app/helpers/application_helper.rb

Requiring pry in production environment when it is limited to dev and test does bad things, man. BAD THINGS!
No Stacktrace, no pry.

Don't require pry

---

app/assets/stylesheets/application.scss

Make application stylesheet scss.
@cdoyle-temple Was working fine in development, but when we switched to `RAILS_ENV=production` for deployments, the `@import` of a file that was not preent caused issues.

Remove import of nonexistent scss file.

---

app/models/marc_indexer.rb
solr/conf/solrconfig.xml

When running multiple traject indexers, the commit requests overlap, causing pain. Let solr autocommit handle that.

Add autocommit, and have traject not commit 

---

app/models/traject_indexer.rb
solr/conf/solrconfig.xml

Solr will auto commit after 1M documents, or 15 minutes, since the last commit.
We might be able to bump these even further depending on how much memory
we throw at the server running solr.

Let solr handle when to commit.

---

Gemfile.lock

Fixes an issue where traject would bomb out on certain records, leaving any subsequent records 
in the same file unindexed.
Fixes #BL-33

Update ruby-marc version for bugfix

---

app/controllers/catalog_controller.rb
app/models/traject_indexer.rb

I took out things that were duplicate entries.  I left commented fields that I wasn't sure whether we planned on using at some point.

Remove duplicate fields from traject indexer and catalog controller

---

app/assets/stylesheets/tucob.css.erb
app/views/catalog/_show_default.html.erb

This addresses the heading and padding.  I couldn't figure out how to override the css for the iframe from blacklight_alma, it seems like the text needs to be indented a little to the left at some point.

BL-68 Add heading and padding to iframe on show page

---

app/controllers/catalog_controller.rb
app/models/traject_indexer.rb
solr/conf/schema.xml
spec/fixtures/marc_fixture.xml

* Removes a lot of unused fields from the controller. 
* Standardize on using `*_display` dynamicField to catch most of our display fields.
* Standardize (mostly) facet filds to use the `*_facet` dynamicField
* All `*_display` fields should now be `copyField`ed into text, to be picked up on all_fields searches.
* Moves `qf` definition into catalog controller, with all of the attendant score boosts. Will make it more apparent how we can do boosting.
* Does a bit more Library Standard Number normalization for ISBN, ISSN and LCCNs.

Rethink solr schema. Move qf into conroller

---

app/models/traject_indexer.rb

Issue #BL-100
Empty string for years was causing range limits to ignore defaults due to a known bug in blacklight_range_limits. This change works around that problem.
See: https://github.com/projectblacklight/blacklight_range_limit/issues/25

Ignore empty string years

---

app/controllers/catalog_controller.rb

We were asking solr to send fields for search results that we didn't end up using in the display. This reduces that, hopefully providing a performance gain.

Shrink the fl params to send less data on search results

---

app/assets/javascripts/tulcob.js.coffee
app/helpers/advanced_helper.rb

When you go to any page on the site you will see this error displayed in the console:
```
Uncaught ReferenceError: select is not defined
```
* Fixes a bug in the Javascript browser console 
* Also fixes clear button "x" does not work on advanced search results by adding rails helper methods REF BL-141

Fix Uncaught ReferenceError: select is not defined.

---

config/bento.yml.example

The current configuration no longer works with our setup.
This commit updates the URL.

Update bento.yml.example api url.

---

docker-compose.yml

You cannot use the pry debugger from a container without adding this
configuration.
See:
http://www.chris-kelly.net/2016/07/25/debugging-rails-with-pry-within-a-docker-container/

Add configuration that allows for pry dubugging.

---

app/views/search/index.html.erb

We will eventually integrate the bento search into the regular search,
but for now it would be nice to be able to go to `/bento` and be able to
search or QA the bento search without having to do any additional steps.

Make the bento search view displayed by default.

---

config/alma.yml.example

Since this code is not a secret, it makes sense to add it to the example
configuration file to avoid needing to enter it manually and potentially
make a mistake in the entry.

Add the institutional code to alma.yml.example

---

app/helpers/advanced_helper.rb
spec/helpers/advanced_search_helper_spec.rb

REF BL-141
Description
===
The current solution to BL-141 has some duplication and will need to be
modified if ever we add or remove fields in the advanced search section.
This PR makes the following changes:
* It refactors the code to make it more resistant to change and
also remove some of the duplication.
* It adds back labels for OR, and AND ops that are missing from
the buttons after a search is done.
* It adds some new tests to this area of the code.
QA Steps
==
the search should continue to have the expected behavior.

Refactors fix for advanced search not clearing.

---

app/assets/stylesheets/tucob.css.erb
app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/views/catalog/_index_default.html.erb
spec/features/indices_spec.rb
spec/features/searches_spec.rb
spec/fixtures/marc_fixture.xml
spec/fixtures/search_features.yml

This PR updates the way availability information is displayed on the index page.
- If a record contains only one online link, clicking online should go directly to the resource.
- If a record has multiple resources, a collapse div appears with all the resource links listed
- If the item is a physical item, clicking 'checking availability' should show the 'get-it iframe'

Bl 158 update availability views

---

app/helpers/advanced_helper.rb
spec/helpers/advanced_search_helper_spec.rb

REF BL-95
Description
===
The current implementation of the #guided_search method incorrectly
assumes that #search_field_def_for_key returns a hash even when a field
is not found for a specific key.  This change corrects that assumption
by coercing nil into a hash before attempting to use it, and also by
coercing nil into an empty string ("") in the case where :label is not
defined in the field definition.

Fix error undefined [] for nil class.

---

README.md
app/controllers/catalog_controller.rb
spec/features/searches_spec.rb
spec/fixtures/search_features.yml

REF: BL-124
Description
===
Move the solr query parameter configs like ps, pf, author_qf, etc, out of the solrconfig searchHandler and into the catalogContoller
Temporarily move this configuration into the catalog controller for ease of use and update. Once our work on relvancy and schema settles down, we can move it back into solrconfig.

Move search params defaults to catalog_controller

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

The separator between e resource links and their data statements was appearing even if the date statement was missing.  Something like:
This pull request makes that go away!!!
* Fetch and checkout his branch
* Run your fave variation on `bundle exec rake server`
* Go to the show page for record with id `991013867929703811`

Only add separator if has date statement in e resource link

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

This adds the new_ui parameter to the openurl links so that the iframe uses the newer version.  To verify, check any physical holding iframe and it should have this updated styling.

Bl 175 update iframe

---

app/views/catalog/_show_availability_section.html.erb

BL-169 Removes the colon from Availability heading for online items in the record display.

BL-169 Update panel heading for online iframe

---

app/helpers/application_helper.rb
app/helpers/blacklight_alma_helper.rb
config/alma.yml.example
spec/helpers/application_helper_spec.rb

BL-180 Allows us to create our own custom css for the alma availability iframe.  The delivery_domain in the alma.yml.example file was also out of date, so that updated to use the sandbox.

BL-180 Add new skin for alma iframe

---

app/controllers/catalog_controller.rb
app/models/traject_indexer.rb
spec/features/record_page_fields_spec.rb
spec/fixtures/features.yml

BL-193 The decision was made to refine the creator field Marc data.
- Creator fields are now labeled "Author/Creator" and only pull from the 100 fields
- Added a new contributor field, labeled "Contributor" that accessing the 700 fields
- The same changes were made for the creator vernacular fields
- Check http://localhost:3004/catalog/991030852609703811 to see that the 700 info is displayed with the Contributor label

Bl 193 update creator fields

---

app/assets/stylesheets/tucob.css.erb
app/views/catalog/_index_availability_section.html.erb
app/views/catalog/_show_availability_section.html.erb

Cleans up some of the issues regarding availability display
- BL-194 Ensure availability buttons in index view are on new lines with space in between when there are both online and physical holdings
- BL-195 Refactor record views so that both online and physical availability are displayed when both are present
- see http://localhost:3004/catalog/991012599009703811 for example

Update electronic links

---

lib/tasks/server.rake

Running bundle exec rake rspec was throwing an error.  This change allows the tests to run.

Add interpolation to .nil?

---

app/views/catalog/_index_availability_section.html.erb

BL-168 Refactors the index availability to remove logic from the view. The decision was made to leave the button logic there since it is creating markup.

Bl 168 refactor index page

---

docker-compose.yml

REF ADO-1
We will need ports 80 and 443 open for our reverse proxy server on
Jenkins QA site.  Thus, we cannot force our instances to be bound to the
hosts 80 or 443 port.

Do not force a bind to port 80 or 443.

---

app/controllers/catalog_controller.rb
config/routes.rb

REF BL-205 BL-112 BL-27
When a user opens the "Date" facet, the range limit should work as
expected.  However, do to a controller mis-configuration an ajax call to
the catalog/range_limit route was throwing 500.
This commit updates the config/routes.rb removing duplications and
organizing it so that it's easier to read.
It also changes the solr range limit field to be pub_date_sort because
that field is indexed as a trint which is the desired format for the
range limit.
QA Steps
==
see a graph with years under it. not a box with -1 and 1 on each side.
http://localhost:3000/catalog/range_limit?range_end=2080&range_field=pub_date_sort&range_start=1100
you should see a list of dates and counts for each date.

Fixes range limit not plugin not working.

---

app/controllers/catalog_controller.rb

REF BL-209
QA Steps
==
* Do a search and click on a document

Do not render Librarian view link.

---

app/views/catalog/librarian_view.html.erb
config/locales/blacklight.en.yml
spec/views/catalog/librian_view.html.erb_spec.rb

REF BL-176
The staff view should allow users to go back to the regular document view.  This Changes adds a "Back to Main View" to the staff view.
QA Steps
===
* Make a search in the catalog.
* Follow a link to a document.
* Follow "Staff View" link to the staff view.

Remove modal button and add back link.

---

app/views/catalog/librarian_view.html.erb

REF BL-176
The "Back to Main View" link does not work in
http://libqa.library.temple.edu/catalog/catalog/991024675119703811/staff_view
where the path to the catalog is double labeled.
This commit fixes this issue by making the path back to the main view
relative to the current path.
QA Steps
==
* Do a catalog search
* Follow a result link to main view
* Follow the staff view link

Use relative path for Back to Main View link.

---

app/assets/stylesheets/tucob.css.erb
app/views/catalog/_show_availability_section.html.erb

A previous styling change made the facets smaller. This adjusts the code so they return to their original size.

Remove style that made facets smaller

---

app/assets/javascripts/tulcob.js.coffee
app/assets/stylesheets/tucob.css.erb
app/controllers/catalog_controller.rb
app/views/advanced/_advanced_search_facets.html.erb

BL-203 Add availability and language facets to advanced search.  I realized the chosen gem styles weren't applying, so made some changes to the css to get it working.  Facets should display in this order:

Bl 203 advanced facets

---

app/models/traject_indexer.rb
lib/traject/macros/custom.rb
spec/features/record_page_fields_spec.rb
spec/fixtures/features.yml
spec/fixtures/marc_fixture.xml

BL-207 Update mappings for title_series_display, date_copyright_display, and note_display fields
- title_series: Add several new fields and create specs for them
- date_copyright: Update logic in the extract_copyright macro to include records with a "c", "p", or copyright symbol in 260c and create tests for each case.
- note_display:  Add the 525a field and create test.

Bl 207 solr display fields

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/models/traject_indexer.rb
lib/traject/macros/custom.rb
spec/features/indices_spec.rb
spec/features/record_page_fields_spec.rb
spec/fixtures/features.yml

BL-45 and BL-91 relating to creator facets and display
- update creator_facet mappings in traject 
- update links in the creator display so that they only link to the creator_facet. 
- non-facet data displays as plain text
- add helper method so that plain text displays are correct in the index view
- update specs based on new mappings
- see http://localhost:3006/catalog/991020062159703811 for example
- Platini, Giacomo should link to author_creator facet results
- composer should display as plain text

Update creator facet and display

---

app/assets/stylesheets/tucob.css.erb

Adds a minimum height to the book cover image box so that empty images don't
have a squished box by default.

Add a minimum height to book image box.

---

app/assets/stylesheets/tucob.css.erb
app/views/advanced/_advanced_search_facets.html.erb
app/views/advanced/_advanced_search_form.html.erb
spec/features/advanced_search.rb

BL-206 Update pub date in advanced search
- move publication year code to the facet partial
- display on one line
- update specs to include the new advanced facets

BL-206 Move pub date to facet partial and display on one line

---

.docker/cli/Dockerfile
.docker/sp/Dockerfile
app/controllers/catalog_controller.rb
app/helpers/advanced_helper.rb
app/models/search_builder.rb
app/models/traject_indexer.rb
app/views/advanced/_advanced_search_fields.html.erb
app/views/advanced/_advanced_search_form.html.erb
app/views/catalog/_show_default.html.erb
config/application.rb
docker-compose.yml
lib/traject/macros/custom.rb
spec/models/search_builder_spec.rb
spec/models/traject_indexer_spec.rb

REF BL-133
Adds a precision operator to allow searches on :is, :begins_with and the
default :contains.
This change requires a Solr reindex to take effect.
Currently *_t fields are automatically flanked with `matchbeginswith`
and `matchendswith`.  On a :begins_with the solr query is changed under
the hood to search for "matchwithbegins foo bar".
The :is "for exact" phrase works in a similar way, by updating the
search value to be quoted instead of free.
*  Download the PR locally and reindex.
verity that they work as you may expect them to.
* I added a new container called "cli" to docker-compose, this adds an
editor which to containers in cases where we need to attach to the
container and edit something directly we don't have to always download
an editor first.
* I made it so that both …

Add a precision operator to advanced searches.

---

app/helpers/application_helper.rb
app/models/traject_indexer.rb
lib/traject/macros/custom.rb
spec/fixtures/features.yml

BL-45 and BL-230 Fixes behavior related to splitting the creator and contributor fields
- Move the creator call inside block so that it displays all creators
- Use trim_punctuation macro for creator_facet
- Use the same regex logic in the browser_creator and creator_index helper methods to display creators and have the links work to creator_facet
- Update fixture file for punctuation

Fix creator contributor

---

.gitignore
.rubocop.yml
Gemfile
Gemfile.lock
spec/controllers/catalog_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/features/advanced_search.rb
spec/features/availability_response_spec.rb
spec/features/basic_page_elements_spec.rb
spec/features/bento_search_spec.rb
spec/features/indices_spec.rb
spec/features/record_page_fields_spec.rb
spec/features/searches_spec.rb
spec/helpers/advanced_search_helper_spec.rb
spec/helpers/catalog_helper_spec.rb
spec/lib/traject/macros/marc_format_classifier_spec.rb
spec/models/traject_indexer_spec.rb
spec/spec_helper.rb

Lots of changes in the spec files here.
- Add the rubocop gem and changed spec files to get rid of syntax offenses
- Uncomment methods in the spec_helper file
- Cleans up code by removing explicit statements of spec type,  be_methodname rather that expressing a boolean value, using capybara negative selectors 
-Add context to conditional specs

Refactor specs

---

app/models/search_builder.rb
spec/models/search_builder_spec.rb

REF BL-234
There are some odd spelling suggestions made when the advanced search query is executed.  I tried many options to fix this but nothing work.  The blunt solution is to disable spelling suggestions altogether when in the advanced search contetext.
QA Steps
===
- Make a search in advanced for "the sun" using the :begins_with precision method.

Disable spelling suggestions during advanced search.

---

app/helpers/application_helper.rb

BL-245 The class was put on the link rather than the li.  This was a causing unordered list bullets to appear in the dropdown on the search results page.  When viewing a dropdown, no bullets should be present.

Move list_items class to li

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_helper.rb
app/helpers/facets_helper.rb
app/views/catalog/_facets.html.erb
app/views/catalog/_home_text.html.erb
lib/traject/macros/custom.rb
spec/features/home_facets_spec.rb
spec/features/indices_spec.rb

BL-244 This updates the text that displays on the home page.  It also uses the blacklight has_search_paramters? method to limit the facets displayed on the home page.  
- The home page should show only the facets for availability, library, and resource type.
- When search terms are used, all facets should render.

Bl 244 update home page

---

lib/tasks/tulsearch.rake
lib/traject/macros/custom.rb
sample_data/bl-196-example-data.xml
spec/fixtures/marc_files/url_field_examples.xml
spec/models/traject_indexer_spec.rb

REF BL-196
* Adds tests for the indexing methods `extract_electronic_resource` and
`extract_url_more_links`
* Refactors said methods
* Adds new functionality to methods (short circuit the
electronic_resource_display map of 856 field when PRT field is/are
present)
* refactors `rake ingest` task to ingest all files within sample_data folder is no file is passed to it.
QA Steps
===
* Set up locally
* Run `rake ingest` task
* Search for "Occupy the spatial dynamics of discourse in global protest movements / Edited by Luisa Martín Rojo."
* Compare that document to current version on libqa: https://libqa.library.temple.edu/catalog/catalog/991026913959703811

Short circuit electronic_resource_display map when PRT field present.

---

app/models/traject_indexer.rb
lib/traject/macros/custom.rb
lib/traject/macros/custom_marc21.rb
spec/fixtures/marc_fixture.xml
spec/models/traject_indexer_spec.rb

BL-230 Testing revealed that trailing periods preceded by a parentheses were not being removed.  
- overrides traject's trim_punctuation macro for creator_facets
- updates the creator_name_trim_punctuation method so that names on record pages link to the facet
- adds specs to test several different punctuation contexts
- in the spec/marc_fixture.xml file record 991012024509703811, you should expect the period to be visible in the middle initial of Whitney, Ellen M. and removed from 4 Learning(Firm)

Update trim punctuation

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
spec/features/record_page_fields_spec.rb

BL-259 Adds the list_with_links helper method to title_addl_display and title_uniform_display
- refactor get_search_params now that there are three different fields using it
- add specs for links
- title_addl_display and title_uniform_display use list_with_links helper method
Going to record 991036813219903811 should display the additional titles as links.

Bl 259 links to titles

---

app/models/search_builder.rb
spec/models/search_builder_spec.rb

REF BL-253
The `parse_queries` method used by some of our search_builder processing
is erroneoulsy dropping boolean operators from the first query.
This change refactors that method so that no information is lost.
* In libqa or locally run an advanced search query where the first query is "contains" "NOT moon" and the second query is connected with (*) AND  "contains" full.  Note the results.
* Pull in the code and run the same query

Fix first boolean operator dropped.

---

app/models/traject_indexer.rb
lib/traject/macros/custom.rb
spec/fixtures/features.yml

Changes the array order of the subfields so that it matches what the facet is returning. 
- this makes changes to traject, so you will need to clean your solr_wrapper and run bundle exec rake ingest.
-  In the record 991000673139703811, you should see Haggard, H. Rider (Henry Rider), 1856-1925 King Solomon's mines.  The data should be returned in that exact order and clicking on the link should take you to the search results page for author/creator Haggard, H. Rider (Henry Rider), 1856-1925.

Update mappings for creator/contributor subfield order

---

app/models/search_builder.rb
spec/features/searches_spec.rb
spec/fixtures/marc_fixture.xml
spec/fixtures/search_features.yml
spec/models/search_builder_spec.rb

REF BL-252
Searches with : in them fail because : is a special field operator character in solr that modifies how the query operates.  Since our users do not know the names of any of our fields, it does not make sense to have this feature enabled.  Otherwise, it is just an unnecessary hurdle for our users.
In order to disable the feature, we need to substitute the colons with spaces. Escaping the character
doesn't work. 
* Depends on #201, review and merge that first.
* Before pulling down the code try searching for "Religious liberty in : America  the First Amendment in historical and contemporary perspective / Bruce T. Murray." locally.  You should get nothing.

Fix search with colons fail.

---

app/models/traject_indexer.rb
lib/traject/macros/custom.rb
spec/fixtures/marc_files/genre_facet_examples.xml
spec/models/traject_indexer_spec.rb

BL-257 Refine genre_facet to exclude certain values.  When viewing the genre facet list, none of the following should appear:  
- CD-ROM|CD-ROMs|Compact discs|Computer network resources|Databases|Electronic book|Electronic books|Electronic government information|Electronic journal|Electronic journals|Electronic newspapers|Electronic reference sources|Electronic resource|Full text|Internet resource|Internet resources|Internet videos|Online databases|Online resources|Periodical|Periodicals|Sound recordings|Streaming audio|Streaming video|Video recording|Videorecording|Web site|Web sites

Genre facets

---

app/controllers/catalog_controller.rb

Deletes the "Export to Endnote" link for now since it won't be ready for the beta launch.

BL-298 Suppress endnotes

---

app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
app/assets/stylesheets/tucob.css.erb
app/views/catalog/_index_availability_section.html.erb

Add arrows for the availability collapse buttons. The buttons should point to the right in initial state, and then toggle down when clicked open and closed.

Add arrows to collapse buttons

---

lib/traject/macros/custom.rb

The code for sorting link elements does not properly handle the nil case
for a record title.  This commit resolves that issue.

Fix sort breaks when title is nil.

---

app/views/users/_user_loans.html.erb
spec/views/users/_user_loans.html.erb_spec.rb

The data viewed had no items that were not renewable. Run test against user with uid: "20180130" to see one item that is not renewable.
Spec for view partial added to verify logic non-renewable indicator logic.

Bl 226 show unable to renew indicator

---

app/assets/stylesheets/partials/_facets.scss

left sidebar, white when active

Updated glyphicons on facets for color contrast.

---

.docker/cli/Dockerfile

Bundle instal fails on my local dev container becuase it needs the
Gemfile handy.

Fix local dev container bundle install.

---

app/models/user.rb

We were not using the proper path to shibboleth attributes 
in the omniauth hash. This corrects that issue

Grab Shibboleth attributes properly from omniauth hash

---

app/controllers/catalog_controller.rb

REF BL-234
Suggestions coming back are strange.  We need to disable this feature
until we can figure out a better way to configure for both "phrase
suggestions" (not sure that's possible).  And also better suggestions
overall (Maybe a smarter dictionary?)

Disable spellcheck feature.

---

app/views/catalog/_index_availability_section.html.erb

The online dropdown button styling for  was overridden by a previous pull request.  This changes  the styling back to what it was before.

Update classes for online buttons

---

app/views/catalog/_show_default.html.erb

Add image tags for covers and default icons to the full record page.

Add image_tags to record pages

---

app/assets/stylesheets/tucob.css.erb
app/views/catalog/_show_availability_section.html.erb

Online only availability iframe on the record pages show no bottom-border

Remove bottom-border from online only items

---

app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js

Updates status for checked out materials to include the library name.  
- A search for 991021718189703811 should display like this:

Update label for availability status

---

spec/features/home_facets_spec.rb
spec/rails_helper.rb

By adding a `have_text` expectation we force capybara to retry
for up to 2 seconds (by default).  This makes sure that we get the
number of facets on the rendered search page instead of potentially on
the front page where it will be 3 thus creating a false negative when
3 is not < 3.

Make spec less brittle to timing issues.

---

app/assets/stylesheets/tucob.css.erb

Hide the top start over button on the advanced search results page.

#BL-297 Update layout/styling for Advanced Search

---

app/assets/stylesheets/tucob.css.erb
app/helpers/application_helper.rb

Added new tab targets to eresource links in the availabilty sections of the search results and record pages, with title text on the anchor tags for ADA purposes

#BL-305   Re: Electronic resource links open with new tab

---

lib/oai/alma.rb
lib/tasks/jenkins.rake
lib/tasks/oaiharvest.rake

REF BL-329
REF BL-330
Once we broke up the harvest to happen for two different solr instances
we needed a way to run both jobs using the same parameters.  That means
we have to parameterize along the from and to options as well as the
solr URL.  Otherwise two consecutive calls to the job results in two
different sets of parameters.
This PR updates the task to allow us to parameterize the job as well as
adds a new task to allow us to capture the last build time in a way that
we can apply it to multiple Jenkins builds.
This PR also fixes a bug where we are using the wrong URL for the next records to fetch, as well as adds more logging to the standard output so that we see more info in the console.log for the jenkins job that ultimately uses this task.
Finally, this PR fixes a bug were not …

Refactor harvest timing code.

---

solr/conf/solrconfig.xml

Defaults to smaller caches, but make configurable to allow setting higher values on a machine with more memory, like production.
More reading is available at https://lucene.apache.org/solr/guide/6_6/query-settings-in-solrconfig.html#QuerySettingsinSolrConfig-queryResultCache
Additionally, adds a config to log slower queries, as per https://lucene.apache.org/solr/guide/6_6/configuring-logging.html

Add configurable solr cache

---

docker-compose.yml

I noticed an issue when I have multiple instances running where a solr
instance is being shared between multiple containers vs having it's own
solr.
This commit fixes that issue.

Use default network between containers.

---

app/helpers/advanced_helper.rb
app/models/search_builder.rb
app/views/advanced/_advanced_search_fields.html.erb
spec/helpers/advanced_search_helper_spec.rb
spec/models/search_builder_spec.rb

REF BL-291
REF BL-334
The advanced search form is not currently using the default values for
the operators which are available in the blacklight_params.
This PR also addresses an issue where the op_row field on multiple searches without hitting the "restart" button in between the searches, was appending new values to the op_row array in the params object and then we were not using the newer values.

Use default values in form

---

app/helpers/application_helper.rb

REF BL-304
URLs with & are failing for author/creator links because they are not
being URL encoded.
This commit makes sure to properly encode those fields so that links do
not fail.

URL encode author/creator label in links.

---

app/models/traject_indexer.rb
lib/traject/macros/custom.rb

BL-333 Adds the x subfield to 650 and adds a separator between the a and x fields. It also returns only uniq values because sometimes cataloguers write the x subfield information inside the a subfield.  When looking at an A-Z sort of subject topic facets for a search on "adoption", you should see only one instance of "Abbasids--Early works to 1800" and "Adoption--Fees" should display with a separator between the words.

Bl 333 subject topic facet

---

app/controllers/catalog_controller.rb
app/models/traject_indexer.rb
lib/traject/macros/custom.rb
spec/features/record_page_fields_spec.rb
spec/fixtures/features.yml
spec/fixtures/marc_fixture.xml

BL-266 Modify and add fields for special collection links
- Add new finding_aid_field for links that include both "http://library.temple.edu" and "scrc"
- Links that include archive-it should display under the "Other Links" label.

Finding spec problem

---

app/helpers/advanced_helper.rb
spec/features/advanced_search_spec.rb
spec/helpers/advanced_search_helper_spec.rb

BL-319 Restores the field labels to constraints for advanced search
- The results for an advanced search should display the field name and search query term
- If and, or was used then there should be a constraint shown for each query term
- When not was selected, the "NOT" keyword should be displayed in the constraint as well

Constraints

---

app/views/catalog/_search_form.html.erb
spec/features/indices_spec.rb
spec/fixtures/features.yml

BL-283 Fixes two bugs related to basic search in the advanced view.
- Replaces the advanced search link with a Basic Search link back to the home page
- Uses the search_catalog_url which allows you to use basic or advanced search in the advanced view
- Updates specs because the search_catalog_url adds /catalog to the search results url

Basic search

---

lib/oai/alma.rb

It seems that if the file remains open, then it cannot be used in the
purging process.

Make sure to close file after write.

---

app/helpers/alma_data_helper.rb
config/application.rb
config/process_types.yml
spec/helpers/alma_data_helper_spec.rb

BL-357 Adds additional logic into unavailable items according to their process type.
- created a new translation map to convert process_type values into the necessary messages
- On record 991022252979703811, Availability should display as "Checked out" at Paley and "Available" at Ambler
- record 991026548529703811 should display as "At another institution" for Resource Sharing Library

Bl 357 process type

---

lib/traject/macros/custom.rb
spec/fixtures/marc_files/subject_topic.xml
spec/fixtures/marc_files/subject_topic_missing.xml
spec/models/traject_indexer_spec.rb

`subject = [].first` returns nil which causes error when `subject.split`
is called in the next line.  This commit fixes that issue.

Fix no method on nil error.

---

lib/traject/macros/custom.rb
spec/fixtures/marc_files/url_field_examples.xml
spec/models/traject_indexer_spec.rb

The updated logic for electronic_resource_display excludes archive-it links, but these items were still being indexed into online availability.
I think this is what was causing the nil electronic_resource_display problem on libQA
Added specs for online availability, finding aid display, and added more specs for new logic in electronic_resource_display and url_more_links_display

Adds specs and updated logic for online availability

---

app/views/advanced/_advanced_search_facets.html.erb
app/views/advanced/_advanced_search_fields.html.erb

BL-323 Update advanced search form for greater accessibility
- add sr-only labels to form inputs
- chosen dropdown are not currently compliant, looks like they are working on it

BL-323 Add labels to advanced search for accessibility

---

app/helpers/alma_data_helper.rb
app/views/almaws/item.html.erb
spec/helpers/alma_data_helper_spec.rb

BL-366 Library names should only display once, regardless of how many copies there are at that library
- Record 991025629919703811 should display "Paley Library" once
- Temporary libraries should display instead of library name if item is in a temporary library
- Record 991026548529703811 should display "Resource Sharing Library" NOT "Paley Library"

Bl 366 library display

---

app/helpers/alma_data_helper.rb
spec/helpers/alma_data_helper_spec.rb

BL-369 Display "library use only" for availability of non-circulating items.
- Sample data record 991012599009703811 should have the text "library use only" under availability

Bl 369 library use only

---

app/views/almaws/item.html.erb

BL-375 and BL-221 Include default message on record pages for records that do not have any item data
- 991004349569703811 Should display the default message

Add default message for records with no item data

---

app/helpers/application_helper.rb
app/views/catalog/_index_availability_section.html.erb
spec/fixtures/marc_files/url_field_examples.xml
spec/fixtures/marc_fixture.xml
spec/models/traject_indexer_spec.rb

BL-385 Update the logic for electronic_resource_display to try to fix libQA issue with records that have no electronic_resource field
- Add data for specs
- Move logic out of view and into helper methods

Bl 385 link helper bug

---

app/helpers/advanced_helper.rb

REF BL-391
Fixes warning:
```
DEPRECATION WARNING: search_field_def_for_key is deprecated and will be
removed from blacklight 7.x (Use blacklight_config.search_fields[key]).`
```

Fix advanced_search_helper deprecation warning.

---

app/helpers/alma_data_helper.rb
spec/fixtures/marc_fixture.xml
spec/helpers/alma_data_helper_spec.rb

BL-373 Items with a process type of missing or lost should not display in the availability data. 
- Alma mms_id 991016705469703811 in the spec/fixtures/marc_fixture.xml file should display the copy that it available, but not the copy that is missing

Suppress holdings

---

app/controllers/concerns/catalog_config_reinit.rb
app/controllers/primo_central_controller.rb
app/controllers/search_controller.rb
app/helpers/application_helper.rb
app/helpers/search_helper.rb
app/models/bento_search_builder_behavior.rb
app/models/blacklight/primo_central/search_builder_behavior.rb
app/models/search_builder.rb
app/search_engines/bento_search/blacklight_engine.rb
app/search_engines/bento_search/books_engine.rb
app/search_engines/bento_search/journals_engine.rb
app/search_engines/bento_search/more_engine.rb
app/views/bento_search/_more.html.erb
app/views/search/_facet_layout.html.erb
config/initializers/bento_search.rb
spec/fixtures/vcr_cassettes/bento_search_more.yml
spec/models/search_builder_spec.rb
spec/search_engines/bento_search_spec.rb
spec/search_engines/more_search_spec.rb

REF BL-378
Adds a bento box that grabs the format facet from the catalog
search and filters out "Book" and "Journal/Periodical" facets if
included:
Some other enhancements include.
* Does not search for facets in non facet bento searches
* Only searches for the facet.field = format for the more bento search.

Add "More" bento box.

---

app/views/search/index.html.erb
spec/features/bento_search_spec.rb

REF BL-400
This PR removes the redundant bento search bar once #344 (BL-378) gets
merged. It also removes the advanced_search link from that page because
it causes issues with search.

Remove redundant search bar.

---

app/controllers/search_controller.rb
app/helpers/application_helper.rb
app/search_engines/bento_search/blacklight_engine.rb
app/search_engines/bento_search/books_engine.rb
app/search_engines/bento_search/journals_engine.rb
app/search_engines/bento_search/primo_engine.rb
config/initializers/bento_search.rb
config/locales/bento.en.yml
spec/search_engines/primo_search_spec.rb

REF BL-402
Refactor the primo search engine so that it uses PrimoCentralController
Additionally,
* Relabels the "Primo" box "Articles"
* Adds link to search results in Blacklight articles view
* Refactors out some common code to `results` method

Update articles bento box.

---

app/models/blacklight/primo_central/search_builder.rb

BL-REF 386
When I did the merge conflict resolution for the bento concurrency lock
fix, I managed to not add the query processor that fixes the next-previous
button fix.  This commit adds that back.

Add back :previous_and_next_document to pc.

---

app/helpers/alma_data_helper.rb
app/views/almaws/item.html.erb
spec/helpers/alma_data_helper_spec.rb

BL-374 Physical items should be sorted first by library name, then location, call number, and description

BL-374 Add sort order for holdings

---

app/models/blacklight/primo_central/document.rb
spec/models/primo_central_document_spec.rb

REF BL-407
Sometimes we grab values from the query strings of the document link.
Some query values end up being [""].  These need to be filtered out or
they end up making field values appear with blank values.

Filter out query values equal to [""].

---

app/helpers/primo_central_helper.rb
app/models/blacklight/primo_central/document.rb
app/views/primo_central/_direct_link.html.erb
app/views/primo_central/_online.html.erb
app/views/primo_central/_show_availability_section.html.erb
spec/helpers/primo_central_helper_spec.rb
spec/models/primo_central_document_spec.rb
spec/views/primo_central/_online.html.erb._spec.rb

REF BL-395
REF BL-396
Refactors availability rendering for primo_central and allows for
a switch between either the iframe view or a direct link to the
resource.

Add direct link to availability if available.

---

app/helpers/alma_data_helper.rb
spec/fixtures/marc_fixture.xml

There seems to be a situation where loan policy is not always provided.  
- Handles the case where policy has no data

Fix issue with embedded content error for records with no policy data

---

app/helpers/primo_central_helper.rb
app/models/blacklight/primo_central/document.rb
app/views/primo_central/_direct_link_button.html.erb
app/views/primo_central/_index_availability_section.html.erb
app/views/primo_central/_online_button.html.erb
spec/helpers/primo_central_helper_spec.rb

REF Bl-397
Adds either a direct link or iframe button to the result index items for
article searches (primo central)

Add online button to index result.

---

app/models/blacklight/primo_central/document.rb
config/locales/en.yml
spec/helpers/primo_central_helper_spec.rb

REF BL-395
Followup on BL-395. Do not attempt to get direct link label from
response.

Use default label for direct link.

---

app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
app/helpers/alma_data_helper.rb
spec/helpers/alma_data_helper_spec.rb

BL-417 Sorts the availability by library in the search results view.
- "Available at Paley Library" should come first when the item is at multiple locations
- only unique library names should be displayed

Library info search results

---

app/controllers/catalog_controller.rb
app/controllers/primo_central_controller.rb
app/helpers/application_helper.rb
app/helpers/catalog_helper.rb
app/helpers/primo_central_helper.rb
spec/helpers/primo_central_helper_spec.rb

REF BL-409
Add a primo specific `browser_creator` helper method so that links creator values to primo creator queries vs faceted query.
To do this we need to move `browser_creator` method to be a helper_method so that we can selectivly override it in the `PrimoCentralController`

Refactor browse_creator for primo.

---

app/assets/stylesheets/tucob.css.erb
app/controllers/catalog_controller.rb

Changes requested for the user testing next week
- Availability facet should not have a heading, label, or collapse arrow

BL-421 Modify availability-facet for user testing

---

app/assets/stylesheets/tucob.css.erb
app/views/almaws/item.html.erb
app/views/catalog/_show_availability_section.html.erb

BL-416 Tweaks to availability styles per Rachel
- add border
- record page availability panel has a Temple red header with white text
- record page availability has no extra padding at the bottom
- All text is aligned to the left, including the Availability header

BL-416 Adjust styles for availability panels

---

config/routes.rb

Blacklight does some metaprogramming to add a data-attribute to the results links.
https://github.com/projectblacklight/blacklight/blob/v6.15.0/app/helpers/blacklight/url_helper_behavior.rb#L62-L87
Which is then used by BL js to track the search and redirect to the result page.
We needed a route in the form "track_#{controller_name}_path" or else BL uses the default,
in the form of  `/catalog/:id?track=....`
Results links for articles should now work as expected.
Fixes BL-420

Fixes tracking links for articles.

---

lib/traject/macros/custom.rb
spec/lib/traject/traject_indexer_spec.rb

REF BL-419
Flatten the topics value on index so that [["value"]] does not get sent
to Solr.
To test.
* Re-index and search for "Catholic Church"
* Verify that you do not see the topics facet field "[Catholic Church]"

Flatten the topics value on index.

---

app/helpers/advanced_helper.rb
app/models/search_builder.rb
app/views/advanced/_advanced_search_fields.html.erb
spec/features/advanced_search_spec.rb
spec/helpers/advanced_search_helper_spec.rb
spec/models/search_builder_spec.rb

REF BL-323
Do to a change introduced in BL-323 (#376) we no longer add an
individual operator per field row query.  Instead we use one operator
for all queries.
This update fixes that issue by replacing occurrences of `op_row` with the
new name, `operator`.

Fix single operator used for all advanced query.

---

app/assets/javascripts/book_covers.js
app/helpers/catalog_helper.rb

REF BL-470
I've studied the code for generating the google_book images and found
multiple  potential sources of issues that can cause images to not show
up when they otherwise might.
1. We are only selecting one id item from lccn or isbn number even when
multiple are present.  We are selecting the first item.  But this can
cause issues if the sort order is different in different system.
2. We are choosing either the lccn or isbn number but not both.
3. We are not properly handling cases where the id is returned as
a string and not a list of ids.
This change updates the book-image code to search for images on multiple
id and id types so that sorting is not an issue and so that if one id
fails we still try other ids that might return a book image.
This change also fixes handling the case …

Fix google_book image not showing up.

---

Gemfile.lock
app/helpers/alma_data_helper.rb
app/views/almaws/item.html.erb
spec/helpers/alma_data_helper_spec.rb

BL-469 Adds physical_material_type from the alma api to certain types of records
- It should not display for Book, Issue, Music Score, Kit, Map, Bound Issue, Government Document, Other
- Displays in the third column of the availability table

BL-469 Add physical_material_type

---

app/assets/stylesheets/partials/_bento.scss
app/views/search/_more_facets.html.erb
app/views/search/index.html.erb

BL-474 Changes to bento results styling:
- Remove gray background from Resource types and make text smaller
- Add width to columns to align with basic search input and my library account

BL-474 Update styles for bento

---

app/assets/stylesheets/tucob.css.erb
app/helpers/application_helper.rb
app/views/catalog/_index_availability_section.html.erb
app/views/catalog/_show_availability_section.html.erb
app/views/primo_central/_direct_link.html.erb
app/views/primo_central/_show_availability_section.html.erb

BL-477 Add styling to online availability display:
- Tan header
- even spacing
- borders between links

BL-477 Update styles for online availability

---

config/routes.rb

REF BL-414
Adding a similar configuration to the app router fixed a similar issue
with primo_central tracking so I'm hopping this will do the same for
catalog/bookmarks tracking on libqa.
For example the following track requests fail with 404:
```
https://libqa.library.temple.edu/catalog/catalog/991017730139703811/track?counter=1&search_id=2708
https://libqa.library.temple.edu/catalog/TN_crossref10-dot-1177-slash-0361684312464862/track?counter=4
```
We should probably add a redirect for catalog/:id/track where :id
matches /^TN_/, too.

Try to fix libqa routing issue.

---

Gemfile.lock
app/controllers/primo_central_controller.rb
app/models/blacklight/primo_central/repository.rb
app/models/blacklight/primo_central/search_builder_behavior.rb
app/views/primo_advanced/_advanced_search_fields.html.erb

REF BL-398
* Fixes the wrong operator being set for is(exact) searches.
* Fixes wrong field used for subject field.
* Allows Search of description.
Issues that cannot be addressed with this PR.
* start_with/begins_with operator has bug on primo API end
* NOT boolean operator is currently working as expected but we should revisit UI.
* Start over works a expected because facets require a search to appear.

Follow up on some article advanced search issues.

---

.travis.yml
spec/features/advanced_search_spec.rb
spec/features/bento_availability_spec.rb
spec/relevance/keyword_spec.rb

Made a few tests less brittle to more records being present.
Removed a few duplicated records in the test_search fixture

Fix tests that break when relevance tests are run.

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

Don't treat lower-case "and", "not", "or" as boolean operators, only the upper-case versions.

No lowercase booleans

---

lib/traject/macros/custom.rb

When we were using 260 for date field there was some ambiguity about
where and what the four digit date was in the field.  Thus, a search of
the string was necessary.
However, now that we are using field 008, the four digit date is in
a very specific area per a standard.  Thus a search is not needed.
I'm not removing the method for now because it still may prove useful.
(But I'm also OK removing that method if that's a better choice).
@see https://www.loc.gov/marc/bibliographic/bd008.html

Do not use four_digit_year method unnecessarily.

---

app/helpers/application_helper.rb
lib/traject/macros/custom.rb
spec/fixtures/marc_files/url_field_examples.xml
spec/helpers/application_helper_spec.rb
spec/lib/traject/traject_indexer_spec.rb

REF BL-480
* Updates the traject indexer configuration to capture a record's
availability.
* Skips building a link to unavailable records.
* Removes premature compact of data that breaks structural integrity of
the electronic_resource_display field.

Index record availability and skip unavailable items.

---

app/assets/stylesheets/partials/_header.scss
app/views/advanced/_search_form.html.erb
app/views/application/_search_form.html.erb
app/views/primo_advanced/_search_form.html.erb
app/views/primo_advanced/index.html.erb
app/views/shared/_header_navbar.html.erb

REF BL-486
* Removes the basic search bar from the advanced/articles_advance pages.
* Removes top "Start Over" button from articles_advance page.

Remove basic search bar from advance searches.

---

config/environments/production.rb

REF BL-241
Depends on setting BOOKS_AT_TEMPLE_PASSWORD environment variable.
To test configuration locally:
* Open up the `rails console` and add the following:
```ruby
Rails.application.configure do
config.action_mailer.smtp_settings = {
address: "smtp.gmail.com",
port: 587,
domain: "temple.edu",
user_name: "books@temple.edu",
password: "NOT_THIS_PASSWORD_THE_REAL_ONE",
authentication: :plain,
enable_starttls_auto: true
}
end
ActionMailer::Base.mail({
from: "books.temple.edu",
to: "your_email_hear",
subject: "Test",
body: "Test",
}).deliver_now
```

Configure email.

---

Gemfile
Gemfile.lock

Honeybadger, it turns out, does give a functional assistance in debugging errors in production.
Blocked by https://github.com/tulibraries/tul_cob_playbook/pull/8

Add Honeybadger

---

lib/tasks/oaiharvest.rake

The default is 60 seconds.
I'm not currently changing the open_timeout because the default is nil
which I'm taking that to mean max.  The open_timeout is the time to wait for
opening a connection which is not what we are having issues with.

Double the read_timeout time.

---

lib/traject/macros/custom.rb
spec/fixtures/marc_files/url_field_examples.xml
spec/fixtures/marc_fixture.xml
spec/lib/traject/traject_indexer_spec.rb

BL-492 Removes inactive electronic links from the Online availability facet

Remove inactive elec links from avail facet

---

app/models/blacklight/primo_central/repository.rb

In order to hook into the 404 status for article ids that are not found
we need to raise a Blacklight::Exceptions::RecordNotFound exception;
Otherwise, a nonsensical page is rendered to the user.

Raise exception for article id search not found.

---

app/models/concerns/blacklight/document/email.rb
app/models/solr_document.rb
config/locales/blacklight.en.yml

REF BL-500
Unfortunately the way to add fields to emails and sms differs from the
standard way of adding fields in other contexts.
I've created a BL issue to address this. But because that work may
likely introduce some backwards incompatibility, I decided to implement
this change in the non standard way and I may in the future refactor
this work to add the fields via the catalog controller per change in BL.
see https://github.com/projectblacklight/blacklight/issues/1923

Add custom meta data to catalog email record.

---

app/views/advanced/_advanced_search_form.html.erb

REF BL-509
@see also:
https://github.com/projectblacklight/blacklight_advanced_search/pull/81
Fixes issue where advanced search gets polluted with basic search
params.

Exclude basic search fields from advanced search.

---

app/views/catalog/_index_default.html.erb

REF BL-512
This div was removed by mistake when refactoring index fields view in
order to re-use inside of the bento more search.

Add back div removed by mistake.

---

app/controllers/application_controller.rb
app/controllers/users/sessions_controller.rb
app/helpers/users_helper.rb
app/views/shared/_nav_bar_login_links.html.erb
config/routes.rb

REF BL-522
This commit adds a way to generate login forms that can dynamically
redirect the user to a specified path.
The current default redirect path for the My Accounts link has been set to
"/users/account".

Redirect user to "users/account" after login.

---

app/models/blacklight/primo_central/repository.rb

REF BL-536
There are times when a valid id may not be returning articles from the pnx
api.  We want to monitor these events to be able to report issue.
This commit updates the exception thrown when an article is not found so
that the controller does not gracefully handle the event and the
exception gets sent to honeybadger.

Monitor articles not found.

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

Improves known item searching.
This broke one test, which had to be tweaked to continue working

Make the min must match tighter.

---

app/controllers/almaws_controller.rb
app/javascript/packs/controllers/form_controller.js
app/views/almaws/_booking_request_form.html.erb
app/views/almaws/_digitization_request_form.html.erb
app/views/almaws/_hold_request_form.html.erb

Adds browser validations to request forms
- Hold: pickup location, description (if present) are both required
- Booking: start date and end date (dates must be in the future and end date not greater than 8 days after start date), pickup location, material type
- Digitization: title, author, start page, end page, comments(only if partial is selected)

Add validations for request forms

---

app/views/catalog/_index_availability_section.html.erb
spec/features/indices_spec.rb

This fixes the shibboleth redirect login, which was broken when we moved the rendering of the Request button outside the Availability panel. The requisite instance variable was no longer defined, so it was not providing any request info.
While I can reproduce the fix in the browser, I cannot get the fixed behavior to work in Capybara. The link never includes the `redirect_to` parameter. 🤷‍♂️ 
I've added a pending capybara test so we can come back to it, but grrrrrrrrr.

Refix shibboleth login redirect

---

app/assets/stylesheets/partials/_bento.scss
app/controllers/search_controller.rb
app/helpers/primo_central_helper.rb
app/helpers/search_helper.rb
app/views/bento_search/_std_item.html.erb
app/views/catalog/_fields.html.erb
app/views/search/_bento_results.html.erb
app/views/search/index.html.erb
config/initializers/bento_search.rb

REF BL-534
* Refactor to allow boxes to include linked boxes (children)
* Link "resource types" box to "more" box.
* Updates engine title link color to black
* Remove labels for type fields.
* Add type fields to Article items

Additional updates to bento UX.

---

app/controllers/sessions_controller.rb
spec/controllers/sessions_controller_spec.rb

REF BL-565
The xhr format of the sign in form is the simple form we get in modal
context.  If the browser caches that before it caches the regular form,
then clicking the back button after logout from account page will bring
you back to a very simple page with a form in it (the modal context sign
in).
The expected behavior is that clicking the back button will bring you
to the regular sign in (non modal) page.  This is achieved by not allowing the
browser to cache the modal sign in page.

Do not cache the xhr format of sign_in form.

---

app/assets/stylesheets/partials/_facets.scss
app/views/catalog/_previous_next_doc.html.erb

REF BL-567
Fixes back-to-search button and start-over button styling broken after
merging #557 (REF BL-551).

Fix back to search button.

---

app/controllers/almaws_controller.rb
app/controllers/catalog_controller.rb
app/views/catalog/_index_availability_section.html.erb
app/views/catalog/_show_availability_section.html.erb
bin/boundwith_process.rb
lib/traject/indexer_config.rb
lib/traject/macros/custom.rb
solr/conf/schema.xml
solr/conf/solrconfig.xml
spec/controllers/catalog_controller_spec.rb
spec/fixtures/marc_fixture.xml

This PR allows :wastebasket: :fire:  records, otherwise known as boundwith records, to have availability information displayed and be requested.
Did I mention they were a total :wastebasket: :fire: ?
It also adds logic to skip Host (parent) records so they are not skipped.
Whoever takes this on to review, I can send you the marc file with the required records that are created in a separate process
Just for good measure
:wastebasket: :fire: 
:wastebasket: :fire: 
:wastebasket: :fire: 
:wastebasket: :fire: 
Also a :garbagefire:

Bl-317 allows boundwith records to have availability shown and to be requested 

---

app/controllers/almaws_controller.rb

Holds at bib_level
- adds error messages if request isn't successful
- still trying to get the flash messages back for hold requests

Revert to bib_level hold requests

---

lib/traject/macros/marc_format_classifier.rb
spec/fixtures/marc_files/no_govdoc.xml
spec/lib/traject/macros/marc_format_classifier_spec.rb

REF BL-549
Limits what is considered a govdoc by including a leader/06 field query.

Update format field indexing.

---

app/views/catalog/_search_results.html.erb

Uses params[:controller] rather than filtering current_page method by controller

Refine if/else statement for page_title

---

app/javascript/packs/controllers/form_controller.js
app/views/almaws/_digitization_request_form.html.erb
app/views/almaws/_hold_request_form.html.erb

Some browsers allow text input for date fields
- add pattern to include only numbers
- set custom validation message to alert the correct format to the user

Add browser validations for date field

---

app/views/almaws/request_options.html.erb

Text was not displaying when there were no request options
- adds .present to aeon_button
- changes message to users

Check whether aeon button is present

---

app/models/blacklight/primo_central/document.rb

REF BL-584
REF https://app.honeybadger.io/projects/56250/faults/39105905
Rescue from exception thrown when paring a URI.
(This time around the issue was caused because URI string had a newline
at end, but any number of things can ultimately cause this issue so it's
better just to rescue than to try to catch them all.)

Rescue from URI.parse exception.

---

app/models/blacklight/primo_central/search_builder_behavior.rb
spec/models/primo_search_builder_spec.rb

REF BL-587
REF
https://app.honeybadger.io/projects/56250/faults/39100209/29996d82-a095-11e8-98d0-ca2cc93f1c04
Under certain conditions field type can be set to :advanced by the app.
We force :advanced to be set to :any when passed to primo.

Fix attempt to use unknown field :advanced.

---

app/models/blacklight/primo_central/search_builder_behavior.rb

REF BL-600
I'm not sure why I added the processor in the first place.  But testing
many types of ids I have not found a case where replacing dashes with
spaces makes a difference other than in potentially increasing the
number of results since value becomes multi-valued.

Remove id processor that causes multi returns.

---

app/lib/cob_alma/requests.rb
app/views/almaws/_booking_request_form.html.erb

The description field is displaying when it only includes an empty string.  This adds more logic to filter those results out.

Don't allow an array with an empty string in booking request descr

---

app/controllers/almaws_controller.rb
app/views/almaws/_booking_request_form.html.erb
app/views/almaws/_digitization_request_form.html.erb
app/views/almaws/_hold_request_form.html.erb
spec/controllers/almaws_controller_spec.rb

Different browsers display the date field in different formats
- defaults to a "MM-DD-YYYY" string as the default value
- updates the regex patterns to use MM-DD-YYYY format

Update date fields to be MM-DD-YYYY

---

app/assets/stylesheets/tucob.scss.erb
app/helpers/application_helper.rb
app/views/almaws/item.html.erb
app/views/almaws/request_options.html.erb
app/views/catalog/_aeon_request.html.erb
app/views/catalog/_index_availability_section.html.erb
app/views/catalog/_show_availability_section.html.erb

This moves the aeon button back into the availability panel
- Button should display only for SCRC materials and will be on the same row as the library name

Bl 609 aeon requests

---

app/views/almaws/_booking_request_form.html.erb
app/views/almaws/_digitization_request_form.html.erb
app/views/almaws/_format_date_message.html.erb
app/views/almaws/_hold_request_form.html.erb

BL-608 The format date message could be confusing for users that see the date presented in a different format
- limit the message to only browsers that don't support the date field (safari and internet explorer)
-safari view 
- chrome view

Only show date format message for unsupported browsers

---

app/helpers/application_helper.rb
app/views/catalog/_index_header_default.html.erb
spec/fixtures/marc_fixture.xml

Shortens titles in the search results to 300 characters
- see 991004250539703811 in the marc_fixture.xml file for an example

Bl 580 truncate titles

---

app/views/layouts/blacklight.html.erb

BL-585 The stimulus polyfills are not working because the blacklight_alma javascript errors before stimulus is loaded
- Puts the Webpacker javascript before the javascript_include_tag to see if the polyfills are loaded first and work for blacklight_alma javascript too

Move javascript_pack_tag before include_tag

---

app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
spec/fixtures/marc_fixture.xml

The availability button was never leaving the loading state for items with empty holdings
- You should now see the "Not Available" collapse button for those records

Show availButton for lost or missing items

---

app/controllers/primo_central_controller.rb
app/models/blacklight/primo_central/search_builder.rb
app/models/blacklight/primo_central/search_builder_behavior.rb
spec/models/primo_search_builder_spec.rb

REF BL-514
Adds sorting to article searches.  The fields used are the same as what
is currently available in the catalog search.
Neither `creator` nor `date2` sorting is working.  We might need to
bring it up with Exlibris.
Depends on #626

Add sorting fields to articles.

---

app/assets/javascripts/_polyfills.js
app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js

I was taking a look at blacklight_alma_libs.js and it's getting to be
pretty big file.
This change moves polyfills to another file where we can keep easier
track of it and also replaces the`includes` function polyfill
with some more robust versions (sources linked).

Move polyfills to separate file.

---

app/assets/stylesheets/tucob.scss.erb
app/views/advanced/_advanced_search_submit_btns.html.erb
app/views/primo_advanced/_advanced_search_fields.html.erb
app/views/primo_advanced/_advanced_search_submit_btns.html.erb

BL-637 More styling for the advanced catalog/article submit buttons
-buttons should be aligned with the ends of the search query inputs

Align advanced submit buttons with search fields

---

app/controllers/concerns/primo_fields_config.rb
app/controllers/primo_central_controller.rb
app/models/blacklight/primo_central/document_export.rb
app/models/primo_central_document.rb
app/views/primo_central/_tagged_refworks.erb
spec/controllers/primo_central_controller_spec.rb
spec/models/primo_central_document_spec.rb

REF BL-412
This cannot be tested locally, but I set up a gist to show that the outputed format imports as expected:
http://www.refworks.com/express/expressimport.asp?vendor=Library+Search&filter=RefWorks+Tagged+Format&encoding=65001&url=https%253A%252F%252Fgist.githubusercontent.com%252Fdkinzer%252F2690c9e7cec861015b89c542ca7b7a07%252Fraw%252Ff23b391fe8261866d6a75f76b3532327e10add83%252Ftul_cob_refwork

Allow export of articles in Refworks tagged format.

---

app/controllers/concerns/primo_fields_config.rb

The sort options should appear in this order: relevance, date, author/creator, title.

Reorder the article search sort fields.

---

app/models/blacklight/primo_central/document_export.rb

This change refactors how we generate the refwork version of the
document so that the configuration portion is an override of the default
behavior.
This also makes it possible for blacklight_config to be `nil` which could potentially happen in some circumstances.

Refactor refworks map.

---

app/controllers/application_controller.rb

REF BL-576
There is a cross-site-request-forgery session token that gets added
to pages.  If a user signs in and then signs out and then tries to go
back (without reloading page) the same token appears and this causes
rails to raise an authentication exception if the user tries to follow
a link.
There are tricks to get around this involving updating the token using
javascript but this approach seems too risky since it's essentially
trying to circumvent a security measure by poking holes in it.
The best solution I could find that has no security issues is to simply
force a reload of the page the user is trying to work with.

Force reload of referer if user gets auth error.

---

app/models/blacklight/primo_central/search_builder_behavior.rb
app/search_engines/primo_central_bookmark_search.rb

The new api has a limit of 13 vs 9 OR queries. This change reflects that
change.

Update limit on article OR queries.

---

app/assets/stylesheets/tucob.scss.erb

I'm not sure why this is causing libqa to look funky but removing
removes two of the current console errors.

Remove css that is breaking libqa.

---

app/controllers/almaws_controller.rb

Coming across the almaws_controller can be confusing at first if you
don't know that alma api is too slow to use to get field information
when the document is first fetched.

Add documentation about why almaws controller exists.

---

app/models/search_builder.rb
spec/models/search_builder_spec.rb

I'm getting an error locally and on libqa when I go directly to
http://localhost/catalog/991026950679703811
The issue is caused because the operator param is getting passed with
non query keys (which is unexpected).
This commit fixes the issue by making sure we don't process non query
values.

Do not process non query values.

---

app/helpers/advanced_helper.rb
app/views/primo_advanced/_advanced_search_fields.html.erb
spec/helpers/advanced_search_helper_spec.rb

REF BL-655
To test:
* Go to articles advanced search
* Search for `all_fields is home OR all_fields is work`
* After being redirected to search results return to advanced search.
* Verify that `is` is still selected as operator.

Fix advanced article search params clobbered.

---

app/assets/javascripts/application.js
app/assets/javascripts/listeners.js

On our locals `GoogleAnalytics.valid_tracker?` returns false so the `ga`
libraries will never get loaded.  However, we have some click event
listeners that use `ga`.
This change updates the event listener code in two ways:
* It moves a handler function closer to where it is actually being used
* It adds a check to make sure `ga` has been defined.

Fix undefined use of reference to ga.

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
spec/features/record_page_fields_spec.rb
spec/helpers/application_helper_spec.rb

Our previous links were not functioning properly. Records were either linking to general subjects or displaying no results.  This methods makes sure that subject links are based on the facet and only search the exact match.

BL-649 Creates a new helper for subject links.

---

app/controllers/primo_central_controller.rb

REF BL-412
Although the current docs list :YR as the refwork for year, this does
not seem to work as expected.  Whereas years tagged with :Y1 do seem to
work.  This change updates the year tag to be :Y1 for articles refworks.

Override default date field refwork tag to be :Y1

---

app/views/primo_advanced/_advanced_search_facets.html.erb

BL-659
Appending "_inclusive" to the facet field name in PCI advanced search
makes search fail to apply the facet.  This change updates the name to
simply be `f[field_name]`.

Update advanced search facet field names.

---

app/controllers/catalog_controller.rb
lib/traject/indexer_config.rb
lib/traject/macros/custom.rb
spec/fixtures/marc_files/lost_missing_technical.xml
spec/lib/traject/traject_indexer_spec.rb

Records that have only a single item with a process type of missing, lost, or tecnical should not displayed in the search results.
- Creates a method in traject to identify records  
- Suppresses them in a filter query at the solr level

BL-641 Suppress missing, lost, and technical items

---

app/assets/stylesheets/tucob.scss.erb

Internet Explorer is always displaying a scroll bar, even when the content fits inside the container.  Try using overflow: auto to fix this.

BL-652 Try auto for availability scroll bars

---

app/controllers/concerns/multi_source_bookmarks.rb

REF BL-571
We've recently normalized the ids used to bookmark and search for
bookmarked articles.  However, that fix will not work for already
bookmarked items.  This change adds a backwards compatibility step to
normalize the already saved bookmark item ids at search time.

Add backwards compatibility step to bookmarks lookup.

---

lib/traject/indexer_config.rb

Call number mappings need to use the extract_marc_with_flank method in 
order for the begins with advanced search to work.

BL-610 Update call_number mappings

---

app/models/blacklight/primo_central/search_builder_behavior.rb
spec/models/primo_search_builder_spec.rb

REF BL-644
Adding a default range facet is causing major discrepancies between
libqa and librarysearch article searches.  This change removes adding
a premature range facet until a range search is actually done.

Remove the default range facet on article searches.

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

Subject links are not working on LibQA because they don't have the /catalog portion of the link.  Add root_path to allow it to work in all instances.

BL-649 Add root_path to subject links

---

app/javascript/packs/controllers/holds_controller.js
app/javascript/packs/controllers/loans_controller.js

Internet Explorer 11 does not support the javascript remove method, which causes a console error. 
-  Changes the remove methods to use jQuery, which is supported by ie 11

BL-650 Account page in internet explorer

---

lib/tasks/server.rake

apache.org is throwing network errors when we attempt to download solr
from them using solr_wrapper. We are adding a mirror_url to avoid using
the default mirror that uses  apache.org instead of princeton.edu.

Add mirror URL to avoid network error.

---

app/models/solr_document.rb

REF BL-639
The Alma bib api has a default limit of 10 and a maximum limit of 100
items returned per query. This update makes sure that we are querying
for the maximum allowed number.

Request the maximum allowed number of items from bib api.

---

app/models/solr_document.rb
spec/models/solr_document_spec.rb

Although barcodes are unique they are not always present.  This change
updates to code to internally use the pid (which is always present and
unique per item) instead of the barcode.

Replace using barcode with pid.

---

app/models/blacklight/primo_central/search_builder_behavior.rb
spec/models/primo_search_builder_spec.rb

REF BL-698
blacklight_range_limit will usurp the search_field value under certain
circumstances.  When we pass this value to primo, then the primo server
throws an error because that field is unknown. This change vets the
fields that are submitted and only allows those that have been
configured via blacklight_config.

Do not try pass unknown fields.

---

app/controllers/catalog_controller.rb

REF BL-697
Removes catalog number search until we can run a full re-index.

Temporarily disable catalog number search.

---

app/controllers/catalog_controller.rb
app/views/catalog/_show_default.html.erb

Removes the unless field is name check in template and adds an explicit display config to the field.

Move field display alternative to config.

---

app/helpers/catalog_helper.rb
app/views/catalog/librarian_view.html.erb
spec/helpers/catalog_helper_spec.rb

Moves the librarian_view logic from the template to a tested helper
function.

Move librarian view logic to a helper function.

---

app/controllers/almaws_controller.rb
app/helpers/alma_data_helper.rb
app/javascript/packs/controllers/fines_controller.js
app/javascript/packs/controllers/form_controller.js
app/lib/cob_alma/requests.rb
app/views/almaws/_hold_request_form.html.erb
spec/fixtures/requests/desc_with_multiple_libraries.json
spec/fixtures/requests/desc_with_no_libraries.json
spec/fixtures/requests/paley_reserves_and_remote_storage.json
spec/lib/cob_alma/requests.rb
spec/spec_helper.rb

Our former logic was only working at the bib level, so patrons could not request a specific volume that was not available at their library.  
- Refines the current valid pickup locations method to get rid of a bug that was 
including locations that shouldn't be there  
- Adds logic to filter pickup locations by description at the item level.

BL-667 pickup locations by item

---

app/helpers/tweak_query_helper.rb
app/models/search_builder.rb
app/views/advanced/_search_form.html.erb
app/views/catalog/_search_form.html.erb
app/views/catalog/_tweak_solr_query_form.html.erb
docker-compose.yml
spec/helpers/tweak_query_helper_spec.rb
spec/models/search_builder_spec.rb

REF BL-660
This is an experimental feature that toggles on by setting the
SOLR_SEARCH_TWEAK_ENABLE environment variable to "on". When enabled this
adds a link to the solr search forms named "Tweak Solr Query Fields".
When clicked, the link expands a set of links that each can be clicked
to reveal a textarea with the value for the field that will be passed to
solr.
Updates to any field value will affect the current search and all other
searches until a completely new search is started (i.e. start over is
clicked)
This is a relatively bare bones feature.  Enhancements may be added in
the future if it proves useful.
Depends on: tulibraries/tul_cob_playbook#23

Adds a way for admins to experiment with query tweaks.

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/tucob.scss.erb
app/helpers/catalog_helper.rb
app/models/citation.rb
app/models/concerns/citable.rb
app/models/primo_central_document.rb
app/models/solr_document.rb
app/views/bookmarks/_show_tools.html.erb
app/views/catalog/_citation.html.erb
app/views/catalog/_grouped_citations.html.erb
app/views/catalog/_show_tools.html.erb
app/views/catalog/_single_citation.html.erb
config/application.rb
config/locales/blacklight.en.yml
config/oclc.yml
lib/traject/indexer_config.rb
lib/traject/macros/custom.rb
spec/fixtures/marc_files/oclc.xml
spec/helpers/catalog_helper_spec.rb
spec/lib/traject/traject_indexer_spec.rb
spec/models/citation_spec.rb

- Citations are now coming from the worldcat API based on OCLC numbers
- Right now this work handles catalog items and bookmarks
- Bookmark citations can be filtered by title or citation format
- Requires a reindex for the marc fields that include OCLC numbers
- Do not merge until the apikey has been added to the Ansible playbook

BL-648 Use Worldcat API for citations

---

app/assets/stylesheets/partials/_header.scss
app/helpers/application_helper.rb
app/views/shared/_header_navbar.html.erb

REF BL-688
* Change header copy on all pages (id catalog_header, article_header,
etc.) to ‘Library Search’ and add an underline (like [Indiana’s
search|https://iucat.iu.edu/?utf8=%E2%9C%93&search_field=all_field&q=otters])
* Change ‘Library Search’ header link to go to
https://librarysearch.temple.edu/bento on all pages (the header link
will function as start over button)
* Remove all ‘Catalog Search’ and ‘Article Search’ buttons from all
pages

Update red-navbar header to new UI.

---

app/javascript/packs/controllers/form_controller.js

Adding an empty value stops the select from automatically selecting the first option when filtered

BL-667 Prepends empty value to item level pickup locations

---

app/search_engines/bento_search/blacklight_engine.rb
app/search_engines/bento_search/books_engine.rb
app/search_engines/bento_search/journals_engine.rb

Followup on BL-685 and BL-690
Now that we have a books and journals controllers we need to delegate
books and journal searches to them instead of to the catalog controller.
We also need to make sure that we use the new corresponding paths to the
controllers.

Fix bento search books + journal urls.

---

app/helpers/application_helper.rb
app/views/catalog/show.html.erb
spec/helpers/application_helper_spec.rb

Breadcrumb Labels should change depending on the user's current search context and should go back to their current search state

BL-691 Add breadcrumbs to record pages

---

app/controllers/books_advanced_controller.rb
app/controllers/books_controller.rb
app/controllers/journals_advanced_controller.rb
app/helpers/advanced_helper.rb
app/views/advanced/_advanced_search_form.html.erb
app/views/advanced/index.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/books_advanced_controller_spec.rb
spec/controllers/journals_advanced_controller_spec.rb
spec/helpers/advanced_search_helper_spec.rb
spec/helpers/primo_advanced_helper_spec.rb

REF BL-704
* Adds two new advanced forms (journals, books)
* Updates routes to allow form access via:
/catalog/advanced
/articles/advanced
/books/advanced
/journals/advanced
* Keeps backwards compatibility with old paths.

Add advanced books and journals forms.

---

app/assets/stylesheets/partials/_pagination.scss
app/assets/stylesheets/tucob.scss.erb
app/views/almaws/item.html.erb
app/views/kaminari/modal_compact/_paginator.html.erb

REF BL-634 (follow up)
* Remove pagination view when there are less than 100 items (i.e. keep
display as it currently is production)
* When there are more than 100 items: Move pagination view to the bottom
of the scroll view on record page (however, if possible, leave
pagination at top of page for the pop-up display)
* Add more padding to outer border of the pop-up display

Update availability pagination styling.

---

app/helpers/users_helper.rb
config/application.rb
spec/helpers/users_helper_spec.rb

Dates coming back from Alma's api are in UTC. We need to explicitly tell
rails to use a timezone or strftime will output UTC times.
This fixes human readnable dates on the account page for due dates and
Renewal due dates when a user renews an item.
Sets the Application timezone to "Eastern Time (US & Canada)".

Have make_date helper respect timezones

---

Gemfile.lock
app/controllers/almaws_controller.rb
app/helpers/almaws_helper.rb
app/views/almaws/_booking_allowed.html.erb
app/views/almaws/_digitization_allowed.html.erb
app/views/almaws/_hold_allowed.html.erb
app/views/almaws/_hold_request_form.html.erb
app/views/almaws/_resource_sharing_broker_allowed.html.erb
app/views/almaws/request_options.html.erb
spec/helpers/almaws_helper_spec.rb

Uses the alma request options api to retreive the link to EZ-borrow.  
- The link should only appear on items that are books currently unavailable at Temple Libraries.

BL-545 EZ-borrow integration

---

Gemfile
Gemfile.lock

REF BL-337
Followup on BL-337; We were overriding blacklight to fix a Safari bug
(BL-337) but our changes were recently merged into the upstream for version
16.6.0. We can now resume using the regular blacklight instead of our
fork.

Update blacklight to 6.16

---

app/helpers/application_helper.rb
app/search_engines/bento_search/blacklight_engine.rb
app/search_engines/bento_search/books_engine.rb
app/search_engines/bento_search/journals_engine.rb
app/search_engines/bento_search/primo_engine.rb
config/routes.rb
spec/helpers/application_helper_spec.rb

REF BL-713
“Everything” tab should be default highlighted in red on https://libqa.library.temple.edu/catalog/everything and https://libqa.library.temple.edu/catalog/ (where ever the user is starting a search in 'Everything')
“Everything” tab does not stay highlighted when you click on it, UNLESS you first click on another toggle then click back to “Everything”
Once you’re in Advanced Search, the section you’re in (Books, Articles, etc) still needs to be highlighted in the toggle.
* Uses the current_search session to propagate search so that going to
a record does not destroy nav menu.
* Updates the bento links to books and journals so that they match the new
routes and following them activates the correct menu item.
* Updates the code that checks if a path is active so that it works on …

[BL-685:713] Fix nav menu not active.

---

app/helpers/render_constraints_helper.rb
app/helpers/render_constraints_helper_behavior_override.rb
app/models/blacklight/primo_central/search_builder_behavior.rb
app/models/blacklight/primo_central/solr_adaptor.rb
app/models/search_builder.rb
spec/helpers/render_constraints_helper_spec.rb
spec/models/primo_search_builder_spec.rb
spec/models/search_builder_spec.rb

REF BL-712
REF projectblacklight/blacklight#1989
After some QA testing, Jackie and I were talking further about the persistence of filters between Articles and the Solr menu options, and realized that there were some issues with this. For instance, even when there is a field match (author, topic, resource type), each index uses different vocabularies such that the values frequently don't match, leading to no results. We also felt that it might be confusing if some filters persisted (ex. date) while others didn't. So as a result, we'd like to scale this back and have just the basic query persist between Articles and the other options. Even in cases where the user has switched the basic query for "All Fields" to something else (ex. Title), it will revert back to All Fields. The relationship …

[BL-685/BL-712] Do not share facets across searches.

---

app/controllers/books_controller.rb
app/controllers/journals_controller.rb

REF BL-685, REF BL-712
By removing the facet filter from books and journals we are able to
share the other facet field URL search configurations across all the
catalog type.  Thus we would be able to filter in the More search by
facet format and not affect the books or journal search view.

[BL-685/BL-712] Remove format facet for books and journals.

---

app/views/catalog/_facets.html.erb

REF BL-717
Now that the constraint fields are getting added inside of the facets side bar, whenever there is an empty search the constraints do not get rendered because the facets only get rendered when there are results.  We need to start rendering not just when facets are available but also when search params are present, that way on empty searches the user still has the ability to unselect a facet or search term that caused the search to return an empty results set.
* Add or predicate to check if search parameters are present before
rendering.

[BL-685/BL-717] Relax facets rendering.

---

app/lib/cob_alma/requests.rb
spec/fixtures/marc_fixture.xml
spec/fixtures/requests/empty_and_description.json
spec/fixtures/requests/empty_descriptions.json
spec/fixtures/requests/multiple_descriptions.json
spec/lib/cob_alma/requests.rb
spec/spec_helper.rb

Previous code was excluding a single empty element, but some items have multiple empty descriptions.  Changes code to remove all empty elements and adds tests for the method.

BL-718 Book requests with empty descriptions

---

lib/traject/macros/custom.rb

When I tried to import some files directly into the libqa solr, having
this requirement made the import fail.  This dependency should only be
added locally if and when required.

Remove pry dep from traject indexer.

---

app/controllers/catalog_controller.rb

REF BL-524
Further de-emphasizes PRESSER results by boosting other libraries score.

[BL-524] Increase the default library based boosting to 1000.

---

solr/conf/synonyms.txt

REF BL-695
Removing the synonym because of stemming we cannot make a distinction
between maj. and maj and since Maj is a word we would lose those
results.

[BL-695] removes maj = major solr synonym.

---

app/helpers/almaws_helper.rb
app/views/almaws/_no_request_options.html.erb
app/views/almaws/_resource_sharing_broker_allowed.html.erb
app/views/almaws/request_options.html.erb

so that "no Temple libraries" message does not appear for ez-borrow items

BL-545 Refactor logic 

---

app/assets/stylesheets/tucob.scss.erb
app/views/catalog/_online_availability.html.erb

Availability tables are missing borders when there is no scroll bar present.  This adjusts the css to fix problems with the availability display.

BL-710 Availability display update

---

app/controllers/almaws_controller.rb
app/views/almaws/item.html.erb

Currently, if an item is suppressed it is still displaying the library name with an empty table.  This filters it to show the default text when all items are suppressed.

BL-359 Refactor availability display

---

app/controllers/primo_central_controller.rb
app/helpers/advanced_helper.rb
app/models/blacklight/primo_central/solr_adaptor.rb

REF BL-689
Fixes error when switching between Primo advanced and catalog search do
to an unknown field.

Fix error do to unknown field.

---

app/controllers/catalog_controller.rb

REF BL-661
Boost `title_uniform_unstem_search^15000` and `title_uniform_t^5000` for
qf.
For pf, try `title_uniform_unstem_search^150000` and
`title_uniform_t^50000`.

Boost catalog title search fields.

---

app/controllers/almaws_controller.rb
app/helpers/alma_data_helper.rb
spec/fixtures/marc_fixture.xml
spec/helpers/alma_data_helper_spec.rb

Currently items that are suppressedby location in Alma are still displaying in the availability panel. This method filters them out so that they are not displayed.

BL-359 Suppress techserv, UNASSIGNED, and intref locations

---

app/helpers/application_helper.rb
spec/fixtures/marc_fixture.xml
spec/helpers/application_helper_spec.rb

Occassionally a 650 field has multiple "z" subfields.  In these cases, double hyphens are displaying in the record page link.  Refines method to display only a single hyphen.

BL-721 Eliminate extra punctuation

---

app/controllers/almaws_controller.rb
app/helpers/alma_data_helper.rb
app/views/catalog/_index_availability_section.html.erb
app/views/catalog/_show_availability_section.html.erb

The mms_id and the doc_id are not interchangeable for bound-with items.
Thus, when fetching a bound-with item using mms_id, solr will return nil
causing havoc.  This commit fixes the issue by passing doc_id along to
the controller as well as rescuing from error with a dummy Solr document
if all else fails.

[BL-359] Fix bound-with doc throws on fetch.

---

app/helpers/almaws_helper.rb
app/views/almaws/_booking_allowed.html.erb
app/views/almaws/_digitization_allowed.html.erb
app/views/almaws/_hold_allowed.html.erb
spec/helpers/almaws_helper_spec.rb

* BL-699 Request modal should default to being open when only hold requests are allowed
* Refactor method to default to open when there is only one request option available
* Refactored method and added another test

BL-699 Request modal should default to being open  (#785)

---

spec/relevance/query_results_spec.rb
spec/spec_helper.rb

I inadvertently re-created some already implemented rspec matchers.
This commit updates the tests to use these current matchers and removes
the redundant matchers.

Use implemented rspec search util matchers.

---

Rakefile

docker:up rake task does not have access to Rails because rails is not
running at the point it's invoked.

[devops] Fix rake docker:up fails

---

app/helpers/application_helper.rb
app/helpers/catalog_helper.rb

When tests is run just for catalog_helper_spec.rb some tests fail do to
deps.  This moves he deps back into catal_helper.rb from
application_helper.rb

Fix catalog_helper test fail locally.

---

app/assets/stylesheets/partials/_header.scss
app/views/catalog/_search_form.html.erb

- Advanced link was going behind the search input group when screen size was smaller.  This updates the css styles to get rid of that issue.

BL-688 UX header changes

---

app/assets/javascripts/listeners.js
app/controllers/books_advanced_controller.rb
app/controllers/books_controller.rb
app/controllers/journals_advanced_controller.rb
app/controllers/journals_controller.rb
app/controllers/primo_advanced_controller.rb
app/controllers/primo_central_controller.rb
app/helpers/application_helper.rb
app/views/application/_navbar.html.erb
app/views/catalog/_show_availability_section.html.erb
app/views/catalog/_show_tools.html.erb

Update GA actions (created in https://tulibdev.atlassian.net/browse/BL-551) for navigational updates from Fall 2018.
Add tracking for the following actions:
Action on menu items
Books/Articles/Journals/More headers
Books/Articles/Journals/More menu items
Actions on search results pages (ex. Clicking on links, buttons, etc.)
Make sure that Catalog Search actions still work for Books/Journals/More searches: Advanced Search links, Availability/Online buttons (don’t know if this is possible, since it can be a dropdown), Bookmark checkbox
Actions on record pages (ex. Clicking on links, buttons, etc.)
Breadcrumb links
Make sure that Catalog Search actions still work for Books/Journals/More searches: Back to Search button, Start Over button, Bookmark button, “Send To” dropdown/links, “Log in to …

BL-737 Update Google analytics actions for navigational updates

---

app/assets/javascripts/listeners.js

JS arrays require commas between items.

[BL-737] Fix JS pre-compile error.

---

spec/relevance/include_items_spec.rb
spec/relevance/keyword_spec.rb
spec/relevance/query_results_spec.rb
spec/relevance/tul_specific_spec.rb
spec/spec_helper.rb

Refactoring include_items because
* Tests are passing even when a secondary item is not present
(i.e. .before(secondary_items)).
* Benchmarking shows that the declarative approach is not inefficient
even in the most drastic possibility of 100,000 calculations.
```
items = (1..100).to_a
Benchmark.bm do |x|
x.report("benchmark 100 x 100 index checks") {
items.all? { |front_item|
items.all? { |back_item|
items.index(front_item) + items.index(back_item)
}
}
}
end
```
```
user     system      total        real
benchmark 100 x 100 index checks  0.010000   0.000000   0.010000
(  0.005298)
```

[DevOps] Refactors the include_items rspec matcher.

---

.travis.yml

Some production compilation can fail even if test compilation passes.
In order to check against a production compilation failure, we need to
also compile assuming a production environment.

[DevOps] Run production level compilation on travis.

---

app/controllers/catalog_controller.rb
app/helpers/catalog_helper.rb
lib/traject/indexer_config.rb
lib/traject/macros/custom.rb
spec/features/record_page_fields_spec.rb
spec/fixtures/features.yml
spec/fixtures/marc_files/genre_display.xml
spec/fixtures/requests/item_limits.xml
spec/lib/traject/traject_indexer_spec.rb

Genre fields were previously included in the subject_display field on individual record pages.  
- separates genre from subject and gives them their own display field
- new helper method and facet_field created to generate exact links for genres from a record page (display mappings are different than the current genre_facet mappings and need to remain different)
- removes genre fields from subject_facets so that they are not included in advanced subject searches
- Adds a new dropdown option for genre advanced search

BL-596 Create new genre_display field

---

lib/traject/indexer_config.rb
lib/traject/macros/custom.rb
spec/fixtures/marc_files/title_statement_examples.xml
spec/fixtures/marc_fixture.xml
spec/lib/traject/traject_indexer_spec.rb

Records that include a subfield h should have a / separator before subfield c.

BL-720 Update mappings for title_statement_display

---

README.md
lib/traject/indexer_config.rb

Now that we have configured solr to check the update date before
ingesting a file, it has been necessary locally to dump our solr
document before doing a re-ingest.  This step can become cumbersome if
we need to ingest the same file many times over during a development
session.
This commit adds a way to override this feature by setting the update
date to the current Time, thus guarantying that the update date is
always newer and effectively disable the Solr feature.

[DevOps] Allow multiple ingest of the same file.

---

Gemfile.lock
app/lib/cob_alma/requests.rb
spec/spec_helper.rb

Currently we are limited to only 100 item descriptions, so if a patron wants to request something from a larger set of records, they may not be able to choose the item they want.  This now returns all items in the request dropdown menus.

BL-747 Remove item limits from request descriptions

---

app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
app/assets/stylesheets/partials/_bento.scss
app/assets/stylesheets/tucob.scss.erb
app/views/almaws/_booking_request_form.html.erb
app/views/almaws/_digitization_request_form.html.erb
app/views/almaws/_hold_request_form.html.erb
app/views/almaws/item.html.erb
app/views/bento_search/_item_title.html.erb
app/views/catalog/_index_default.html.erb
spec/features/bento_search_spec.rb

- Change bento headings structure
- add alt tag to default image icons
- change label color on search results page
- change 2nd and 3rd table headers to td
- update form labels on request forms to associate by id to avoid duplicate labels being present between forms
REF BL-749
REF: https://github.com/jrochkind/bento_search/pull/38

BL-749 Accessibility issues

---

app/helpers/alma_data_helper.rb
spec/helpers/alma_data_helper_spec.rb

A bug in the alma api was preventing us from being able to use the requested boolean key in item_data.  The December release fixed the issue, so we can now display requested items as unavailable.

BL-357 Show requested status for availability

---

app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

REF BL-769
Refactors electronic_resource_link_builder so that it only adds dashes
after additional notes not if only an electronic note is present.

[BL-347:769] Remove dash for electronic resource.

---

Gemfile.lock

There have been bug fixes to concurrent-ruby since we installed it and
I believe some of these bug fixes may help with locking issues in bento.

[DevOps] Update concurrent-ruby to latest.

---

app/controllers/catalog_controller.rb
app/models/purchase_order_mailer.rb
app/views/purchase_order_mailer/purchase_order.text.erb

REF BL-767
* Update email subject header  from "Purchase Order:" to "Purchase on Demand:"
* Include the patron's name in the email
* Would it be possible to send a copy of the email be sent to the requester and/or a confirmation screen pop-up saying the request submission was successful?

[BL-340:767] Update purchase order email.

---

bin/alma_electronic_db.rb
lib/alma/electronic/batch_utils.rb

The script to get electronic notes is throwing some exceptions do to
name error and type error.
This commit fixes those bugs.

[BL-347] Fix exception thrown.

---

doc/architecture-decisions/0002-use-separate-solr-cores-for-separate-az-database-document-type.md

REF BL-757
We want to document the architectural decision to use a separate Solr core to house the new az database documents so that we do not forget our reasoning:
Mainly that it will be easier to maintain separate cores and avoid undue processing when only one document type needs processing.

[BL-726:757] Document az-db architectural decision.

---

app/lib/cob_alma/requests.rb
spec/fixtures/requests/empty_hash.json
spec/lib/cob_alma/requests.rb
spec/spec_helper.rb

When more than 100 items were present, the pickup locations dropdown was still limited to the first 100.

BL-747 Add all descriptions to pickup_locations dropdown

---

bin/alma_electronic_db.rb
lib/alma/electronic/batch_utils.rb
spec/lib/alma/electronic/batch_utils_spec.rb

The script for downloading electronic notes is failing to download
service notes properly do to some bugs.  This commit fixes the error and
adds some new tests to help prevent problems in the future.

[BL-346] Fix electronic notes script.

---

app/controllers/catalog_controller.rb
app/helpers/catalog_helper.rb
app/views/catalog/_availability_panel.html.erb
app/views/catalog/_index_availability_section.html.erb
app/views/catalog/_purchase_order_anonymous_button.html.erb
spec/helpers/catalog_helper_spec.rb

On search results page:
* When *not* logged in: Add “Request Rapid Access” button with “>”; when clicking on button, add drop-down with following link “Log in to access request form” in right of button and the following text below the button: “This online material is available for purchase on demand. The option to request rapid access is limited to Temple University students, faculty, and staff. Once requested, access will generally be enabled within 2 business days.”; use box styling used for electronic resources in drop-down
* When logged in: Leave functionality as is.
On full record page:
* When *not* logged in: Add link “Log in to access request form” (same placement as “Log in to see request options” for other record types; Add header “Request Rapid Access” and text “This online …

[BL-340:766] Update purchase order buttons.

---

README.md
lib/tasks/docker.rb

Adds a `rake docker:open` and `rake docker:open_solr` that opens up the
app or solr in the browser.  Makes it easier to develop with docker
because you don't have to search the IP address to open up the app in
a browser locally.

[DevOps] Add a rake task to open up docker app in browser.

---

app/models/blacklight/primo_central/response.rb
spec/models/primo_central_response_spec.rb

The top line of the actual bars seems to be extending too far to  the right in the date range facet for articles.

[BL-719] Fix articles date range graph broken.

---

app/controllers/catalog_controller.rb

REF BL-777
REF
https://app.honeybadger.io/projects/56250/faults/41903589#notice-summary
Define error_info for xml and json document not found error page.

Fix xml json error page throws exception.

---

app/controllers/search_controller.rb

REF: BL-778
Currently all our other search views have a json format except for the
search by everything view. This commit adds the missing format.

[BL-778] Add json format to search everything view.

---

app/controllers/almaws_controller.rb

- Currently when partial digitization requests are made, the citation information(item-level description) is not being passed through to Alma.  This adds the descprition to the comments so that the people filling the request can easily see which item is needed.

BL-705 Add item descriptions to comments

---

app/controllers/application_controller.rb
spec/controllers/bookmarks_controller_spec.rb
spec/controllers/catalog_controller_spec.rb
spec/spec_helper.rb

- Currently our deprecations are piling up in our test suite.  This PR handles all of the deprecations that are not related to the Blacklight 7 upgrade
- skip_after_action :discard_flash_if_xhr
- allow_message_expectations_on_nil
- change be_success predicates to be_successful

BL-678 Begin handling test suite deprecations

---

lib/traject/macros/custom.rb
spec/lib/traject/traject_indexer_spec.rb

REF BL-746
Allow PO items to still be visible in the facets even after online items
are selected.

[BL-340:746] Make po items also online items.

---

app/helpers/catalog_helper.rb
app/views/catalog/_document.html.erb
app/views/catalog/_index_availability_section.html.erb

REF BL-780
When forced to log in in order to make a request the redirect link is not
document specific.  Therefore, when you are logged back in you get
redirected with focus on top of page.  This forces user to scroll back
down if they redirected from a lower section of the window.
This update adds target specific redirect links so that the browser scrolls
to the correct part of the window on log in.

[BL-780] Redirect back to specific document on log in.

---

app/helpers/alma_data_helper.rb

REF BL-786
Honeybadger Ref: https://app.honeybadger.io/projects/56250/faults/44436938#notice-summary
When we do not have a location mapped in `Rails.configuration.libraries`
then the `location_name_from_short_code` method returns `nil` and in
turn causes an error to be raised by the `sort_order_for_holdings`
helper method.
* This PR fixes the issue by defaulting to the key when no map is
present for a specific location.
* This PR also aliases `location_status` to
`location_name_from_short_code` for backwards compatibility because they
are in fact the same method.

Use key as default location description.

---

app/helpers/almaws_helper.rb

- We were accidentally limiting the text for no request options to items that were not books.  This removes that logic so that the default text displays for all item types.

BL-784 Request options display

---

solr/conf/schema.xml

- The way our current solr schema is set up, stop words are case sensitive, so when a user searches with 'The' no results are found.  
- Adds caseInsensitive='true' to StopFilterFactory
- Move LowerCaseFilterFactory after StopFilterFactory

BL-776 Capitalization bug in dropdown title search

---

app/helpers/alma_data_helper.rb
spec/helpers/alma_data_helper_spec.rb

- It can be confusing to users to see reserve items listed as available since they can only be checked out for a few hours and must remain in the library.  
- Updates the item status to display library use only

BL-781 Reserve item status

---

app/views/advanced/_advanced_search_submit_btns.html.erb

- Remove equal sign for the sort_fields variable so that it isn't displayed in the template

BL-795 Advanced search sort options displaying

---

app/assets/javascripts/application.js
app/assets/stylesheets/partials/_header.scss
app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

- There is a significant delay in the transition between searches, resulting in the active class being present on both links.  This is especially a problem on mobile devices.
- Use javascript to remove and reassign "active" class faster
- We were assigning the active class to both the list item and the link itself. Now the active class is only assigned to the list item.

BL-790 Navigation tabs when active

---

app/helpers/advanced_helper.rb
app/models/blacklight/primo_central/search_builder_behavior.rb

* Updates constraints element rendering code to short circuit the
advanced elements constraints when not doing an advanced search.
* Adds check to primo search builder to verify if regular advanced
search has been created (i.e. also do advanced search in primo)

[BL-666] Do not add always add advanced constraints.

---

app/helpers/blacklight_marc_helper.rb
app/models/solr_book_document.rb
app/models/solr_journal_document.rb

- xml views and refworks are not currently available for books and journals. 
- Adds the refworks_marc_txt to each model 
- Adds helper methods for the refworks links

BL-789 xml views for books and journals

---

app/models/blacklight/primo_central/document.rb
app/models/concerns/diggable.rb
app/models/primo_central_document.rb
app/models/solr_document.rb

Articles were breaking because BL7 does not allow []= for document obj.

Makes articles document diggable.

---

Gemfile.lock
app/controllers/almaws_controller.rb
app/controllers/concerns/json_logger.rb
app/controllers/users_controller.rb
app/models/blacklight/primo_central/repository.rb
app/models/solr_document.rb
app/models/user.rb
config/initializers/alma.rb
config/initializers/primo.rb
spec/controllers/catalog_controller_spec.rb
spec/helpers/almaws_helper_spec.rb
spec/models/almaws_response_spec.rb
spec/spec_helper.rb

REF BL-779
When we make API calls we log the response process in order to obtain
metrics on these API requests.  However when the request raises an
exception we fail to log the event.  We need to make sure that logging
happens even in the event of a raised exception.
This change updates the `json_request_logger` method to accept a block.
When a block is passed it gets yielded before logging happens and if an
exception is raised it is caught, logged and then released so that we do
not interrupt the proper behavior of the app just for logging.

[BL-779] Log API requests even on failure.

---

Gemfile
Gemfile.lock
app/assets/stylesheets/icons.css.erb
app/controllers/search_controller.rb
app/helpers/search_helper.rb
app/models/search/solr/response.rb
app/search_engines/bento_search/blacklight_engine.rb
app/search_engines/bento_search/cdm_engine.rb
config/initializers/bento_search.rb
config/initializers/cdm.rb
config/locales/en.yml
spec/controllers/search_controller_spec.rb
spec/models/search/solr/response_spec.rb
spec/search_engines/cdm_seach_spec.rb

REF BL-348
* In the "Resource Type" column of the bento box, add Resource type
value for "Digital Collections"
* This value should include the number of results that there are for
that query in ContentDM, accessed via ContentDM API
* The facet link itself should open the search results for ContentDM,
with the basic query from the Library Search.

[BL-348] Implement Content DM API integration.

---

app/search_engines/bento_search/blacklight_engine.rb
app/search_engines/bento_search/cdm_engine.rb

Fixes no method `blacklight_config` for BentoSearch::SearchController on
libqa.

[BL-438] Fix blacklight_config method error.

---

app/controllers/search_controller.rb
app/models/search/solr/response.rb
spec/models/search/solr/response_spec.rb

If we do not sort a merged facet item then the item will just appear at
the end of the list.  By providing a default sorting order with the
possibility to overriding we can merge new facets without braking the
expected behavior.

[BL-438] Sort facet items on merges.

---

app/assets/stylesheets/icons.css.erb
app/controllers/search_controller.rb
app/helpers/search_helper.rb
config/locales/en.yml
spec/controllers/search_controller_spec.rb

Sort is using cdm instead of digital_collection so "Digital Collection"
appears before "C" in the sorted list.

[BL-438] Update digital collection label for ordering.

---

app/models/search_builder.rb

REF BL-800
1. Start with an articles advanced search
2. Once you get some results, click on “More” to switch view.
3. “More” results page errors out.
This also happens when switching to Books or Journals. The reverse behavior (Books/Journals/Catalog advanced search to Articles) works as expected.
Patched with BL-7 `def sort` which does not attempt to pass unknown
sorting fields to solr.

[BL-800] Fix solr search breaks on unknown sort field.

---

app/helpers/advanced_helper.rb
app/views/advanced/_advanced_search_submit_btns.html.erb
app/views/primo_advanced/_advanced_search_submit_btns.html.erb

* Add missing helper method `sort_fields`
* Replace views level definitions with helper method.

Fix primo advanced articles search breaks.

---

app/assets/javascripts/listeners.js
app/views/layouts/blacklight.html.erb

The google-analytics-rails gem does not have the forceSSL option.

Add privacy features to event tracking and pageviews.

---

app/controllers/databases_controller.rb
app/helpers/catalog_helper.rb
lib/traject/databases_az_indexer_config.rb
spec/helpers/catalog_helper_spec.rb

* AZ Vendor ID display field: We need to either remove the AZ Vendor ID from display or replace it with the text value. The latter would require retrieving data for a translation map from vendor ID’s to vendor names – can this be done systematically, or would it need to be maintained manually?
* Note display field: change label from “Note” to “Description” for all displays
* For brief results display: remove ID fields, add resource type field/icon (see indexing section for details)
* For full record page display : add subject_display, with links back to search, and resource type field/icon; update label “AZ ID” to “Database Record ID” and move to bottom

[BL-810] Update AZ database display.

---

app/helpers/facets_helper.rb

Resource type "Digital Collections" should open up a new tab.

[BL-438] Open up a new tab when linking to cdm link.

---

app/controllers/databases_controller.rb

* Add secondary value for “Resource Type” field – by default, all records will have a value of “Database”; but there should also be secondary resource type values mapped from the AZ field for “type” (ex. image). We will need to change translation map from raw AZ values to standard resource type values in the Library Search.
* Add “Resource Type” facet, but exclude main “Database” value from display and show only secondary resource type values (see indexing section for details)

[BL-10:BL-808] Add resource type facet to databases.

---

app/helpers/catalog_helper.rb

REF BL-814
When items are bookmarked from the book or journal index pages they
do not appear as being bookmarked when viewing the bookmarked items.
This happens because of a conflict between the document.class and
bookmark.class.  For now we can fix this by just not checking against
that field as all our Solr document ids are uniq by default.

[BL-814] Fix issue with book bookmark items.

---

app/controllers/catalog_controller.rb
app/helpers/catalog_helper.rb
app/models/search_builder.rb
app/views/catalog/_did_you_mean.html.erb
spec/models/search_builder_spec.rb

REF BL-316
* Makes suggestions on entire phrase (not just per word)
* Max suggestions is 3 (default is 1)
* Disables suggestions for advanced search (does not work)

Enable suggestions for solr searches.

---

app/helpers/catalog_helper.rb
app/models/solr_book_document.rb
app/models/solr_journal_document.rb
lib/tasks/temporary/bookmarks.rake

REF BL-814
REF BL-822
Having books and journal documents be represented by different models
SolrBookDocument and SolrJournalDocument that derive from the
SolrDocument is causing both the bookmark and email functionality for
these documents to fail when actions occur from the bookmark or journal
index pages.
This is partly do to a misconfiguration.  Although we need these models
in order to have correct paths .. they should be equal to SolrDocument
not derive from.
Updating them to equal SolrDocument fixes both the issues with
bookmarking and the issue with sending emails.
* Also adds temporary rake task to fix old data in the bookmarks table.

[BL-814] Fix bookmark not working from book or journal.

---

app/controllers/books_controller.rb
app/controllers/journals_controller.rb

Blacklight has a way to override the default routing behavior for
indexed document via configurations. @see
Blacklight::SearchState.url_for_document. This commit updates the
configurations for books_controller and journals_controller to point
index urls to the right place.

[BL-814] Override the default catalog URL.

---

app/helpers/application_helper.rb
app/views/catalog/_show_availability_section.html.erb

A change in the way BL-7 adds fields to show page is causing a nil error
to now break databases show pages.
This commit adds a helper method to guard against nil values in this
context and fixes the issue with the databases show page.

[BL-399] Fix database show page broken after BL-7 upgrade.

---

app/controllers/databases_controller.rb
app/helpers/advanced_helper.rb
app/views/advanced/_advanced_search_facets.html.erb
app/views/advanced/_pub_date_sort_facet.html.erb
lib/traject/databases_az_indexer_config.rb
spec/helpers/advanced_search_helper_spec.rb

Makes the following changes:
* Adds an “All Fields” search option as default for basic search and add database description, subject, and id fields to search index, if not already present (basically all fields should be searchable, like the MARCXML record in the catalog)
* Fixes “Subject” drop-down option for basic search
* Fix advanced search goes to wrong path on submit
* Remove pub_date_sort facet search from databases advanced search form
* Add an alphabetical title sort
* Add AZ alternate title field to search index.

[Bl-809] Databases AZ updates.

---

app/views/search/_blacklight_availability.html.erb

When searching for "Development and validation of the children’s
constructive conflict resolution scale" on libqa or production an error
is thrown due to not method found.
We are fixing this by removing the call to this method from a shared
template.  The call is not required since nothing happens even if it is
evaluated.

[BL-833] Fix everything search fails for some queries.

---

app/helpers/advanced_helper.rb

Fixes error being caught in production where the method
is_advanced_search? is not present.  I cannot reproduce this locally but
regardless this method should assume that when that method is not
available then the search is not advanced.

[BL-836] Default to false when is_advanced_search? not available.

---

app/controllers/search_controller.rb
app/views/catalog/_search_form.html.erb
spec/features/bento_search_spec.rb

- The search fields select menu was accidentially introduced to the bento view.  It doesn't work properly, so it should be hidden for bento searches

BL-835 Remove dropdown from bento view

---

app/controllers/almaws_controller.rb
app/controllers/catalog_controller.rb
app/helpers/alma_data_helper.rb
app/views/almaws/item.html.erb
lib/traject/indexer_config.rb
lib/traject/macros/custom.rb
spec/fixtures/alma_data/merge_document_and_api.json
spec/helpers/alma_data_helper_spec.rb
spec/spec_helper.rb

This changes the logic to depend more on document fields and less on the alma api
- Creates a new items_json_display field to get all document information except for real-time avail.
- Refactors all the alma_data_helper methods to use the new field rather than the api
- Creates a new method to merge the real-time availability for each item with the information from the items_json_display field
- group_by library and reject missing_and_lost items methods performed on this new merged_data
- sort-by-holdings refactored to use merged_data
- adds/updates specs as needed
- keeping alma bib_items and methods in controller since we are still using them for requests

Bl 815 physical item data

---

app/views/bookmarks/_show_tools.html.erb

- Refworks export is not working properly for bookmarked items.  Remove until we get it fixed.

BL-694 Remove link to refworks

---

app/helpers/blacklight_marc_helper.rb

REF BL-838
Now that books and journals document models alias the solr document only
the `refworks_solr_document_path()` gets called.  This commit updates
this method to also return for books and journal controller.

[BL-838] Fix refworks paths for books and journals

---

lib/traject/macros/custom.rb
spec/lib/traject/traject_indexer_spec.rb

REF BL-641
REF BL-850
* Reverts skipping suppressed docs because docs are sometimes already in solr repo.
* Allows to skip suppressed docs by signaling that a full reindex is in progess.

[BL-641] do not skip suppressed on non full reingest

---

app/helpers/availability_helper.rb
config/libraries.yml

There is an error on production that happens when availability item is on DSC:
https://librarysearch.temple.edu/catalog/991036860491803811
There are a couple of tasks that need to be done.
* Set a configuration for DSC
* Set a default if config is not available for DSC
* Notify Honeybadger when config not set (so that we can update configs)

[BL-847] Add config entry for DSC.

---

app/controllers/errors_controller.rb

REF BL-853
almaws controller items are all for ajax so errors should not render the
full layout.

[BL-853] Do not render layout for almaws errors.

---

app/models/blacklight/primo_central/search_builder_behavior.rb
spec/models/primo_search_builder_spec.rb

When searching an unknown field it should revert to primo field any not
just pass the field along.

[BL-855] Default unknown fields to any.

---

app/controllers/concerns/multi_source_bookmarks.rb
app/views/bookmarks/_show_tools.html.erb
app/views/bookmarks/index.html.erb

REF BL-837
blacklight-7 changes the way that response.documents works causing
failure when we try to override what response.documents returns.
This commit overrides the @documents instance variable of response so
that reponse.documents works as expected (i.e. uses our merged documents
not just documents coming from one searcher).

[BL-837] Fix bookmarks not showing up.

---

app/assets/stylesheets/partials/_header.scss
app/controllers/almaws_controller.rb
app/helpers/availability_helper.rb
app/views/almaws/item.html.erb
config/application.rb
config/material_types.yml
spec/helpers/availability_helper_spec.rb
spec/spec_helper.rb

- update material type to be description, not value
- add pagination links to the top of the modal
- Get all availability info, was only getting the first 100 previously
- fix failing specs and rubocop offenses

Bl 815 physical item availability

---

app/controllers/catalog_controller.rb
app/helpers/catalog_helper.rb
app/views/catalog/_fields.html.erb
spec/helpers/catalog_helper_spec.rb

Updates bound_with_ids render to be a configuration at the controller
level to avoid field getting rendered when it has not been configured.

[BL-837] Fix bookmarked article render breaks.

---

Gemfile.lock
app/models/blacklight/primo_central/search_builder_behavior.rb

The Primo::PNXS API has been deprecated. This updates the primo gem we
use to the version that uses Primo::Search api instead.

[BL-876] Update primo gem.

---

app/search_engines/catalog_bookmark_search.rb

This is causing a 500 error when viewing bookmarks.
REF BL-837

Remove reference to SolrBookDocument.

---

lib/traject/indexer_config.rb
lib/traject/macros/custom.rb
spec/lib/traject/traject_indexer_spec.rb

REF BL-875
REF #1113 
The `extract_update_date` method finds the latest date by looking at all
dates in ADM, ITM, HLD and PRT record fields.

[BL-875] Add extract_update_date method to traject config.

---

app/helpers/request_helper.rb
app/views/almaws/_resource_sharing_broker_allowed.html.erb
spec/helpers/almaws_helper_spec.rb
spec/helpers/request_helper_spec.rb

- Currently the ez borrow link is too strict and is not giving patrons the matches for the titles they would like to request
- Strips out unwanted query params in the url
- Adds specs for new method
- Updates old specs to have valid urls
- URI.encode_www_form had to be added in for authentication to work

BL-761 EZ Borrow Link

---

app/controllers/primo_central_controller.rb
app/helpers/catalog_helper.rb
app/helpers/primo_central_helper.rb
app/models/blacklight/primo_central/document.rb
spec/models/primo_central_document_spec.rb

* Adds back fields lost when upgrading to new primo pnx API.
* Adds some extra unit tests for the mappings.

[BL-876] Add back article fields lost in api upgrade.

---

config/routes.rb
spec/routing/books_redirect_spec.rb

Related to changes made in
https://tulibdev.atlassian.net/browse/BL-861.
With the removal of the "Books" nav option, we need to redirect URLs
from /books
* For individual record pages, redirect from /books/ID to /catalog/ID
* For search results, redirect from /books to /catalog, with resource
type facet for books added

[BL-885] Redirect books urls for record pages and search results.

---

README.md
bin/ingest.rb

This is a ruby executable that works on both files and URLs. So now if
you want to quickly ingest a marc xml record from production into local
you can run something like:
```bash
bin/ingest.rb http://example.com/catalog/foo.xml
```

Allow dev to ingest marc xml urls to local.

---

app/helpers/availability_helper.rb

In order to test that requests are working properly on Libqa, we need to unsuppress this location

Unsuppress asrs_test location 

---

lib/traject/databases_az_indexer_config.rb
spec/features/databases_spec.rb

We recently removed automatically adding title_truncated_display to the
solrdocument instance.  Because databases inherits from the catalog
controller and also uses the solr document model, it was automatically
configured to use title_statement_display as the title field for
results.
There are two ways to fix this issue.
* Add a databases specific title field (like title_display)
* Or, make sure we add "title_truncated_display" to databases.
I when with the latter option because there is another related issue
that requires we truncate the database titles in the results page.

[BL-809] Fix database title missing from results.

---

app/controllers/catalog_controller.rb

Blacklight/Solr spelling suggestions have too many issues to be useful.

[BL-316] Disable spelling suggestions.

---

Gemfile.lock
config/initializers/alma.rb
config/initializers/primo.rb

* Updates alma to use new version that limits  offset to < 500.
* Updates timeout to 10 seconds for primo and alma api (because we
noticed that locally we were timing out when it was set to default of
5 seconds).

[Bl-877] Update alma and timeout.

---

app/helpers/application_helper.rb
app/helpers/catalog_helper.rb
spec/features/indices_spec.rb

A change in the way BL-7 adds fields to show page is causing a nil error
to now break databases show pages.
This commit adds a helper method to guard against nil values in this
context and fixes the issue with the databases show page.

[BL-399] Fix database show page broken after BL-7 upgrade. (#1047)

---

config/routes.rb

The books redirect is only required once we deploy new navbar changes
where Everything link becomes "Books & Media".

Remove books redirect.

---

config/initializers/alma.rb

user_loans api is timing out when timeout is set to 0.
This is a temp quick fix.  We should update timeout to be overridable at
call time and use alma user_loans specific override.

Increase alma api call timeouts.

---

app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
app/lib/cob_alma/requests.rb
config/libraries.yml
config/locations.yml
config/translation_maps/libraries_map.properties

- Change ASRS mappings for library and location
- Remove "Available at" text for items at ASRS or MAIN
- Change availability button to reflect unavailable for items on ly at ASRS or MAIN
- Refactor descriptions so that they do not include descriptions at ASRS or MAIN
- Requires reindex for the mapping changes

BL-902 More move updates

---

solr/conf/schema.xml

- Currently, searching for a full subject line such as Clothing and dress -
Greece - History gives no results
- Adds a copyfield for subject_display to the list of unstemmed fields in the solr schema to make them searchable
- Requires re-index

BL-889 Subjects in advanced search

---

app/javascript/packs/controllers/explanation_controller.js
app/views/catalog/_search_results.html.erb

- The hide button for the explanation text on search results pages is not currently working.
- Moves the data-target and controller up a level so that they include the button and text div

BL-900 Hide button

---

app/helpers/application_helper.rb
app/models/solr_document.rb
spec/models/solr_document_spec.rb

- Using documents as an argument in the render_ris method is returning nil
- Use the instance varaible @documents to get the document list for export

BL-903 RIS exports for bookmarks

---

app/assets/stylesheets/partials/_availability.scss
app/helpers/availability_helper.rb
app/views/almaws/item.html.erb
config/locales/en.yml
spec/helpers/availability_helper_spec.rb

- Currently some availability statuses are empty, which may cause confusion for the patron.
- Adds an alert message to the top of the availability panel when an availability status is left empty.

BL-877 Availability error message

---

app/controllers/almaws_controller.rb
app/views/almaws/_asrs_request_form.html.erb
app/views/almaws/_booking_request_form.html.erb
app/views/almaws/_hold_request_form.html.erb
spec/controllers/almaws_controller_spec.rb
spec/helpers/almaws_helper_spec.rb

- We previously only passed material types for booking requests, but a user requested this functionality for hold requests as well.

BL-890 Add material type to hold requests

---

app/controllers/catalog_controller.rb

In BL-7 searching documents happens indirectly via `search_service` not directly
in catalog controller.

[BL-908] Fix purchase_order_action breaks after BL-7 upgrade

---

app/controllers/catalog_controller.rb

After BL-7 upgrade we need to fetch documents via search_service.

[BL-908] fix purchase_order_action fail on fetch. (#1224)

---

app/controllers/catalog_controller.rb

After the BL-7 upgrade accessing raw json format is only available via
a new route catalog/:id/raw.json  that must be enabled in order to work.
Enabling the raw format makes our lives easier as developers because we
can more easily review fields that we are actively indexing.
BL-7 removed this feature for security purposes because other
institutions are potentially indexing sensitive information with their
documents.  But we do not index any sensitive information.

Allow access to raw json format.

---

app/controllers/databases_controller.rb
app/helpers/catalog_helper.rb
app/views/catalog/_search_results.html.erb
lib/traject/databases_az_indexer_config.rb

- Makes resource types searchable in all fields searches
- Create separate field for "database" type so that it doesn't display in the facets (currently not being used, but may be in the future)
- Align database type links of record pages

BL-810 Database resource types

---

app/controllers/primo_central_controller.rb

Using flash now keeps flash from being alive when we go to another
action.

[BL-912] Do not flash article notice outside of articles.

---

app/assets/stylesheets/partials/_bento.scss

- Currently the max-height property is dropping databases below the other compartments in some searches. 
- I think this is due to the length of results.  Lowering the max-height seems to solve the issue.

BL-861 Adjust height for bento compartments

---

app/controllers/databases_controller.rb

Rename the az facet fields to avoid collision with the catalog faceting.
The catalog is aware of the facet fields that it has configured but in
order to work it cannot share the same name as facets for other
searches.
This commit updates the az facet fields and takes advantage of a BL
feature that allows us to change the name that BL uses for this field
without needing to change what the field is named in the backend solr
core (i.e. solrcores can duplicate field names).

[BL-917] Rename az facet fields.

---

app/views/application/_navbar.html.erb

- Removes the website link from the top nav so that it isn't accidentally included in the bento updates
- It will be added back in as part of the website integration work

BL-861 Remove link

---

app/helpers/blacklight_marc_helper.rb

REF BL-918
REF WEB-2169
We're using the path instead of url method to create the callback url
for the refworks link.
This fixes that issue.

[BL-918] hotfix refworks link broken for books/journals path.

---

app/views/databases/_home_text.html.erb

- The link to browse databases alphabetically was set to the subject browse instead. This fixes it to use the correct translation.

BL-810 Fix database link

---

app/controllers/almaws_controller.rb
app/lib/cob_alma/requests.rb
app/views/almaws/_asrs_request_form.html.erb
spec/lib/cob_alma/requests_spec.rb

- ASRS pickup locations should include all libraries.  For now, it was requested that these values be hard-coded with (Main campus) included with the Charles Library label.

BL-919 Add pickup locations for asrs

---

app/controllers/databases_controller.rb
app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

- Adding the az prefix to database facet fields broke these two methods. This updates the methods to use the correct field names.

BL-810 database links

---

app/views/search/_home_text.html.erb

- The links on the bento home page were incorrect, this updates the path for the resources.

BL-922 Update links

---

app/assets/stylesheets/partials/_bento.scss
app/views/search/_bento_results.html.erb
app/views/search/index.html.erb
config/blacklight.yml
spec/spec_helper.rb

- With our current configuration, the bento columns are displaying a different number depending on the height of the various results
- Changes the layout to use bootstrap cards for the bento results since the masonry layout is built in with the card-columns class

BL-923 bento columns

---

app/controllers/databases_controller.rb
spec/features/databases_spec.rb

* We don't want any document features (inc. bookmarks) enabled for databases yet.
This was likely missed or we were disabling it incorrectly.
* Adds spec to avoid regression.

Remove bookmarks from  database index view.

---

spec/search_engines/books_and_media_search_spec.rb

VCR was hiding some changes to the way this search_engine is supposed to
work.  Removed it and fixed the test.

Do not use VCR for non api test.

---

docker-compose.yml
lib/tasks/tulsearch.rake

AZ and web-content files should not be ingested when we pass a filepath
to the load_fixtures task, because in this case the ingested files will
not be json.
This commit fixes this issue.

Short circuit the load fixtures task if filpath passed.

---

.travis.yml

Travis has lost support of jdk8 OOB; Trying to switch to jdk9 for now ..
if this doesn't work we may need to upgrade to solr 8 ahead of
schedule.

Switch to jdk9 on travis.

---

README.md
lib/oai/alma.rb
lib/tasks/oaiharvest.rake
lib/tasks/server.rake
lib/tasks/tulsearch.rake
spec/spec_helper.rb

fortytu would work better for a repository named fortytu.  Since this
repo is named tul_cob it makes more sense for its rake tasks to also be
namedspaced by tul_cob.

Rename fortytu namespace tul_cob.

---

app/lib/cob_alma/requests.rb
app/views/almaws/_asrs_request_form.html.erb
app/views/almaws/_booking_request_form.html.erb
app/views/almaws/_digitization_request_form.html.erb
app/views/almaws/_hold_request_form.html.erb
config/locales/en.yml
spec/fixtures/requests/asrs_empty_descriptions.json
spec/fixtures/requests/asrs_repeated_descriptions.json
spec/fixtures/requests/repeated_descriptions.json
spec/helpers/almaws_helper_spec.rb
spec/lib/cob_alma/requests_spec.rb
spec/spec_helper.rb

- Refactors so that the dropdown menu only displays if multiple descriptions are present
- Single descriptions are passed as a hidden field to ensure they are sent to alma
- Returns only unique descriptions
- Do not filter out empty descriptions so that the patron can select the empty option if one item doesn't have a description
- Field should be optional, not required

BL-926 Update description logic

---

app/controllers/almaws_controller.rb
app/views/almaws/_asrs_request_form.html.erb
app/views/almaws/_booking_request_form.html.erb
app/views/almaws/_hold_request_form.html.erb

- Refactor the way we handle material types so that they are sent to alma as a hidden parameter when only one option is present

BL-949 Material types in request forms

---

app/assets/stylesheets/partials/_availability.scss
app/assets/stylesheets/partials/_record_pages.scss
app/helpers/catalog_helper.rb
app/views/catalog/_online_availability.html.erb
app/views/catalog/_purchase_order_anonymous_button.html.erb
app/views/catalog/_show_availability_section.html.erb
app/views/catalog/_show_default.html.erb
app/views/catalog/_show_primary_fields.html.erb
app/views/catalog/_show_secondary_fields.html.erb
spec/helpers/catalog_helper_spec.rb

- Aligns all types of availability content (purchase order, online, etc)
- Fixes content displaying incorrectly in safari browser
- Aligns staff link with the rest of the content
- Adjusts css classes for availability displays

BL-932 Record page availaiblity

---

app/javascript/packs/controllers/form_controller.js
app/views/almaws/_asrs_request_form.html.erb
app/views/almaws/_hold_request_form.html.erb

- The javascript method that returns pickup locations used to be set to empty when no description was selected. This updates the method to display the pickup locations.
- Moves material type above descirption on the ASRS and hold request forms
- Removes unnecessary hidden field code from hold request form
- Fixes a bug that was calling digitization_description instead of hold_descirption in the hold form

BL-926 Description form updates

---

app/helpers/availability_helper.rb
spec/helpers/availability_helper_spec.rb

- Items in the ASRS should display directly after MAIN and before the other libraries

BL-956 Availability sort order

---

Gemfile
Gemfile.lock
app/assets/javascripts/listeners.js
app/assets/stylesheets/tucob.scss.erb
app/controllers/catalog_controller.rb
app/controllers/databases_advanced_controller.rb
app/controllers/databases_controller.rb
app/controllers/journals_advanced_controller.rb
app/controllers/journals_controller.rb
app/controllers/primo_advanced_controller.rb
app/controllers/primo_central_controller.rb
app/views/advanced/index.html.erb
app/views/catalog/show.html.erb
app/views/primo_advanced/index.html.erb

- We were currently displaying breadcrumbs for individual record pages and advanced search pages.  The decision was made to get rid of them, so this removes breadcrumb-related code.

Bl 936 remove breadcrumbs

---

app/assets/stylesheets/partials/_header.scss
app/views/catalog/_search_form.html.erb
app/views/shared/_nav_bar_login_links.html.erb

- With the recent design changes, the logout button was removed.  This adds the button back in next to bookmarks.
- The nav_bar_login template was updated to not display the login option since that link is being generated in the main menu navbar.

BL-951 Add back logout option

---

app/views/almaws/_asrs_request_form.html.erb
app/views/almaws/_booking_request_form.html.erb
app/views/almaws/_hold_request_form.html.erb

- Some requests were not going through to alma.  The problem is with the material types when being passed as a hidden field.  The data was in a form that alma was not able to recognize, so it rejected the request.  This updates the hidden field to return the value of the material type.

BL-959 Requests bug

---

app/controllers/almaws_controller.rb
app/lib/cob_alma/requests.rb
app/views/almaws/_asrs_request_form.html.erb
spec/lib/cob_alma/requests_spec.rb

- Hard coding the wait times into the pickup locations list means that the request does not go through to alma since it doesn't know how to handle that text.  This removes the extra explanation and goes back to the original method.

BL-959 ASRS request bug

---

app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
app/helpers/availability_helper.rb

- SCRC items need to display as unavailable until the research room opens
- This hides the available at display in the search results, makes the button display unavailable for SCRC items, and updates the availaibility message for SCRC items

BL-966 SCRC availability

---

app/lib/cob_alma/requests.rb

- Until the fourth floor opens, MAIN stacks and Juvenile collections need to be available for pickup at Charles.  
- This removes Charles from the MAIN campus so that items can be picked up there
- It retains the logic for the rest of the campuses

BL-964 MAIN stacks should be requestable at Charles

---

config/locations.yml
spec/helpers/availability_helper_spec.rb

- Updates the external names for Stacks and Juvenile to temporarily display as Remote Storage until the 4th floor opens

BL-964 Location changes

---

app/helpers/availability_helper.rb
config/locations.yml

- Items that don't fit in the ASRS should display Main Storage as the location
- They should display Temporarily unavailable as the avail_status
- This will require a restart of the application, but not a reindex

BL-965 Temporary storage items

---

.circleci/deploy-prod.sh

Depends on running next prod deploy in circle. Will give ansible logs along with already logged output.

adding verbose flag to prod deploy for tracking down assets error

---

app/controllers/almaws_controller.rb

- We are not currently filtering out missing and lost items from the request options method in the controller.  This sometimes results in patrons not seeing the correct request options.  This adds the filter_missing_and_lost method to items

BL-990 Request Options bug

---

app/controllers/web_content_controller.rb
solr_web/conf/schema.xml

Fixes BL-994 - Finding aid not searching description field,
This is actually also true  of other entities like policies. Fixes this for all entity types specifying in the contoller which fields should be searched in qf and pf params, including boosts.
Fixes BL-986 "Did you mean to type: ?" showing up in web results
Adds controller config to turn off suggestions
"Fixes" BL-991 - Select Finding Aids not appearing in Library Search.
This error was caused by copying huge finding aid descriptions into the `suggest` field. `suggest` should be a text field, and thus have no byte limit, but it is throwing errors. "Fixes" that issue by removing the solr schema copyField configuration to suggest since we aren't currently using the suggest fields.
Additionally, not sure if updating the schema in …

Fixes multiple issues with Web Contetnt Search

---

app/controllers/web_content_controller.rb
solr_web/conf/schema.xml

Fixes BL-994 - Finding aid not searching description field,
This is actually also true  of other entities like policies. Fixes this for all entity types specifying in the contoller which fields should be searched in qf and pf params, including boosts.
Fixes BL-986 "Did you mean to type: ?" showing up in web results
Adds controller config to turn off suggestions
"Fixes" BL-991 - Select Finding Aids not appearing in Library Search.
This error was caused by copying huge finding aid descriptions into the `suggest` field. `suggest` should be a text field, and thus have no byte limit, but it is throwing errors. "Fixes" that issue by removing the solr schema copyField configuration to suggest since we aren't currently using the suggest fields.
Additionally, not sure if updating the schema in …

Fixes multiple issues with Web Content Search (#1436)

---

app/views/catalog/_email_form.html.erb
app/views/catalog/_sms_form.html.erb

- Emails and texts take a few seconds to process.  Users are not given any indication that their request was made, which sometimes results in them clicking submit multiple times.  
- This adds a data disable_with attribute to both buttons that disables the button so that it can't be clicked again and changes the text to read Sending email/text... to let the user know it is being processed.

BL-898 Disable multiple clicks on email/text submit buttons

---

app/views/catalog/_show_fields.html.erb
app/views/catalog/_show_primary_fields.html.erb
app/views/catalog/_show_secondary_fields.html.erb

- The code to generate the fields was being duplicated in both the primary and secondary partials. This pulls the duplicate code to its own partial so that we can use it only once.

BL-947 Refactor show field templates

---

Gemfile
Gemfile.lock

In order for rails to pick up .env variables we need to install
dotenv-rails.

Add dotenv-rails to the project.

---

app/controllers/almaws_controller.rb

Refactor request_options to use a private method to get the largest set of request options instead of duplicating code
- Moved the code to a private message so that it isn't duplicated
- Handles cases where request_options is nil

Bl 998 request options bug

---

app/controllers/almaws_controller.rb
app/helpers/almaws_helper.rb
app/lib/cob_alma/requests.rb

If the item selected is beyond the default 100 returned then there is
items is not found when trying to submit request.
* Makes sure we process all items.
* Adds error notice if no request was possible.
* Sorts items.

BL-1003 Fix item request sometimes fails when more than 100 items.

---

app/assets/javascripts/listeners.js
app/views/application/_mobile_nav.html.erb

- Having the my-acocunt id in both website headers is throwing a duplicate Id accessibility error.  This changes the id for the mobile link and adds it to the Google Analytics listeners

BL-972 Duplicate Ids

---

app/models/blacklight/primo_central/response.rb

Raises BlacklightRangelimit::IvalidRange is min is greater than max in
user provided range.

[BL-856] Raise invalid range limit if min > max.

---

app/helpers/availability_helper.rb
spec/helpers/availability_helper_spec.rb

- We currently display an alert that availability can't be found for items with blank items_json_display fields.
- Electronic items don't have those fields, so the method is throwing an error.  Refactor the method to not include items with the electronic_resource_display field.

BL-1011 Availability alerts

---

app/controllers/almaws_controller.rb

- @request_options is no longer returning nil when empty, so when the first set of request options is empty, it does not try another item
- This ensures that @request_options.request_options is nil so that another attempt is made to get the request options from alma

BL-1016 Request options bug

---

app/controllers/almaws_controller.rb

In cases where items is an empty set, `get_largest_request_options_set`
method will return `nil` so `@request_optioins.request_options` would
throw an error. We can avoid the error by using guard operator, &.

[BL-1016] avoid throwing error if options truly nil.

---

app/helpers/availability_helper.rb

When "items_json_display" is not present we throw a no map method on
nil.  This commit fixes the issues by using &. operator and checking is
results are `.present?`

[BL-1011] Fix avaiability_alert helper error.

---

app/lib/cob_alma/requests.rb
spec/fixtures/requests/temp_storage.json
spec/lib/cob_alma/requests_spec.rb
spec/spec_helper.rb

- Records that have items in temporary storage are not returning the correct request options.
- This filters out items in the temporary storage location right now from the method that gets request options so that we don't return nil options
- Adds specs for the method since there weren't any previously

BL-1018 Request bug

---

app/lib/cob_alma/requests.rb
spec/fixtures/requests/temp_storage.json
spec/lib/cob_alma/requests_spec.rb
spec/spec_helper.rb

- Our last hotfix did not catch all of the errors related to items without an items_json_display field.  Refactors to catch all instances.
- Filters out items in temporary storage from the method that gets request options to limit returning nil.

Set up v0.11.2 release

---

app/assets/javascripts/application.js

- We have an issue where pages are loading at the bottom.  This adds a javascript function to ensure that pages are loaded at the top unless there is a location hash(we don't want it to override redirects)

Bl 1019 fix loading page bug

---

app/helpers/primo_central_helper.rb

- Article direct links in the bento search are currently not working.  
- Removing the use of the single_link_builder method inside bento_availability seems to resolve the issue.

BL-1005 Bug with bento direct links

---

.circleci/deploy-prod.sh
.circleci/deploy-qa.sh
.circleci/deploy-stage.sh

I wont pretend like I know exactly what ansible magic is going on here
but, this seems to make a difference when I deploy from my local.
i.e. using `-i inventory/qa` instead of `-i inventory/qa/hosts`

Use all environment inventory changes on deploy.

---

app/helpers/application_helper.rb

- Use the same classes as the request form submit buttons
- "Go to SCRC Researcher Account" should not be bold

BL-955 Aeon button

---

.rubocop.yml
app/helpers/catalog_helper.rb
app/views/catalog/_other_library_options.html.erb
spec/helpers/catalog_helper_spec.rb

- EZ borrow list item should only appear in the catalog no results page
- Adds a helper method to include this list item when in a catalog search
- Adds specs and updates a rubocop style that was obsolete

BL-1007 Illiad text

---

app/helpers/application_helper.rb
app/search_engines/bento_search/blacklight_engine.rb
app/search_engines/bento_search/databases_engine.rb
app/search_engines/bento_search/journals_engine.rb
app/search_engines/bento_search/primo_engine.rb
app/search_engines/bento_search/web_content_engine.rb
app/views/primo_central/_tagged_refworks.erb
config/routes.rb

Blacklight Raange Limit adds search_field=dummy_range if dummy_range is
not set in the query. This seems to be an outdated requirement that I'm
trying to get removed and thus fix issue, but in the mean time we can
fix our issue simply by making sure we set the param searc_field=all
when submitting queries to the catalog.
REF: projectblacklight/blacklight_range_limit#109
REF: BL-1017

[BL-1017] Fix dummy_range field bug

---

app/models/citation.rb

- Currently, if a HTTParty response is not in html format, it is throwing an error.
- This checks the response, and if it is invalid it will notify Honeybadger and give the user the default no citations message instead of an error

BL-1037 Citations bug

---

app/search_engines/bento_search/primo_engine.rb
config/routes.rb

New route is causing article redirects to blank page.
This commit removes that route and update helper method that required
it.

[BL-1039] Fix routing issue with articles.

---

.rubocop.yml
app/helpers/almaws_helper.rb
app/views/almaws/_asrs_allowed.html.erb
app/views/almaws/_booking_allowed.html.erb
app/views/almaws/_digitization_allowed.html.erb
app/views/almaws/_hold_allowed.html.erb
app/views/almaws/_resource_sharing_broker_allowed.html.erb
spec/helpers/almaws_helper_spec.rb

- If only one request option is available, the collapse form is supposed to default to being open.  This was not always happening.
- We currently are just checking whether different request options are available, which sometimes results in multiple options being true.  This updates the relevant request options to include additional logic that we pass to limit displays, such as available_asrs_item or non_asrs_item.

BL-1050 Request form displays

---

config/routes.rb

I just noticed that clicking on "Start Over" button always takes you to "/bento".
It should go to "/everything".  This commit fixes that minor issue.

Update BentoSearch engine root path.

---

app/controllers/databases_controller.rb

Catalog solr configs break the databases solr because solr will now
throw an error (solr8 change) when we try to query using fields are not
defined.

Do not inherit default solr configs from the catalog.

---

app/assets/javascripts/application.js

- Changing our jQuery to 3 in the application.js file caused the modal functionality to stop working. Revert back to requiring only jQuery

BL-1088 Blacklight modal bug

---

app/controllers/databases_controller.rb

There seems to be an issue with the  way solr_parameters work in
solr8... for now we can do a work around by using a custom query handler
for title, and subject searches.
TODO: look into proper way of using solr parameters in solr8.

Switch the search query handler for title and subject searches.

---

.circleci/config.yml
.circleci/test.sh
.rubocop.yml
Gemfile

Fixes ci not reporting failure in ruby tests.

BL-1069 seperate out linting, ruby and javascrpit tests.

---

docker-compose.yml

Passes DO_INGEST from local host into the container so that it can be used in the starter script.

Fix DO_INGEST load data option.

---

app/assets/stylesheets/partials/_bento.scss
app/controllers/search_controller.rb
app/search_engines/bento_search/cdm_engine.rb

- Removes if/else statement so that the total number of results is returned when search query is empty
- Fixes css error where some resource type links were red instead of black
- returns cdm totals with comma delimiter

BL-1061 Fix for digital collections bug

---

app/helpers/availability_helper.rb
app/views/catalog/_main_open_shelving_instructions.html.erb
spec/features/availability_spec.rb
spec/fixtures/availability_features.yml
spec/helpers/availability_helper_spec.rb

- We currently display a banner message on all items that are in the MAIN library.  This is misleading for items that are not in the bookbot, but are also not on open shelving(reserves, reference, etc.)
- Refactors the code to display the message based on location and library.  The message should display for any items found in these locations: hirsch, juvenile, leisure, newbooks, stacks

BL-1048 Message on open shelving materials

---

app/helpers/blacklight_helper.rb

BL v7.4.0 update broke the labels when Document is empty.
This commit reverts the broken method to the v7.3.0 version that still works.
See projectblacklight/blacklight#2234 for more details.

BL-1090 Fix document_link error.

---

app/helpers/almaws_helper.rb
spec/helpers/almaws_helper_spec.rb

- Currently asrs item requests are restricted to only items that are in place.
- This adjusts the logic so that DVDs can be reserved regardless of whether they are checked out, in trasit, etc.

BL-1032 Make DVDs requestable

---

.rubocop.yml

The Style/BracesAroundHashParameters cop has been removed from Rubocop.  We need to remove it in order to get the latest Rubocop version.

Removes obsolete cop

---

app/javascript/packs/controllers/advanced_controller.js
app/views/advanced/_advanced_search_fields.html.erb

- The begins with operator does not currently work for all fields.
- This hides the begins with operator when a user selects a field from the search options dropdown that does not support that functionality

Bl 1108 begins with operator

---

app/javascript/packs/controllers/advanced_controller.js

- If a user has selected the begins with operator and then goes to a field that doesn't support that, it should not still display the words begins with

BL-1108 Hide begins with text when selected (#1729)

---

app/javascript/packs/controllers/advanced_controller.js

Release notes:
* Add additional webpages to Website search results
* Add phonetic matching for Website search results (ex. a query for “Matt” now returns results for “Matthew”)
* Updated indexing process to exclude “empty” catalog records that do not have an attached holding/item, portfolio, or other electronic resource link
* Updated subject heading displays for “noncitizens" and "undocumented immigrants"
* Fixed “Begins With” operator in Books & Media and Journals advanced search

set up release v0.14.2

---

app/controllers/catalog_controller.rb
app/views/kaminari/blacklight/_paginator.html.erb
config/locales/en.yml
spec/features/indices_spec.rb

- We currently allow users to click on or enter into the web url pages that take too long to load and result in a timeout.
- Removes links from pagination and adds a before action to prevent loading pages past 250

BL-1158 Fix deep paging issue

---

app/assets/javascripts/book_covers.js

- Currently the javascript is looping over all of the isbn numbers to search for a preview, so whatever the data is for the last isbn number in the list is being used.
- Sometimes the last isbn number has noview, but a previous identifier did have a preview.  This code refines the function so that if a full or partial preview is found, we break out of the loop and return the link.

BL-1155 Google books preview update

---

Gemfile
Gemfile.lock

- The newer version of this gem is causing multiple issues with the display of the date range facet. - This reverts back to the version we were using before for now.

blacklight-range-limit update

---

.docker/app/Dockerfile
bin/app-start.rb

* alpine is a supported official docker image flavor.
* Temple IST scans images for vulnerabilities and debian images always
fail.
* Temple IST will host official ruby alpine images for us on request.
* The first time you run this use `docker-compose -f docker-compose.yml -f docker-compose.local.yml build --no-cache` in order to force it to rebuild your local images using the new alpine base.
* The first time will take longer because you are fetching the base image and rebuilding your local images from scratch.

Switch to using alpine based container.

---

app/assets/stylesheets/partials/_typography.scss
app/views/layouts/blacklight.html.erb

- Use font-display: swap attribute so that the browser uses a fallback font until the custom font has downloaded
- Preconnect to font awesome and google books to help improve performance

DEVO-64 More font updates

---

app/models/json_store.rb
db/migrate/20200422020027_create_json_stores.rb
db/schema.rb

JSON fields are not allowed in our version of MariaDb.
This commit updates our schema/migration to create and use a text field.
The model has been updated to auto-magically serialize into JSON.

Update e-notes value field to be text not json.

---

.circleci/config.yml
Makefile

The way we were copying cache between circle coordinator and remote
docker machines was recursively copying direcctoires inside of already
existing directories. Doing this over and over again built a huge cache
of many copies of our bundled files. This fixes that.

Fix recursive cache copying on CircleCI

---

package.json
yarn.lock

* Js-yaml: prior to 3.13.1 are vulnerable to Code Injection. The load()
function may execute arbitrary code injected through a malicious YAML
file.
* serialize-javascript: Affected versions of this package are vulnerable
to Cross-site Scripting (XSS). It does not properly mitigate against
unsafe characters in serialized regular expressions.

Apply security updates for js.

---

.circleci/config.yml
.circleci/deploy-stage.sh
doc/deployment-process.md
doc/new-release-process.md

CI will now.
* Deploy to tul_cob/qa on merges to master branch.
* Automatically deploy to stage when a new release is created.
* Deploy to production on confirmation when a new release is created.

Update tul_cob CI to be master branch only.

---

app/helpers/availability_helper.rb
spec/helpers/availability_helper_spec.rb

- This is a temporary change due to the library closure so that patrons can't request physical materials

BL-1190 Hide temporary recall link

---

app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

- lccn numbers should include alphabetic prefixes.  This removes the logic that stripped lccn numbers down to only digits and adds a test.

BL-1175 lccn data attribute

---

app/controllers/catalog_controller.rb
app/controllers/search_controller.rb
app/views/errors/unsupported_query.html.erb
config/locales/en.yml
spec/controllers/search_controller_spec.rb
spec/features/bento_availability_spec.rb
spec/features/bento_search_spec.rb
spec/fixtures/vcr_cassettes/bento_availability_item_1.yml
spec/fixtures/vcr_cassettes/bento_availability_item_2.yml
spec/fixtures/vcr_cassettes/bento_search_features.yml
spec/spec_helper.rb

When a blacklight search engine fails for some reason, the user should see an appropriate message. In the case of bento searches, the bento_search gem is stashing the exception and the app consequently falls over during the view rendering process. This commit raises the stashed exceptions, and adds handling for Blacklight's InvalidRequest exception, which wraps RSolr's exception when it receives an error response from Solr.
See: https://tulibdev.atlassian.net/browse/BL-1227

die gracefully when search engine(s) fails

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/icons.css.erb
app/assets/stylesheets/tucob.scss.erb
app/helpers/render_constraints_helper_behavior_override.rb

* Updates blacklight_range_limit to latest version.
* Patches JS issue (projectblacklight/blacklight_range_limit#111)
* Hides remove button (to keep current behavior)
* Patches render_constraints_filters method (projectblacklight/blacklight_range_limit#152)
Does not override the range limit view because we would need to override the entire view and thus lose possible upgrade changes.
New version:
Old version:

BL-1171: Update blacklight_range_limit.

---

.circleci/deploy-prod.sh
.circleci/deploy-qa.sh
.circleci/deploy-stage.sh

We introduced ansible flag `--limit=app` to preovent solr changes from being pushed, but this also prevented db changes from being pushed, which was an undesired side effect.
Now that all deplys happen via thos repo, and not via tul_cob_playbook, we need to remove the limit so changes to the db server get deployed.

Don't limit to app in deploys

---

app/controllers/catalog_controller.rb
app/search_engines/bento_search/primo_engine.rb
spec/search_engines/primo_search_spec.rb

This will change the Primo bento message from an error to a "no results found" when the query is empty. It also adds a catch for NoMethod errors in the controller.

Bl 1247 bento empty query errors

---

app/search_engines/bento_search/cdm_engine.rb
spec/search_engines/cdm_seach_spec.rb

Fixes URI::InvalidURIError error in CDM search context.

BL-1248: Make sure query is URL encoded.

---

app/controllers/application_controller.rb
app/lib/feature_flags.rb
config/initializers/features.rb
spec/controllers/application_controller_spec.rb
spec/lib/feature_flags_spec.rb

﻿Adds a feature flag that can toggle functionality that depends if our campus as open as ususal,  or closed for long periods of time because of social distancing requirements.
The feature flag uses the env var $CAMPUS_CLOSED, defaulting to false if the env var does not exist. If env var is set, will only evaluate to false if the value is "false". All others values evaluate to true.
The env var flag can be overriden by a URL paramter "campus_closed". If the URL parameter is present passed and the value is "false", the flag will evaluate as false. Any other value passed to the URL paramter will icause the flag to be evaluated as true.
Adds the class `FeatureFlags` with the method `campus_closed?` so that it can be called from anywhere in the code base.
Adds a convenience helper_method to …

Add feature flag for campus closure

---

app/views/almaws/request_options.html.erb

Removed X close button from request pop-up.
Removing the Cancel button had negative implications for users tabbing, or using other assistive technologies.

#BL-1261 Styling - Remove cancel button

---

Gemfile.lock
app/helpers/users_helper.rb
app/views/almaws/request_options.html.erb
spec/helpers/users_helper_spec.rb

- Ruby DateTime class doesn't recognize date string with
trailing 'Z'. Strip trailing 'Z' if it's on the expiry_date

#BL-1127 Workwround for improperly formatted expiry date

---

Gemfile.lock
app/controllers/catalog_controller.rb
app/helpers/catalog_helper.rb
app/views/advanced/_advanced_search_facets.html.erb
app/views/catalog/_hathitrust_link.html.erb
spec/helpers/catalog_helper_spec.rb

* Handle JSON formatted hathi fields that now include access details and add  display handling logic that respects the "campus_closed" feature flag.
* Update Availability facet to include Hathi "ETAS" records when campus is closed
* Update Advanced Search facet handling to respect facet config `if`/`else` attributes.

Update handling HathiTrust data for display and online availability

---

app/views/catalog/_index_availability_section.html.erb

- Merging the params in item_url was also merging the page param,  causing availability status to not display after the first page of results. We can use .except to avoid this.

BL-1277 Availability status bug

---

spec/models/search_builder_spec.rb

filter_suppressed may not be temporary because it solves other issues.  Adding this missing spec.

Add spec for filter_suppressed method

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
spec/controllers/catalog_controller_spec.rb
spec/models/solr_document_spec.rb

Since we were not able to correctly suppress results form the document and realtime get handlers,
we have opted to override Blacklight Catalog COntroller show method to raise an reocrd not found errors if
a document has the expected value in the suppress field.
Still needs a test.

Overide Blacklight Show to suppress some items

---

.circleci/config.yml
Makefile
docker-compose.yml

When we set this path bundle install inside docker happens inside of /app/vendor/bundle vs /usr/local/bundle by default.
* We don't need to copy local root files to the docker instance because
by default this is done for us.

Add BUNDLE_PATH env.

---

app/models/blacklight/primo_central/search_builder_behavior.rb
spec/models/primo_search_builder_spec.rb

TODO: Fix empty date-range search defaults.
If start and end dates are empty string do not add date range facet.

Do not add empty date range search.

---

app/controllers/concerns/bookmarks_config.rb
app/models/blacklight/primo_central/repository.rb

Will limit number of bookmarks to 100 but fixes page brake.

Set default_per_page to be 100.

---

.env.vagrant

Since we now have a `.env` file in the repo, having any `.env.INVENTORY_NAME` will break the rails role. Others were previously removed. This removes the vagrant one

no vagrant env file

---

app/assets/javascripts/blacklight_overrides.js
app/controllers/almaws_controller.rb
app/controllers/application_controller.rb
app/controllers/catalog_controller.rb
app/controllers/concerns/server_errors.rb
app/views/errors/alma_request_error.html.erb
spec/controllers/almaws_controller_spec.rb
spec/controllers/catalog_controller_errors_spec.rb
spec/controllers/primo_central_controller_spec.rb

Improves error handling by:
- ensuring we don't send the rails 500 message to the end user
- consolidating error handling in a 'concern'
- giving us a headstart when we find out a primo query has caused an error.
See also:
https://github.com/tulibraries/primo/pull/35

move general controller rescuing to a concern, handle primo errors

---

lib/tasks/tulsearch.rake

I've noticed that recently we sometimes are overriding SOLR_URL with the
production URL in our locals to test issues.
Thus, in order to avoid inadvertently polluting the production Solr
database with our local fixtures, I'm adding a snippet to abort when
there's a potential for doing that.

Abort if trying to load fixtures into our prod sever.

---

app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

- Add object resources to the exclusions for displaying "get help finding a digital copy"

BL-1304 Digital copy exception

---

app/controllers/concerns/server_errors.rb

We are swallowing errors in the development context. Which is not useful.
This commit skips error handling enhancements when in development mode.

Add back errors in development context.

---

app/models/search_builder.rb
spec/controllers/catalog_controller_spec.rb

https://app.honeybadger.io/projects/56250/faults/53917673

BL-1079 Prevent parselet errors on empty advanced search fields

---

app/models/search_builder.rb
spec/models/search_builder_spec.rb

Solr treasts '?' as a special wild character.  If you search for "hats?"
it is actually trying to search for something more like "hats[a-z]"
where that last character cannot be null.
Easiest way to fix this issue is just to strip ? chars from our query
string since we don't actually expect our users to know about these Solr
quirks.

BL-1301: Fix no results for some queries with '?' in them.

---

app/views/catalog/_results_pagination.html.erb
app/views/catalog/index.html.erb

- The automatic row styles were causing extra spacing to appear on small screen sizes.  Adding no-gutters eliminates the problem.

Fix styling bug

---

app/controllers/catalog_controller.rb
app/controllers/primo_central_controller.rb
app/helpers/catalog_helper.rb
app/javascript/packs/controllers/index_controller.js
app/search_engines/catalog_bookmark_search.rb
app/services/primo_search_service.rb

This adds back bookmark options for articles in the bookmarks context.
This also fixes a bug with bookmark deletes do to pnx to cdi id
conflicts.
Finally, and unfortunately,  I had to also revert some changes we made
earlier that removed deprecation warnings.  However, without the revert
there is a bug that we did not notice because we had disabled article
bookmarks prior to merging that change.
Since we will be removing the custom code that was required to enable
article bookmarks, I think that it's OK to revert this one change as we
will fix the issue soon simply by removing the deprecated code.

BL-1310: Reenable article bookmark deletes.

---

app/models/blacklight/primo_central/repository.rb
app/models/blacklight/primo_central/search_builder.rb
app/search_engines/bento_search/primo_engine.rb
app/services/primo_search_service.rb
spec/controllers/primo_central_controller_spec.rb
spec/models/primo_central_repository_spec.rb
spec/models/primo_search_builder_spec.rb

We are still doing an unnecessary search when we switch to article view
but have not done a search (the blank page)

BL-1299: Skip article search on empty search.

---

app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

Adds a helper than can be used to derive the search term we should use to search libguides for a recommendation.
At present, it only returns the original search query being sent to solr. Added as helper so underlying implmentation can be swapped.

Add placeholder implementation for libguides search term

---

app/controllers/almaws_controller.rb
app/javascript/packs/controllers/form_controller.js
app/lib/cob_alma/requests.rb
app/views/almaws/_asrs_request_form.html.erb
app/views/almaws/_booking_request_form.html.erb
app/views/almaws/_digitization_request_form.html.erb
app/views/almaws/_hold_request_form.html.erb
spec/lib/cob_alma/requests_spec.rb

- We are currently throwing errors when a user selects a material type and a description that does not exist for the selected material type.
- This code groups the descriptions by material types and filters the description dropdown based on the material type selected

BL-1102 Request bug

---

app/models/search_builder.rb
spec/models/search_builder_spec.rb

If an empty param,`()`, is included in a query, the boolen query parser included from advanced search gem throws an error.
It is documented as an issue upstream at projectblacklight/blacklight_advanced_search#101, but at the moment no fix upstream is proposed.
This PR works around the issue by removing empty parens from the query string. It does not impact parens containing content.

Parse out empty params from queries

---

app/presenters/facet_item_presenter.rb
spec/presenters/facet_item_presenter_spec.rb

Blacklight::SearchState::to_h returns the actual param hash, so using it to render facet params causes bad side effects (deleting search params). So we can just utilize the existing remove and add functions, which return deep copies of that facet hash.

avoid using SearchState::to_h when tweaking facet href params

---

app/controllers/search_controller.rb
app/helpers/catalog_helper.rb
app/models/lib_guides_api.rb
app/views/catalog/_lib_guide_recommender_catalog.html.erb
app/views/search/_lib_guide_recommender_bento.html.erb
spec/controllers/search_controller_spec.rb
spec/helpers/catalog_helper_spec.rb
spec/models/lib_guides_api_spec.rb

This pull requests updates the way we generate search queries to send to the libguides API and changs how we handle the API response before generating html.
Instead of sending only the original search term to the libguides API, we now grab the orginal search term plus the top 10 subject_facet_topic terms, wrap each term (which can be multiple words) in parenthesis and then join all of the terms with a boolean `OR`. This allows for a much broader search than the possibly very narrow original search query.
Additionally, we also process the response from the libguides API to boost Subject Guides and Topic Guides over Course Guides and General Purpose guides.

Update libguides search terms and response handling for better relevance

---

app/models/lib_guides_api.rb
spec/models/lib_guides_api_spec.rb

We don't want to recommend internal or private guides, so limit the types returned in the API call.

Only request published, handled types of guides

---

app/assets/stylesheets/partials/_index_results.scss
app/controllers/lib_guides_controller.rb
app/javascript/packs/controllers/lib-guides_controller.js
app/views/catalog/_index_default.html.erb
app/views/catalog/_lib_guide_recommender_catalog.html.erb
app/views/catalog/_lib_guide_section.html.erb
app/views/catalog/_search_results.html.erb
app/views/catalog/index.html.erb
app/views/lib_guides/index.html.erb
config/locales/en.yml

- Adds translations for default text
- Uses javascript to insert lib guides section into catalog results
- Adjusts styling that needed to be changed after editing the original files
- Moves where we call lib guides in the catalog so that it only gets called once

Clean up lib guides work

---

.env
app/helpers/facets_helper.rb
app/helpers/render_constraints_helper.rb
spec/helpers/facets_helper_spec.rb
spec/helpers/render_constraints_helper_spec.rb

REQUIRES FULL_REINDEX
Move location translation step to indexing time because doing that
handles collapsing items that should be treated as coming from the same
location.  Otherwise they appear as duplicates or have the wrong facet
count.

BL-1052: Remove location translation step.

---

app/models/search_builder.rb
spec/controllers/catalog_controller_spec.rb

Seems like some queries result in a blank string rather than a nil value for the q_X param. See:
https://app.honeybadger.io/projects/56250/faults/53917673

use blank? rather than nil? to prevent parselet errors

---

Gemfile
Gemfile.lock

- cob_az_index is now a main only repo, so we need to point to that branch

DEVO-260 Update cob_az_index branch

---

app/models/blacklight/primo_central/search_builder.rb
spec/models/primo_search_builder_spec.rb

Skip search only when no queries (including advanced ones) are set.

BL-1335 Fix advanced article searches skipped.

---

app/views/almaws/_asrs_request_form.html.erb

We recently updated the way descriptions are handled in the request forms, basing them on material type.  The asrs_descriptions instance variable now returns [["DVD", [""]]] in order for the dropdown menus to work.  This works when there are multiple descriptions present and the user is selecting one.
When items only have 1 description, we pass the params["description] through a hidden field. But, this is adding the material_type key("DVD") as a description in the hidden_field.  This updates the form to return the last description instead of the nested array that includes the material type value.

Fix for request bug

---

config/application.rb
config/deploy_to.yml.example

* The relative URL root is set to the default ("/") for all our
environments. Therefore this configuration is no longer needed.

Remove unnecessary configuration.

---

docker-compose.ci.yml

Set ci docker bundle path to /app/vendor

---

app/assets/javascripts/application.js
app/assets/stylesheets/partials/_record_pages.scss
app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

For subject_display fields with subdivisions (i.e. those that we have
concatenated together using an em dash), add link options for searching
each level of the subject heading using the subdivisions on the full
record page

BL-1166: Add hierarchical linking to subjects.

---

app/helpers/catalog_helper.rb
app/models/solr_database_document.rb
app/views/catalog/_show_availability_section.html.erb
spec/views/catalog/_show_availability_section.html.erb_spec.rb

Skips adding stimulus controller to document show page when viewing
databases as databases have not alma availability information that needs
to be loaded.

BL-1323 Do not hit alma on database page.

---

app/views/shared/_footer.html.erb
config/locales/en.yml

- Adds EZBorrow and Illiad links to the footer
- Updates the link for Illiad to not use the proxy

BL-1328 Footer links

---

app/assets/stylesheets/partials/_record_pages.scss

* Do not underline visited link (avoid weird sub link underlining)

BL-1166: follow up, do not underline visted.

---

.circleci/config.yml
Makefile

dockerhub will begin to throttle non anthenticated pulls so we need to
authenticate our pulls now.

Authenticate dockerhub pulls.

---

app/controllers/errors_controller.rb
config/routes.rb
spec/routing/routing_spec.rb

See:
https://app.honeybadger.io/projects/56250/faults/71188759
What happened:
The app raised a routing error, and because it was in the production environment, tried to render an error page while recovering and then errored while rendering due to an environment variable that wasn't there being expected by the template. I have fixed both issues (I hope!).

respond with not found for all random requests

---

app/controllers/errors_controller.rb
spec/controllers/errors_controller_spec.rb

Application faulted when a request contained a file extension, e.g., http://librarysearch/foo/bar.txt
https://app.honeybadger.io/projects/54521/faults/71255924

always render error pages as html

---

app/controllers/catalog_controller.rb
app/controllers/concerns/lc_classifications.rb
app/helpers/catalog_helper.rb
app/presenters/index_presenter.rb
app/presenters/primo_central_presenter.rb
app/views/catalog/_fields.html.erb
spec/controllers/catalog_controller_spec.rb

Repost of: https://github.com/tulibraries/tul_cob/pull/2304
- abstracted logic for displaying lc classification to a controller concern
- created a local IndexPresenter class to customize fields_to_render so we only have to iterate through field presenter creation one time.

BL-1373 conditionally render lc classification metadata

---

spec/controllers/almaws_controller_spec.rb
spec/controllers/catalog_controller_errors_spec.rb
spec/controllers/catalog_controller_spec.rb
spec/controllers/primo_central_controller_spec.rb
spec/spec_helper.rb

Adds an option to use `rescue_from` when testing controllers, and turns it off by default so ci failures will be more informative.

allow controller errors to raise by default in tests

---

app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

- The original implementation excuded hathitrust items from the get help finding a digital copy method.  
- Now that we are open and not using hathitrust, we need to remove this exclusion so that the request panel displays.

BL-1365 Digital help bug

---

app/controllers/errors_controller.rb
app/models/concerns/blacklight/document/email.rb
app/models/purchase_order_mailer.rb
config/application.rb
config/email_groups.yml

Pulls the rapid request email addressee into a config file.
Also wraps a line in the mail constructor in a begin / rescue to protect against errors arising in the alma gem when the item has no holdings.
Unrelated change to prevent serving an html page for missing asset files.

Bl 1364 add email address

---

app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

- We still provide hathitrust links for open source materials, so they should not display the "get help finding a digital copy" tab

BL-1365 Digital copy bug

---

app/controllers/concerns/lc_classifications.rb

Refactor to use present and only no returns.

Refactor lc_call_number_ender_on_index?

---

app/views/blacklight/nav/_bookmark.html.erb

* grasping at straws.. something is trying to do
current_user_or_guest.bookmarks <<    and it's throwing an error.  But
we can't figure out what could be doing this.

Move parens into inside of span.

---

Gemfile

- The omniauth security update is throwing this error: RuntimeError:
MiniProfilerRails initialized twice. Set `require: false' for rack-mini-profiler in your Gemfile

Set rack-mini-profiler to require: false in Gemfile

---

.circleci/config.yml

Presuming this doesn't break the actual CircleCI build, this change should enable CI jobs to run locally on OSX - example:
`circleci local execute --job run_tests`

set permissions on docker host socket so osx can run circlci jobs

---

app/models/search_builder.rb
spec/models/search_builder_spec.rb

Skips providing a defaut lc range when no range was given for both
begining and end of range.

BL-1418: Fix advanced search different than basic search.

---

app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
app/helpers/application_helper.rb
spec/controllers/catalog_controller_errors_spec.rb
spec/controllers/catalog_controller_spec.rb
spec/controllers/errors_controller_spec.rb
spec/controllers/sessions_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/helpers/application_helper_spec.rb

* Add threading for concurrent http calls.
* Add caching to avoid making expensive HTTP calls.
* Add default behavior when network times out.
* Reduce network timeout to 1 second (should always be less than 1 second)

BL-1438: Make manifold alerts more robust.

---

app/controllers/users/omniauth_callbacks_controller.rb

Adds temporary debugging code in order to more easily debug auth issue on k8.
Logs the Idp raw xml response.

Add temporary debugging code for saml k8 debugging.

---

Gemfile
Gemfile.lock

Updates blacklight_range_limit_gem in order to prevent it from making
inefficient queries.
REF: projectblacklight/blacklight_range_limit#170

BL-1358: Prevents the blacklight_range_gem from making efficient queries

---

app/search_engines/bento_search/blacklight_engine.rb
app/search_engines/bento_search/databases_engine.rb
app/search_engines/bento_search/journals_engine.rb
app/search_engines/bento_search/primo_engine.rb
app/search_engines/bento_search/web_content_engine.rb

Prevents params from being propagated via bento_links.

BL-1424: Do not propagate URL params in bento links.

---

app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

*  Updates method to not render a link if only relation is present
*  Adds some tests to this helper method.

BL-1514: Refactor additional_title_link

---

app/controllers/catalog_controller.rb

- Adjust date ranges for newly added facet to not include the current week
- BL-1520 Add secondary sort to newly added

BL-1473 Update date ranges

---

app/views/web_content/_index_default.html.erb

The empty link causes a ghost tab issue.

BL-14096: Do not generate empty link.

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

* When creator name is not present the name link should not be
generated.
* Adds test for browse_creator method.
* Refactors

BL-1533: Fix creator link when name not present.

---

app/controllers/catalog_controller.rb
app/models/search_builder.rb
spec/features/call_number_facet_spec.rb
spec/models/search_builder_spec.rb

A bug in the blacklight_range_limit gem was allowing the
lc_classification facet constraint to show up even though it wasn't being
configured as a facet field in the controller.
When this bug was fixed it caused the lc_classification constraint to
disappear.
This commit configures the lc_classification constraint but then removes
it from the search so that Solr does not throw an error since
"lc_classification" is not a field that our Solr config knows about.
This commit also adds a feature test for these constraint to avoid
a regression bug.

BL-1540: Fix lc_classification constraint broken

---

app/javascript/packs/controllers/query_list_controller.js
app/views/catalog/_show_default.html.erb

Hide Related items heading info until we know there are actually related items.  This also removes it from non-catalog pages

Experiment with hidden headings

---

app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
app/helpers/availability_helper.rb
app/lib/cob_alma/requests.rb
spec/controllers/almaws_controller_spec.rb
spec/helpers/availability_helper_spec.rb
spec/lib/cob_alma/requests_spec.rb

1) Remove Ambler from the list of pickup locations
2) Set masked availability status as "Temporarily unavailable" for all Ambler items
Note -- one of the spec/controllers/almaws_controller_spec.rb tests uses a Ambler item, so this needed to temporarily updated as well.

BL-1557 Make Ambler items unavailable

---

app/controllers/application_controller.rb
app/helpers/blacklight_helper.rb
app/presenters/classification_field_presenter.rb
app/presenters/facet_item_presenter.rb

- Removes spellcheck method we are no longer using
- Updates facet_item presenter - this one fixes hundreds of dep. warnings but needs to be tested thoroughly to make sure it is still working as expected
- Adds search state to url_for method

DEVO-296 Deprecation warnings part 2

---

app/assets/stylesheets/partials/_record_pages.scss
app/helpers/render_constraints_helper.rb
app/views/catalog/_previous_next_doc.html.erb
app/views/catalog/_show_availability_section.html.erb
app/views/catalog/_show_default.html.erb
app/views/catalog/_show_primary_fields.html.erb
app/views/catalog/_show_secondary_fields.html.erb
spec/controllers/lib_guides_controller_spec.rb
spec/views/catalog/_show_availability_section.html.erb_spec.rb
spec/views/catalog/_show_default.html.erb._spec.rb

- Use to_h instead of dig drectly on search_state
- Use search context component
- Use document presenter instead of show presenter
- Use successful instead of success

DEVO-396 Fix deprecation warnings part 3

---

app/helpers/request_helper.rb
app/views/almaws/_resource_sharing_broker_allowed.html.erb
spec/helpers/request_helper_spec.rb

This would be repurpose the Resource Sharing link to map the OpenURL field to a non-OpenURL parameter and leave us the option to pull in any of the other parameters later on if needed. Happy to discuss if this isn't the right approach (see Jira ticket for details).

BL-1579 Update EZBorrow integration for new system

---

.circleci/update-airflow.sh

I missed this when I was updating git repo URLS for that issue that was causing our deployments to fail on QA.
This makes sure we don't run into that issue when we try to do a prod deployment at this step.

Use https for git repo urls.

---

app/models/search_builder.rb
spec/models/search_builder_spec.rb

Opensearch queries just return titles so facetings are not required.
Also disabled faceting for query_list queries because we do not neet facets on those either.

BL-1559: Disable faceting for opensearch queries.

---

app/controllers/concerns/server_errors.rb
spec/controllers/almaws_controller_spec.rb

Apparently passing the full exception to honeybadger should work and that will
be more informative than what we are doing.

Pass full exception to Honeybadger.

---

app/assets/stylesheets/partials/_header.scss
app/assets/stylesheets/partials/_pagination.scss
app/assets/stylesheets/partials/_record_pages.scss
app/assets/stylesheets/partials/_record_tools.scss
app/views/catalog/_previous_next_doc.html.erb
app/views/catalog/_show_main_content.html.erb
app/views/catalog/show.html.erb
app/views/layouts/blacklight.html.erb

So I was looking at BL-1402 to evaluate our options. I _think_ I may have found a solution that does not require a complete redesign, but I'm not sure if the choices that I made are consistent with our best practices. 
What I did: 
- Overrode the default Blacklight view _show_main_content.html.erb: This is the part that I'm most unsure of. Is there a reason why we should not customize this view (vs. others)? Here's the [Blacklight view](https://github.com/projectblacklight/blacklight/blob/master/app/views/catalog/_show_main_content.html.erb). By creating a custom view, we can remove `<%= render 'previous_next_doc' if @search_context && search_session['document_id'] == @document.id %>` and change the conditional logic for the rendering of 'previous_next_doc'. 
- Updated …

Bl 1402 Include export options when directly accessing record page

---

app/views/catalog/_show_primary_fields.html.erb

- Hide both link and <hr> element when no query lists are present

BL-1570 Anchor link updates

---

Gemfile
Gemfile.lock
config/coverband.rb
config/routes.rb

* We'll need to manually make whoever wants to view the coverage analysis and
admin in the production server.

BL-614: Add coverband as code coverage analyzer.

---

.circleci/deploy-prod.sh
.circleci/deploy-qa.sh
.circleci/deploy-stage.sh

Cimg images already have piping installed, so this step isn't needed

Devo 466 remove install

---

app/helpers/request_helper.rb
app/views/catalog/_explanation_div.html.erb
app/views/catalog/_index_availability_section.html.erb
app/views/catalog/_lib_guide_recommender_catalog.html.erb
app/views/catalog/_show_availability_section.html.erb
app/views/lib_guides/index.html.erb
app/views/query_list/_results.html.erb
app/views/users/_user_fines.html.erb
app/views/users/_user_holds.html.erb
app/views/users/_user_loans.html.erb
spec/helpers/application_helper_spec.rb

Stimulus 3 has added a deprecation warning to data-target attributes because they are going away in future versions of stimulus.

Fix stimulus-3 deprecation warnings

---

app/views/catalog/_previous_next_doc.html.erb

Anchored link bug with JS occurs only when "back to search" and "start over" buttons are present, but not previous-next navigation. I think the issue may be due to a mistake in my logic for https://github.com/tulibraries/tul_cob/pull/2936.

BL-1570 Anchored link bug caused by nav-tools logic

---

app/assets/javascripts/book_covers.js

Noticed this when I was working on https://github.com/tulibraries/tul_cob/pull/3000

Fix OCLC query error for Google Books

---

app/controllers/application_controller.rb

We'll want to dump cache that results from error recovery because it's not useful.

BL-1604: delete cache that results from a bad request.

---

app/models/user.rb
config/locales/en.yml
spec/features/online_payment_spec.rb
spec/models/user_spec.rb

Remove consideration of a user's group in deciding if they can pay
online.
Only consider that they have a fine and the they are authenticated.

Allow any authenticated user to pay online.

---

spec/fixtures/features.yml
spec/fixtures/marc_fixture_4_marc.xml

- Some of our test cases for record page feature tests did not include a title.  This throws an error during the cob_index ingest process.  
- This adds titles to the records throwing errors to avoid this when running tests

Cleanup fixtures

---

app/controllers/concerns/quik_pay.rb
spec/controllers/quik_pay_spec.rb

We need to convert alma values to a float in order not to lose
precision.

Fix lose precision when convert from dollars to cents.

---

Gemfile
Gemfile.lock

- Nokogiri was installing with  nokogiri (1.13.1-x86_64-darwin), this was causing the playbook to fail.  This updates it to just use nokogiri (1.13.1) because that is what the playbook is looking for.

Update nokogiri to not use native extension

---

.docker/app/Dockerfile.prod
Makefile
package.json
yarn.lock

- Removes the default gem directory (We don't use those versions and they are causing the trivy scans to fail)
- Updates trivy command for Makefile
- Fixes js vulnerability

Fix trivy issues

---

.docker/app/Dockerfile.prod

*  This is no longer needed because these updates have been added to the base image

Dockerfile update

---

spec/features/record_page_fields_spec.rb
spec/fixtures/features.yml

- Mapping for 588a is being removed from cob_index, so the related tests also need to be removed.

BL-1624 Notes mapping

---

Gemfile.lock
app/controllers/catalog_controller.rb
spec/features/indices_spec.rb
spec/features/record_page_fields_spec.rb

- Adds a facet for collections
- Updates the mapping for both the facet and display field to use collection_ms so that we can create a searchable link on the record page.

BL-251 Collection Name facet

---

app/controllers/catalog_controller.rb
app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

- Moves the collection field to the primary field section of the record page
- Adds a new generic method for all _ms fields on record pages (collection, donor_info, genre)

BL-1615 Collection display field

---

app/assets/javascripts/availability.js
app/assets/stylesheets/partials/_availability.scss
app/helpers/availability_helper.rb
app/views/almaws/item.html.erb
app/views/catalog/_physical_availability_card.html.erb
spec/features/record_page_fields_spec.rb
spec/helpers/availability_helper_spec.rb
spec/javascript/packs/controllers/availability_controller.spec.js

Updates in this PR include: 
- Moving the placement of the holdings summary to appear under library/location rather than to the right
- Adding table structure and labels for column sections: “Call Number,” “Description,” “Type”, and “Availability”
- Removing prepended labels from item data (ex. "Description: ")
- Modifying JS long list truncation to work with new structure
- Adding some CSS to flatten table structure in mobile view 
This changes do not include broader styling updates (ex. color, fonts) yet.

BL-1617 Update availability display layout to table for physical items

---

app/assets/stylesheets/partials/_availability.scss
app/helpers/catalog_helper.rb
app/views/catalog/_online_availability_button.html.erb
app/views/primo_central/_direct_link.html.erb
app/views/primo_central/_show_availability_section.html.erb
spec/helpers/catalog_helper_spec.rb

- Removes borders from search results and record pages
- Coverage statement appears first and is the link for items that have it.

BL-1638 Online Availability

---

app/controllers/users/omniauth_callbacks_controller.rb
spec/controllers/users/omniauth_callback_controller_spec.rb

* Fixes redirects back to searched document after authentication via
SAML.
* Remove debugging code.
* Adds controller spec for SAML auth.

BL-1587: Fix regression, no redirect for SAML auth.

---

app/helpers/availability_helper.rb
spec/helpers/availability_helper_spec.rb

- Adds a few more items to the non-circulations status.  As a result of this, I broke this out into a new method and added some specs
- Cleaned up the display for non-circulating items

BL-818 Non-circulating items

---

app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js

We've decided that "Check Availability" as a label introduced too much ambiguity for our users.

BL-1639 Change Check Availability back to Available label

---

app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

- The subtitle subfield was renamed to coverage_statement in cob_index.  This adds that change on the app side for helper methods.

BL-300 Electronic resources updates

---

app/assets/stylesheets/partials/_availability.scss

- Adding the padding to last-child makes the info-icon get bigger.
- This adds the padding to the td div instead

BL-1637 Adjust padding

---

app/assets/stylesheets/partials/_availability.scss
app/views/catalog/_hathitrust_button.html.erb
app/views/catalog/_online_availability.html.erb
app/views/catalog/_online_availability_button.html.erb

This PR fixes this double gray line issue:

BL-1638 Adjust online availability border styling to avoid double line in search results

---

app/helpers/request_helper.rb
app/views/catalog/_index_availability_section.html.erb
app/views/catalog/_show_availability_section.html.erb

When logged in, the search results request button still had the class "record-page-request-btn" due to dual use of request_modal helper method. I've updated this method so that it can have different classes on record page and search results view pages.

BL-1621 Fix Google Analytics event tracking for search results request button

---

.docker/app/Dockerfile.prod
Gemfile.lock
Makefile
README.md

This adds m1 platform specific changes to allow local deevelopment using
m1 computer.  This does not change how application works for non m1 macs
etc.
This fixes m1 issues for building production image using
`make build` and `make run`
This also fixes issue for regular local dev using `bundle install`
This does not fix issue for docker-compose in local development.  That
is still a TODO.

Allow local development using m1 mac.

---

.docker/app/Dockerfile.prod
Gemfile
Gemfile.lock
Makefile

* Updates rails version to fix security scan
* Updates the way we pass in config for alma/bento 
* Updates bento_search gem to pull from ruby gems rather than an outdated branch

fix build and scan errors related to Rails upgrade

---

.dockerignore
.gitignore

Avoid committing or adding the rails docker image directly.

Ignore config/master.key for security.

---

app/helpers/availability_helper.rb
spec/helpers/availability_helper_spec.rb

In anticipation of the arrival of 12” ASRS bins, we are disabling the storage request form for MAIN storage and defaulting the standard "Temporarily unavailable" display for that location.

BL-1649 Remove link to recall items from Main Storage

---

config/initializers/new_framework_defaults_6_1.rb

Now that the rest of the changes have been pushed to production, we can add the configurations that are not backwards compatible.  This includes:
Rails.application.config.action_dispatch.cookies_same_site_protection = :lax
Rails.application.config.action_controller.urlsafe_csrf_tokens = true
Rails.application.config.active_record.legacy_connection_handling = false

DEVO-554 Rails config changes for 6.1

---

app/models/concerns/blacklight/document/email.rb
app/models/concerns/blacklight/document/sms.rb

The blacklight methods to_email_text and to_sms_text take an optional argument.  The way our methods were written, an argument was not allowed, so when we tried to pass one it failed.  This just adds a default argument to both methods to match what the blacklight methods have.
Emails are still sending correctly, but I am adding the optional argument to that method so that we match the format that blacklight is using.

Fixes bug with sending sms messages

---

Gemfile.lock

QA broke after I merged this.  I tried rebooting the linode, restarting httpd, and restarting passenger but it is still down.  Reverting this to see if that resolves it.
Reverts tulibraries/tul_cob#3292

Revert "Bump blacklight-marc from 7.1.1 to 8.0.0"

---

Gemfile.lock
app/models/solr_document.rb

It looks like this module was renamed about six months ago.  Both the old and new names work for me locally, but I am hoping updating it will fix the issue on QA that happened yesterday.  The error showed:
uninitialized constant Blacklight::Solr::Document::Marc
Did you mean? Blacklight::Marc

Update blacklight-marc to 8.0.0

---

app/helpers/advanced_helper.rb

There have been times when users enter a single quotation mark in an advanced search term and forget to close it.  This method checks that there is an even number of quotation marks and removes any stray quotation marks.

BL-1675 Return adv. queries with an even number of quotation marks

---

app/controllers/web_content_controller.rb

Currently, if a user has search results from a catalog title advanced search and then clicks on the web content tab, they get an unsupported query error.  Adding the advanced solr parameters to the title search field for web content allows the user to go through.

BL-1676 Add advanced solr params to web content

---

app/models/search_builder.rb
spec/models/search_builder_spec.rb

There are times when a user accidentally uses a single quote when searching for a term.  The way our code was previously written, if a search term included any number of quotation marks, it returns the search term value.  
So if a user searched for `"George Washington",` it would search for that term with the existing quotes.  If a user selects the is(exact) operator and does not use quotes, the method adds them to the term.
This updates the code to remove any single quotes from a search term, and then puts quotes around the search term so that the is(exact) precision is applied.
So, `"George Washington` would become `"George Washington"`

BL-1675 Update advanced search to remove single quotes from queries

---

.circleci/config.yml
Gemfile
Gemfile.lock
Makefile
README.md
spec/features/facets_spec.rb
spec/rails_helper.rb
spec/spec_helper.rb

We have some features that require JavaScript to test them properly.
However, JavaScript testing frameworks are not easy to manage and
understand when you are not constantly writing JavaScript.
A different approach we can take is to test these features via a web
browser interaction using a feature test that interacts with the codes
behavior.
This should suffice to test features in our site that require
JavaScript.
This change updates our code to:
* Add dependencies to the test and developer environment to enable
JavaScript enabled feature specs.
* Adds an example test that test that clicking on facet headers opens
the closed facets.

Allow adding javascript enabled feature specs.

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

There are some instances where the date_added_facet includes a 0 in the array.  We want to remove any zeroe that are present in the array so that we can parse the correct date.

BL-1692 Update to query_list footer method

---

app/views/application/_navbar.html.erb
app/views/shared/_header_navbar.html.erb

There was a border line in the header between the search section and navbar that did not go the full width of the page.

Fix border width for navbar

---

Gemfile.lock
app/models/blacklight/primo_central/search_builder_behavior.rb
spec/models/primo_search_builder_spec.rb

Updates the primo search builder to process the pcAvailability user
params and adds it to the primo query.

BL-1715: Use pcAvailability if given in user params.

---

app/assets/javascripts/application.js
app/assets/stylesheets/partials/_index_results.scss
app/views/catalog/_index_default.html.erb

* Only displays button for longer-text summaries
* Adds a "less" link to collapse preview
* Adjusts css to align with the document header

BL-1713 Summary preview updates

---

app/assets/stylesheets/partials/_bento.scss
app/views/bento_search/_std_item.html.erb
app/views/layouts/_bento_box_wrapper.html.erb
app/views/layouts/blacklight.html.erb
app/views/search/_bento_results.html.erb
app/views/search/index.html.erb

- Updated Bootstrap layout from card columns to rows with columns
- "No Results" are now pushed to bottom of display
- Adjusted width of bento container and other minor padding/margin changes

BL-921 Update bento layout to accommodate Guides box

---

app/controllers/search_controller.rb
app/helpers/search_helper.rb
app/search_engines/bento_search/lib_guides_engine.rb
app/views/search/_bento_results.html.erb

- Matches guide header link to "View all" link
- Switches databases and journals in bento order
- Remove dynamic "no results" ordering that I had tried in a previous PR

BL-921 Update guides header link and reorder bento

---

app/assets/stylesheets/partials/_index_results.scss
app/controllers/primo_central_controller.rb
app/helpers/application_helper.rb
app/presenters/show_presenter.rb
spec/helpers/application_helper_spec.rb

* Remove responsibility_display from secondary fields on full record pages
* Updates multiple authors in articles to display on separate lines (this matches what we do for catalog results)

BL-1758 Author/responsibility updates

---

app/assets/stylesheets/partials/_index_results.scss
app/views/almaws/item.html.erb
app/views/catalog/_explanation_div.html.erb
app/views/catalog/_hathitrust_button.html.erb
app/views/catalog/_index_summary_field.html.erb
app/views/catalog/_online_availability_button.html.erb
app/views/catalog/_physical_availability_card.html.erb
app/views/catalog/_purchase_order_anonymous_button.html.erb
app/views/catalog/_show_fields.html.erb
app/views/primo_central/_online_button.html.erb
spec/features/axe_spec.rb

I updated the spec to adhere to WCAG2 Level A and AA, which is TU's standard. I also made the following changes based on failing tests:
- I fixed ul element errors resulting in invalid html structure. 
- The aria-expanded attribute was in the wrong place for some buttons, so I moved the attribute from <span> to <button> whichs match other buttons that were correctly tagged. 
- The id "error-message" is not matched to unique element on page in some scenarios, so I updated to class instead. 
- I updated the styling of explanation box to better distinguish the embedded link. 
There still is one outstanding failure related to https://dequeuniversity.com/rules/axe/4.7/link-in-text-block, which I will need to follow up on design options for. Because of this, I'm leaving the "xit" skips in place …

Update axe_spec requirements and make needed code changes

---

config/environments/production.rb

Allow up to one minute for mails to deliver via smtp.
This is an attempt to fix an increase in mail timeout errors.

Increase mailer timeout.

---

Gemfile
Gemfile.lock

Now that we are not on CentOS 7 we no longer need to pin skylight to an older version.  I have added the necessary env vars in vault, so I am hoping this is all that is needed to get it running in kubernetes.

DEVO-807 Update skylight version

---

app/models/blacklight/primo_central/document.rb

If something goes wrong getting a libkey, send an error to Honeybadger logs.

Ref: Bl-1783: Alert honeybadger on libkey error

---

spec/rails_helper.rb

Version 4.12.0 of the seleniuv-webdriver has an update that is breaking one of our tests.  The capabilities keyword has been changed to options instead.  See further details here: https://stackoverflow.com/questions/77045183/rails-7-capybara-with-selenium-webdrivers-fails-unknown-keyword-capabilitie

Update the keyword for capabilities

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

We received a honey badger error this week due to the fact that an article creator has a null value.  Refactored the helper method to delete null values.

BL-1809 Don't include null values in article creator links

---

.circleci/config.yml
Gemfile
Gemfile.lock

We keep having issues with tests on main failing.  This updates the seleniuv-webdriver to the last passing version.  It also changes the cache versions to something that I didn't use when I was trying to fix the selenium issue earlier this week.

Update selenium webdriver gem

---

app/models/blacklight/primo_central/document.rb
spec/models/primo_central_document_spec.rb

libproxy section to links is getting removed by our k8 instance.
IST is looking into it.
In the meantime we can just add it ourselves and remove this once they fix the root cause.

BL-1813: Temporarily add libproxy to get_it link.

---

app/models/blacklight/primo_central/document.rb
spec/models/primo_central_document_spec.rb

Working on bl-1813 I realized that whe URLs are proxied that url_query method is not working.
This change fixes that issue.

BL-1814: Fix url_query method in primo document model.

---

Gemfile.lock

- Addresses deploy failure when we upgraded the Faraday gem

Rollback base64 from 0.2.0 to 0.1.1

---

.circleci/config.yml
.docker/app/Dockerfile.prod
.docker/ci-app/Dockerfile.ci

Uses 3.1.3-alpine to get libssl1.1. This is an old version and should be updated in future. 3.1.4-alpine uses libssl3. 
Current rails dependencies (bootsnap) require this older version.

Alpine version docker build

---

app/helpers/application_helper.rb

This code was removed in https://github.com/tulibraries/tul_cob/pull/4043 which broke the RIS export for articles.

BL-1828 Fix RIS export in articles

---

.docker/app/Dockerfile.prod
Makefile

I will follow up this PR with one to charts to add the environment variable there.

BL-1840 Make web_concurrency configurable

---

app/controllers/catalog_controller.rb
config/environments/development.rb
config/environments/production.rb

Actions fail when cached using memcached because of forgery protection.
Disabling the forgery proection for index actions fixes issue.
Also moves cached pages to temp folder.
Also removes useless expire config for cached pages.

Fix cached actions.

---

app/search_engines/bento_search/cdm_engine.rb

* Gets headers of images to check if they are available (faster than pulling down whole image)
* checks if images are available concurrently via threading.
* caches cdm_collections_api_response value (which is static)

Make CDM a bit faster

---

app/search_engines/bento_search/cdm_engine.rb

If we include this notification, we will get lots of errors for expected behavior (ex. when there isn't a "full_image_url" and switch to using a "thumbnail_image_url")

Don't notify Honeybadger when a CDM image isn't available

---

app/views/layouts/blacklight.html.erb

I have noticed in the logs that we have a significant number of get requests for stylesheets/preload.css that are erroring out because that file doesn't exist. Removing rel=preload removes the error for me locally.

Remove preload tag

---

app/views/catalog/_sort_and_per_page.html.erb

It looks like we are already using the Blacklight components for sort and pagination.  We were overriding a related Blacklight partial that I think we can remove.  They made some updates that now render the content the same way that we were rendering it.

BL-1873 Response sort and pagination

---

app/controllers/almaws_controller.rb
app/helpers/almaws_helper.rb
app/lib/cob_alma/requests.rb

Updates include: 
- Moved bib items api call to private method and added low-level cache with duration of 30 seconds -- We want close to real-time availability for item and request views, but my hope is that this might help in cases where users view item availability panels and request modal in quick succession. We can remove the cache, though, if needed. 
- Removed code that it is no longer actively used, primarily related to item display pagination (not active)
- Simplified and fixed some issues with how we were using the methods related to Alma::BibItem and Alma::BibItemSet 
- Switched to using @document for data that can be pulled from the bibliographic record (@books, @author)
- Reordered and grouped variables according to their function
This should also fix BL-1825.

BL-1866 Clean up almaws controller and add low-level caching

---

app/controllers/catalog_controller.rb
app/controllers/primo_central_controller.rb
app/models/blacklight/primo_central/repository.rb
app/models/solr_document.rb
config/application.rb
lib/article_not_found.rb
spec/controllers/catalog_controller_spec.rb
spec/controllers/primo_central_controller_spec.rb
spec/models/solr_document_spec.rb

The function of validating if the record is suppressed or nil can happen without overriding the blacklight catatalog#show method.

Remove unnecessary catalog#show override.

---

config/oclc.yml

OCLC has reported that there is an API issue with the redirect from http to https currently. I haven't tested this locally, but I'd like to push this update to QA to see if it fixes the issues with citations.

Update OCLC API endpoint to HTTPS

---

app/controllers/catalog_controller.rb
app/controllers/query_list_controller.rb

This reverts commit 0dfd445650a8b53f893185ab6380833f14606f94.

Revert "Bl-1848: Add action caching. (#4426)"

---

app/models/request_data.rb
spec/models/request_data_spec.rb

Booking request form is broken. It appears that the logic for the booking pickup locations in Alma has changed, so I've updated our logic accordingly.
There is some cleanup to do related to the library name lookup, but I will need to work on some broader refactoring to do that.

BL-1882 Fix booking request pickup locations

---

app/controllers/almaws_controller.rb
app/helpers/request_helper.rb
app/models/request_confirmation.rb
config/locales/en.yml
spec/fixtures/requests/request_sent_from_ambler.json
spec/fixtures/requests/request_sent_from_bookbot.json
spec/fixtures/requests/request_sent_from_japan.json
spec/fixtures/requests/request_sent_from_main.json
spec/helpers/request_helper_spec.rb
spec/models/request_confirmation_spec.rb
spec/spec_helper.rb

- Added new RequestConfirmation model to determine delivery estimate from request submission API response
- Updated message text accordingly (to be reviewed with Justin), removing old helper method in the process
- Added correpsonding spec and fixtures
As always, I welcome any feedback and suggestions to improve this code!

BL-1865 Add time estimates to request confirmation message

---

app/models/request_confirmation.rb
app/models/request_delivery_estimate.rb
config/locales/en.yml
spec/models/request_confirmation_spec.rb
spec/models/request_delivery_estimate_spec.rb

This HTML is coming through as escaped, and after working on it locally for a bit, I'm still working through the best way to fix this. For now, I'm going to remove this markup for now, so that we can move forward in production with the plain text version.

BL-1865 Remove HTML markup for confirmation messages 

---

.circleci/config.yml

Task failing because it is trying to use the wrong version of python.

DEVO-1105: Update catalog on deployment.

---

app/models/blacklight/primo_central/response.rb

This error has been thrown a lot lately, usually when a user is trying to access a page that doesn't exist:
NoMethodError: undefined method `min' for nil
https://librarysearch.temple.edu/articles/login is an example
This just handles cases where range is nil so that an error isn't thrown.  It seems like this error is being caused by bots, but it doesn't hurt to handle it.

BL-1898 Fix honeybadger no_method error for primo_central#show

---

config/application.rb

A new Rails 7 security feature breaks logouts because devise trys to redirect user to fim.temple.edu in produciton on logoout.
We can monkey patch devise or we can disable the feature.
For now I've disabled the feature.
I tried adding an exception for fim.temple.edu, bu that didn't work.

BL-1904: Fix error on logout

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb

The clear caches endpoint does not need forgery protection.
Fixes airflow task not able to clear caches due to forgery protection of endpoint.

BL-1878: Disable forgery protection for clear caches endpoint.

---

app/assets/stylesheets/tucob.scss

This should be double-checked after merge. It was not working locally with this change, but after reverting subsequent other changes that also did not work, it just started working.

BL-1919-fix-multi-subject-links-when-hovered-over

---

config/honeybadger.yml

Honeybadger documentation says the gem will ignore any exceptions matching the string, regex or class that you add to exceptions.ignore. I tried adding this as a string, but it didn't work.  Now I'm trying as regex to see if that gives the results we want.

Bl 1911 try ignoring by regex

---

app/components/facet_item_pivot_component.rb
app/views/almaws/_asrs_request_form.html.erb
app/views/almaws/_booking_request_form.html.erb

Syntax for data attributes needed a fix. Also adds other files without the -bs- in the attribute.

Bootstrap 5 HTML Objects

---

.gitignore
app/models/search_builder.rb
spec/features/indices_spec.rb
spec/models/search_builder_spec.rb

I also refactored the process_is method to be a case statement and when I did that the is (exact) searches started working again in the advanced search.

BL-1855 Convert single quotes to double quotes for exact searches

---

config/initializers/primo.rb

When retries are enabled we don't want to make the timeouts too long because they add up.

Set default primo timeout to 3 seconds.

---

app/models/blacklight/primo_central/document.rb

Use the @doi value as the cache key, instead

Don't save copies of the access_token to a cache.

---

app/controllers/concerns/server_errors.rb
app/controllers/primo_central_controller.rb

Give user a useful error befinstead of blank 403 page.

Use recaptcha specific error for verification errors.

---

app/controllers/concerns/server_errors.rb
spec/controllers/primo_central_controller_spec.rb

Use 403 status when verify_captcha fails.

---

app/controllers/catalog_controller.rb

There have been some Honeybadger errors thrown when users are switching to an everything search after an advanced catalog search. This fixes it so that the search won't error out.

Fixes a bug when params["operator"] is nil

---

app/controllers/primo_central_controller.rb

The Google v3 recaptcha uses float values.  This will resolves some Honeybadger errors that we have been getting.

Convert recaptcha value to a float

---

app/helpers/almaws_helper.rb
config/locales/en.yml
spec/helpers/almaws_helper_spec.rb

This is a temporary workaround to be tested while ongoing work to completely remove the asrs pickup location select list on hold requests is finished.

BL-1868-combine-request-item-from-book-bot-and-request-item-for-pickup-dropdowns

---

Documentation/essential_packages.txt
Documentation/on-headers-CVE-2025-7339
package.json

- Packages are dependent on on-headers 1.0.2, so pinning its version to 1.1.0 is not sufficient to pass vulnerabilty scans. Will need to waive this package

CVE-2025-7338 Add on-headers to essential packages

---

.rubocop.yml
app/components/blacklight/constraints_component.html.erb
app/components/blacklight/start_over_button_component.rb
app/views/catalog/_constraints.html.erb
app/views/catalog/_facets.html.erb
app/views/catalog/_previous_next_doc.html.erb

Also adds the constraints component because that initializes the start over button component.  The component has to be called in slightly different ways on the search results/record page due to the context that it is in.

BL-1875 Add start over button component
