- Gemfile
- Gemfile.lock
- README.md
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_account_link.html.erb
- app/views/users/account.html.erb
- app/views/users/fines.html.erb
- app/views/users/holds.html.erb
- app/views/users/loans.html.erb
Issue #COB-81
- Updated method calls
- Temporary instructions to add Alma_ID to users
> Integrate with Alma Ruby API

- Gemfile.lock
- app/assets/stylesheets/users.scss
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/loans.html.erb
- app/views/users/renew.html.erb
- app/views/users/renew.js.erb
- config/routes.rb
- lib/alma_utils.rb
- spec/controllers/users_controller_spec.rb
- spec/views/users/renew.html.erb_spec.rb
Issue #COB-86
Adds Renew loan capability
> Integrate user renew loan

- app/assets/stylesheets/application.css
- app/assets/stylesheets/partials/_colors.scss
- app/assets/stylesheets/partials/_facets.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_pagination.scss
- app/assets/stylesheets/partials/_vars.scss
changed css hex colors to variables in sass, defined in partials/_vars.scss.
> Variablized colors in Sass.

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/availability.js
- app/models/traject_indexer.rb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_show_default.html.erb
- config/alma.yml.example
- config/routes.rb
Includes a fork of the Blacklight Alma gem into our app.
Includes marc indexer that can be used with traject cli.
> Include the Blacklight Alma Gem

- app/controllers/users_controller.rb
- app/models/user.rb
- config/routes.rb
- spec/models/user_spec.rb
> Add user controller with fines, loans and requests data

- app/assets/javascripts/application.js
- app/assets/stylesheets/partials/_users.scss
- app/assets/stylesheets/partials/_vars.scss
- app/views/users/account.html.erb
Created a select all option for renewals and moved submit button to below the list.
> Selectallcheckbox

- app/assets/javascripts/application.js
- app/assets/stylesheets/partials/_users.scss
- app/assets/stylesheets/partials/_vars.scss
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/models/user.rb
- app/views/users/_user_info.html.erb
- app/views/users/_user_loans.html.erb
- app/views/users/renew_selected.js.erb
- spec/helpers/users_helper_spec.rb
Added the non-renewability and to user account, with js routine to disable submit button until at least one loan is selected for renewal.
> Include renewability data

- app/views/users/_user_fines.html.erb
- app/views/users/_user_holds.html.erb
- app/views/users/_user_info.html.erb
- app/views/users/_user_loans.html.erb
- app/views/users/renew_selected.js.erb
Textual changes based on user-feedback sessions.
> Made textual changes related to sub-task: COB-117.

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/controllers/catalog_controller.rb
- app/controllers/saved_searches_controller.rb
- app/controllers/search_history_controller.rb
- app/models/search_builder.rb
- app/views/catalog/_search_form.html.erb
- config/routes.rb
> Install Blacklight_Advanced_Search Gem

- config/application.rb
- config/deploy_to.yml.example
Sets `config.relative_url_root` if the config file exists.
> Optional, configurable relative_url_root

- README.md
This fixes the issues I found 7/5.
> Update README.md file to include tar command and fix spelling

- app/controllers/catalog_controller.rb
- app/models/traject_indexer.rb
- spec/features/record_page_fields_spec.rb
- spec/fixtures/features.yml
- spec/fixtures/marc_fixture.xml
Added logic and specs for imprint, date, and date_copyright fields
- changed imprint label to Published
- added logic to show pub_date and date_copyright fields depending on indicator 2 value
> 130 imprint and date logic

- app/controllers/catalog_controller.rb
Now reflects the order indicated on the chart
> Update the order of record page fields 

- app/controllers/catalog_controller.rb
- app/models/traject_indexer.rb
Creator links to search results
> BL-26 Add link from creator_display_field

- app/assets/stylesheets/tucob.css.erb
- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/views/catalog/_show_default.html.erb
- spec/features/record_page_fields_spec.rb
- spec/fixtures/features.yml
- spec/fixtures/marc_fixture.xml
Updates to record page display
> BL-23 Helper methods for displaying links and lists

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/models/traject_indexer.rb
- spec/features/record_page_fields_spec.rb
- spec/fixtures/features.yml
> Subject field updates

- app/controllers/catalog_controller.rb
> BL-43 Change pub_no label

- app/controllers/catalog_controller.rb
- spec/features/indices_spec.rb
Added fields and specs for index page
> Bl 30 index page display

- Procfile
- app/controllers/catalog_controller.rb
- app/models/traject_indexer.rb
- lib/traject/macros/marc_format_classifier.rb
- lib/translation_maps/marc_genre_007.yaml
- lib/translation_maps/marc_genre_leader.yaml
Addresses Issue #BL-5, sub issues #BL-41, #BL-48 #BL-39.
#BL-39 Completely removed code that generated Online and Print facets
#BL-48 Enabled Format Facet
> BL-5 resource type format mappings

- app/controllers/catalog_controller.rb
- spec/features/indices_spec.rb
- Issue #BL-3
- Availability and Location are not implemented, and commented out in
the spec
> BL-3 Reorder and update facet column

- app/assets/stylesheets/tucob.css.erb
- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/models/traject_indexer.rb
- app/views/catalog/_show_default.html.erb
- spec/features/indices_spec.rb
- spec/features/record_page_fields_spec.rb
- spec/fixtures/features.yml
- spec/fixtures/marc_fixture.xml
BL-20 Add subject_600 subfield v
BL-26 Add creator search field for linked search
BL-23 Add helper method to all notes fields
BL-48 Update css to display whole creator
BL-48 Update to include all longer labels
> Addresses multiple JIRA issues around display.

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/models/traject_indexer.rb
- spec/features/record_page_fields_spec.rb
- spec/fixtures/features.yml
- spec/fixtures/marc_fixture.xml
> Bl 6 updates for 856 fields

- Gemfile
- Gemfile.lock
- app/assets/javascripts/availability.js
- app/controllers/catalog_controller.rb
- app/helpers/blacklight_alma_helper.rb
- app/helpers/catalog_helper.rb
- app/models/solr_document.rb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_show_default.html.erb
- config/environments/development.rb
- config/initializers/alma.rb
- spec/features/availability_response_spec.rb
- spec/fixtures/availability_response.xml
- spec/spec_helper.rb
Realtime availability seems to be working in dev environment and all specs are passing.
> Bl 60 fix realtime availability

- app/models/traject_indexer.rb
- Archival -> Archival Material
- Conference -> Conference Proceedings
Issue #BL-41: See Minor Issues comment
> Replace archival conference formats

- app/assets/stylesheets/tucob.css.erb
- spec/features/indices_spec.rb
Adds styles and specs for availability buttons.
> Bl 66 add buttons for availability

- app/assets/stylesheets/tucob.css.erb
- app/helpers/application_helper.rb
- app/views/catalog/_show_default.html.erb
Shows availability under the title on the record page.
> Bl 53 show physical availability

- Gemfile.lock
- app/models/traject_indexer.rb
- spec/features/indices_spec.rb
Update traject indexer and specs for library facet.
> New locations

- app/assets/stylesheets/tucob.css.erb
- app/views/catalog/_show_default.html.erb
I noticed that the alignment was off in the dt and dd elements below availability.  This fixes that issue.
> BL-53 Update css to keep dt and dd in alignment

- Gemfile.lock
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_search_results.html.erb
Created a search_results partial to use rails url_helper for alma availability route instead of hard coding route in javascript.
> Route for production

- lib/tasks/oaiharvest.rake
- Don't need a progress bar when running as automated task
> Remove progress bar

- app/views/catalog/_search_form.html.erb
Label change for advanced search.
> BL-36 Change label to advance search

- app/models/traject_indexer.rb
BL-61 Added additional logic for indicator values in the availability facet.
> Add indicator2 exception logic

- app/assets/stylesheets/tucob.css.erb
- app/controllers/catalog_controller.rb
- app/helpers/advanced_helper.rb
- app/views/advanced/_advanced_search_facets.html.erb
- app/views/advanced/_advanced_search_fields.html.erb
- app/views/advanced/_advanced_search_form.html.erb
- spec/features/advanced_search.rb
Adds search fields and booleans for the advanced search field.
> Bl 96 customize advanced search

- app/controllers/catalog_controller.rb
Renamed library facet in the advanced search config
> Update library facet for advanced search

- README.md
- lib/tasks/server.rake
This is super useful for devs working on this to get up to speed quickly.
> Document the working rake server task

- .travis.yml
Don't notify on pull requests?
> Quieter travis?

- app/controllers/catalog_controller.rb
- app/views/advanced/_advanced_search_help.html.erb
- app/views/advanced/index.html.erb
- app/views/blacklight_advanced_search/_facet_limit.html.erb
Addresses several issues relating to advanced search:
- BL-135 Remove facet limits from search results
- BL-138 Edit dropdown for simple search
- BL-131 Edit text in search tips
> Advanced search config

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/models/traject_indexer.rb
- spec/helpers/application_helper_spec.rb
BL-153 and BL-145 Use enriched bib records rather than the alma api for electronic resources
> Bl 153 use enriched bibs

- Gemfile.lock
This updates the version of blacklight_alma that tul_cob will use.
> Update Gemfile.lock for updated alma_blacklight

- Gemfile
- Gemfile.lock
- config/application.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
Replace all references to FactoryGirl with FacotryBot as the upstream gem name changed
> Factory Girl tranform into... Factory Bot

- app/helpers/blacklight_alma_helper.rb
- spec/helpers/blacklight_alma_helper_spec.rb
This commit adds some tests to a custom override of
`alma_service_type_for_fulfillment_url`
> Add tests to an overriding function.

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/models/traject_indexer.rb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_index_default.html.erb
- spec/features/record_page_fields_spec.rb
- spec/features/searches_spec.rb
- spec/helpers/application_helper_spec.rb
BL-162 Links coming from the alma api and links coming from Marc 856 fields are merged into one field.
> BL-162 Links from 856 field and alma api are merged into one list

- app/controllers/catalog_controller.rb
- app/views/catalog/_show_availability_section.html.erb
> BL-169 Update availability display for online items

- app/assets/stylesheets/tucob.css.erb
- app/helpers/application_helper.rb
- app/views/catalog/_show_default.html.erb
BL-174 Makes changes requested during testing
- BL-182 Adjust logic for button so that it displays when available at multiple libraries
- BL-181 Change the base url for accessing aeon
> Refine aeon

- app/controllers/application_controller.rb
- app/controllers/catalog_controller.rb
- app/views/users/_account_link.html.erb
- sample_data/.gitignore
- spec/features/basic_page_elements_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
Fixes path to account when logged in.
> Link to lib account only shows when logged in.

- Gemfile
- Gemfile.lock
- README.md
- app/assets/stylesheets/tucob.css.erb
- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/users/index.html.erb
- config/application.rb
- config/deploy_to.yml
- config/routes.rb
- db/migrate/20171113193924_add_admin_to_users.rb
- db/schema.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/users.rb
- spec/spec_helper.rb
Rebase issues with PR #147 and #148
Resubmission for issue #BL-178
> Add masquerade functionality (Attempt 3)

- app/views/layouts/blacklight.html.erb
In this case at least. Otherwise it asks, is this expression defined.
> && Needs Parens

- app/assets/stylesheets/tucob.css.erb
- app/helpers/application_helper.rb
- app/views/catalog/_show_default.html.erb
> BL-92 Adjust styling and remove br to get rid of line break issue

- app/assets/stylesheets/tucob.css.erb
- Makes standard width 100 pixels (height adjusted accordingly)
> Adjust book cover thumbnail size

- app/models/traject_indexer.rb
BL-4 Update subject_region_facet mappings 
- Use the traject macro marc_geo_facet
> Bl 4 subject facets

- app/assets/stylesheets/tucob.css.erb
- app/helpers/application_helper.rb
- app/views/catalog/_show_availability_section.html.erb
- app/views/catalog/_show_default.html.erb
BL-182 Aeon updates
- refine helper method when item exists in multiple libraries
- move button within availability panel
-change styles and text according to jira issue
> Aeon updates

- app/assets/stylesheets/tucob.css.erb
Adjust width of container and image to be a max of 100 pixels
> Adjust css for width of 100px

- app/controllers/catalog_controller.rb
BL-243 Standardizes the view of facet lists to only show 10
> BL-243 Limit facet lists to 10

- .rubocop.yml
- .travis.yml
- Gemfile
- app/helpers/application_helper.rb
- app/helpers/blacklight_alma_helper.rb
- app/helpers/catalog_helper.rb
- app/search_engines/bento_search/blacklight_engine.rb
- config/routes.rb
- db/migrate/20171113193924_add_admin_to_users.rb
- lib/tasks/tulsearch.rake
- lib/traject/macros/custom.rb
- lib/traject/macros/marc_format_classifier.rb
- spec/spec_helper.rb
Pedantic rule obsessed justice that is
> Bring this code to justice

- lib/traject/macros/custom.rb
> Bl 192 reorder electronic resources by date coverage

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_user_info.html.erb
- config/initializers/devise.rb
- db/migrate/20180109214210_add_name_to_users.rb
- db/schema.rb
- lib/traject/macros/custom.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
> Bl 226 fix my library account issues

- app/views/catalog/_home_text.html.erb
- config/locales/blacklight.en.yml
Made changes to size and content of the text.  Also moved the content to blacklight.en.yml file in config/locales
> Update home page text and move into blacklight.en.yml file

- app/assets/stylesheets/tucob.css.erb
- app/views/catalog/_citation.html.erb
Requested by Emily: Jira #BL-240
(also added missing Close button to modal)
> Override blacklight citation modal tool in views/catalog.

- app/views/catalog/_show_availability_section.html.erb
- app/views/catalog/_show_default.html.erb
- spec/views/catalog/_show_default.html.erb._spec.rb
Add book cover images to record show pages
> Bl 278 book covers

- app/controllers/catalog_controller.rb
> Remove title_statment boosters from search cofig

- app/models/traject_indexer.rb
> Remove duplicate creator_t configuration.

- .docker/app/Dockerfile
- .docker/solr/Dockerfile
- .dockerignore
- bin/app-start.rb
- cli.docker-compose.yml
- docker-compose.yml
- lib/tasks/docker.rb
- sp.docker-compose.yml
REF BL-173
Description
===
Create auto QA builds from PR branches.
QA Steps
===
> Build QA site for PR

- Gemfile
- Gemfile.lock
- config/database.yml
> Use Mysql in prod environment

- app/models/search_builder.rb
- spec/features/home_facets_spec.rb
Fixes a bunch of deprecation warnings on this line when testing.
> Fix dperecation warning on count.

- app/controllers/catalog_controller.rb
- app/models/traject_indexer.rb
BL-268 Update sort_field labels and mappings to match our title, author, and pub_date fields.
> Sort fields

- app/views/devise/sessions/new.html.erb
- spec/features/login_page_spec.rb
> Update sign-in form.

- app/assets/stylesheets/tucob.css.erb
Adds padding-left to physical holding availability buttons.
> Add padding to physical holding button

- app/views/catalog/_show_availability_section.html.erb
Updates the conditional statements to use fetch so that record pages don't break with empty data
> Availability facet

- sp.docker-compose.yml
fixes the docker container with shib not building after travis roper
updates.
> Fix local shib container.

- lib/traject/macros/custom.rb
Update words to exclude from genre_facet list
> Refine genre_facet exclusions

- app/models/traject_indexer.rb
> Enable trim punctuation config for topic facet.

- .docker/cli/Dockerfile
- docker-compose.yml
- lib/tasks/docker.rb
Set minimum and maximum memory usage for the JVM running the Solr
instance.  Hopefully we can maximize the number of PRs that get QA
builds this way.
> Controll memory allotment for solr instance.

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/assets/stylesheets/tucob.css.erb
- app/views/catalog/_index_availability_section.html.erb
Adds dropdown arrow to items that are "not available"
> Add arrow functionality to not available buttons

- Gemfile
- Gemfile.lock
Adds the skylight gem to allow performance monitoring with https://www.skylight.io/
> Add skylight for profiling

- app/assets/javascripts/application.js
- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/partials/_facets.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/tucob.css.erb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_previous_next_doc.html.erb
- app/views/catalog/_show_default.html.erb
- app/views/catalog/_show_tools.html.erb
- app/views/catalog/_show_tools_navbar.html.erb
- app/views/catalog/show.html.erb
- app/views/shared/_header_navbar.html.erb
> Update search results theme/layout based on new mockup

- app/assets/javascripts/book_covers.js
- app/assets/stylesheets/partials/_pagination.scss
- app/assets/stylesheets/tucob.css.erb
- app/models/search_builder.rb
- app/views/catalog/_constraints_element.html.erb
- app/views/catalog/_home_text.html.erb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_search_form.html.erb
BL-220 This fixes some current issues with accessibility on the home page and search results index page.
> Accessibility testing

- solr/conf/schema.xml
This way we get balance for and -> \&
> Apply Synonym filter at index time too

- app/assets/stylesheets/tucob.css.erb
- app/views/advanced/_advanced_search_facets.html.erb
> BL-297 Update layout/styling for Advanced Search

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/assets/stylesheets/partials/_facets.scss
Updated font size and spacing on availability buttons.
> Update search results theme/layout based on new mockup #BL-276

- lib/traject/macros/custom.rb
- When subtitle missing, search whole field
- Fix bug in regex that fails match when end date is not used.
> Fix sorting anomaly for missing subtitle or until

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
Updates the logic for an unavailable  status in the search results.  
- If an item is available at one location, but unavailable at another, it should display the library name. 991034984279703811
- If all copies are unavailable, it should just display "checked out or currently unavailable" 991029432039703811
> Bl 313 checked out

- app/controllers/devise/session_controller.rb
- config/application.rb
- config/devise.yml
- spec/controllers/devise_spec.rb
REF BL-224
Force a shibboleth session logout when logging out from application by
redirecting the user to the shibboleth loggout URL.
> Set up proper single logout handle.

- lib/traject/macros/custom.rb
> Accept alpha/num/space/parentheses

- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/partials/_facets.scss
as relates to #BL-266, not available button was wrong size text and padding. should now look uniform.
> Cleaned up css declared twice, slightly differently.

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
BL-313 Reverts back to pervious version for the beta release.
> Revert availabilityInfo function back to previous version

- app/helpers/application_helper.rb
- app/views/catalog/_home_text.html.erb
- app/views/shared/_banner.html.erb
- config/locales/blacklight.en.yml
- spec/features/indices_spec.rb
Banner and home page text updated.  Link is not published yet, so you will see access denied when you click on it.
> BL-322 Update text for banner and landing page

- lib/oai/alma.rb
- lib/tasks/oaiharvest.rake
REF BL-76
This is an MVP for a jenkins oai harvester job.  It does the following:
* Deletes previous build MARC XML files for clean build.
* Determines time span for harvest based on last build time.
* Runs an oai harvest task.
* Determines if Errors were logged and fails the buid if so.
* Archives the Error logs.
> Add jenkins oai harvest task.

- lib/tasks/oaiharvest.rake
> Add extra steps to harvesting.

- app/models/solr_document.rb
- spec/models/solr_document_spec.rb
REF BL-296
Removes incompatible extension with our xml records.
> Fix xml view broken.

- .rubocop.yml
- lib/traject/macros/custom.rb
REF BL-246
This resets strings to be frozen in macros/custom.rb file. I was not able to
reproduce any issues after enabling this and running the ingest process
locally.
> Use frozen-strings.

- bin/solr_harvest_json_records2xml
- spec/controllers/query_results_spec.rb
- spec/fixtures/search_features.yml
- Add'l documentation to test code
- Fixes for harvester not handling MMSID search
- Woah-oh, amber is the color of my energy
> - Updates to query results test and test data

- README.md
Hi there! 👋
I work at Skylight, and had chatted over email with @bibliotechy about adding a Skylight performance badge to the COB README as part of the Skylight for Open Source [program](http://oss.skylight.io). This PR does just that 😄 
Please do let me know if there is a better place to put this badge; I followed what I have seen other open source repositories do, but I can move it if you'd prefer!
> Add Skylight performance monitoring badge

- lib/tasks/jenkins.rake
- lib/tasks/oaiharvest.rake
> Allow for reuse of downloaded files.

- lib/traject/macros/custom.rb
BL-266 Updates the text for archive it links to account for links that include www and links that don't.
> BL-266 Update text for archive-it links

- lib/traject/macros/custom.rb
- spec/fixtures/marc_fixture.xml
BL-257 Use unicode_normalize method in genre_facet to exclude foreign words and phrases
> BL-257 Use unicode_normalize method in genre_facet

- app/views/catalog/_index_availability_section.html.erb
Be safer with fetch, even if that shouldn't happen
> Fix a bug with zero electronic_resource_display items

- app/views/catalog/_index_default.html.erb
- spec/features/indices_spec.rb
BL-326 Clicking on an cover image or default icon takes you to the record page.
> BL-326 Add link to book covers and default format icons in search

- app/helpers/advanced_helper.rb
- spec/helpers/advanced_search_helper_spec.rb
> Copy basic search into initial advanced search

- Gemfile.lock
- config/initializers/primo.rb
Fixes Primo not working after vid/scope update.
> Update search context to :PC

- app/models/blacklight/primo_central/solr_adaptor.rb
> Remove pub_date_sort to creationdate facet map.

- app/controllers/primo_central_controller.rb
REF BL-349
Missed adding the collection facet on the first go.
> Add facet collection.

- app/controllers/search_controller.rb
- app/helpers/application_helper.rb
- app/search_engines/bento_search/journals_engine.rb
- config/initializers/bento_search.rb
- config/locales/bento.en.yml
REF BL-365
* Adds a bento box for journals search that links to faceted search with
format "Journal/Periodical".
> Add Journals Bento Box to Bento page.

- app/views/application/_advanced_search_link.html.erb
Update the path for advanced search to work with the /catalog prefix in LibQA
> BL-283 Update link to work with LibQA

- spec/fixtures/marc_files/contributor_examples.xml
- spec/fixtures/marc_files/creator_examples.xml
- spec/fixtures/marc_files/creator_vern_examples.xml
- spec/models/traject_indexer_spec.rb
> Add more tests to custom extractor definitions.

- app/views/primo_central/_show_availability_section.html.erb
REF BL-348
Adds a follow up change to for issue BL-348.
Depends on #317
> Use header Online instead of Details.

- app/controllers/primo_central_controller.rb
> Add contributor as index field.

- lib/traject/macros/custom.rb
- spec/fixtures/marc_files/url_field_examples.xml
- spec/models/traject_indexer_spec.rb
Refactor extract_availability method to handle cases where the "u" subfield is nil.
> Availability index error

- bin/massage.sh
Stupid bash tricks. This will always run in a bash context, right?
> Make massaging marc collection cross platform.

- app/models/blacklight/primo_central/document.rb
- app/models/blacklight/primo_central/repository.rb
REF BL-386
Fixes browsing buttons broken in libqa.
> Encode slashes in primo ids.

- app/controllers/primo_central_controller.rb
- app/models/blacklight/primo_central/solr_adaptor.rb
> Update field names.

- app/search_engines/bento_search/primo_engine.rb
- app/views/bento_search/_no_results.html.erb
- config/locales/en.yml
REF BL-371
* Empty searches error out for bento primo, so we need to skip them.
> Skip empty search for primo bento searches.

- app/controllers/search_controller.rb
- app/helpers/application_helper.rb
- app/search_engines/bento_search/books_engine.rb
- config/initializers/bento_search.rb
- config/locales/bento.en.yml
> Add books bento box.

- app/assets/stylesheets/icons.css.erb
- app/controllers/primo_central_controller.rb
- app/helpers/primo_central_helper.rb
REF BL-392
* Applies translation to type code for index field via helper method
* Refactors out helper methods to helper class.
> Translate index field type code.

- Gemfile
- Gemfile.lock
APPSEC for the production branch.
> Update rails-html-sanitizer and loofah

- config/locations.yml
- lib/tasks/locations.rake
BL-394 Prepend remote storage locations with the text "Remote Storage"
> BL-394 Add additional text to remote storage locations

- config/locations.yml
- lib/tasks/locations.rake
BL-394 Adds a comma after "Remote Storage"
> BL-394 Add comma

- README.md
- lib/tasks/server.rake
OK. Docs updated. Ready for review.
> Make ingesting test data optional Also refactor tasks

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
BL-417 Sorts library names in brief view that are unavailable or have a check_holdings status
> BL-417 sort items that are unavailable or check_holding status

- app/controllers/catalog_controller.rb
- app/controllers/primo_central_controller.rb
Fixes base_path not defined for CatalogController in libqa.
> Fix base_path not defined.

- app/helpers/catalog_helper.rb
- config/initializers/assets.rb
REF BL-411
Use the "unknown" format to avoid broken image issue.
> Make default format unknown.

- app/controllers/primo_central_controller.rb
REF BL-428
Removes the Collections facet from PCI index.
> Remove collection facet.

- .rubocop.yml
- app/models/blacklight/primo_central/document.rb
- app/models/blacklight/primo_central/repository.rb
- app/models/blacklight/primo_central/response.rb
- config/application.rb
- config/caches.yml
REF BL-418
Caches primo central response. The cache expiration is configurable via
environment variables.
> Cache the primo central response.

- app/controllers/primo_central_controller.rb
> Strip html tags from Primo record notes field.

- spec/spec_helper.rb
Rspec may not properly set the exit code to non zero value under certain
conditions. This monkey patch fixes that issue.
@see http://www.davekonopka.com/2013/rspec-exit-code.html
> Fix tests fails but travis build passes.

- app/assets/stylesheets/partials/_bento.scss
- app/helpers/application_helper.rb
- app/helpers/primo_central_helper.rb
- app/search_engines/bento_search/blacklight_engine.rb
- app/search_engines/bento_search/primo_engine.rb
- app/views/bento_search/_std_item.html.erb
- app/views/search/_bento_availability.html.erb
- app/views/search/_blacklight_availability.html.erb
- app/views/search/_primo_availability.html.erb
- spec/features/bento_availability_spec.rb
- spec/fixtures/features.yml
- spec/fixtures/marc_fixture.xml
BL-455 Add online availability to the bento search results
- items with a single link go directly to resource
- items with multiple links go to the record page
> Bl 455 bento availability

- app/assets/stylesheets/partials/_header.scss
- app/helpers/application_helper.rb
- app/helpers/primo_advanced_helper.rb
- app/views/advanced/index.html.erb
- app/views/application/_advanced_search_link.html.erb
- app/views/primo_advanced/index.html.erb
- app/views/shared/_header_navbar.html.erb
- config/locales/blacklight_advanced_search.yml
BL-459 Updates include:
- Adding Catalog/Articles headers to nav bars
- Changing the headers on the advanced search pages
- Adding a link to articles/catalog search
> BL-459 Updates navbars to include catalog/articles

- app/helpers/application_helper.rb
- config/locales/blacklight_advanced_search.yml
BL-459 Makes some minor changes requested in testing.
> Change labels

- app/assets/stylesheets/tucob.css.erb
BL-464 Reverts back to the original design
> BL-464 revert availability facet styling

- app/assets/stylesheets/partials/_bento.scss
- app/helpers/application_helper.rb
- app/search_engines/bento_search/more_engine.rb
REF BL-474
Followup changes to bento more box issue.
* Limit results to 2.
* Add view all catalogs results link.
> Update more beto box.

- Gemfile.lock
- app/helpers/alma_data_helper.rb
- config/environments/development.rb
- spec/helpers/alma_data_helper_spec.rb
BL-469 Physical material type should use desc rather than value
- 991025183159703811 should display as Sound Recording, not RECORD
> BL-469 Display desc, not value

- lib/traject/indexer_config.rb
- lib/traject/macros/custom.rb
- spec/fixtures/features.yml
- spec/fixtures/marc_fixture.xml
BL-475 Adds subfield I to contributor_display and title_addl_display
- Requires a reindex
> Update traject mappings

- app/assets/javascripts/application.js
- app/helpers/application_helper.rb
- app/views/catalog/_constraints_element.html.erb
- app/views/catalog/_facets.html.erb
- app/views/catalog/_online_only_checkbox.html.erb
REF BL-460
Adds a checbox that when clicked toggles the faceted Online search for
both the Catalog and the Articles searches.
> Add checkbox for easy "Online" resource search.

- app/assets/stylesheets/tucob.css.erb
- app/views/bookmarks/_show_tools.html.erb
- app/views/bookmarks/_sort_and_per_page.html.erb
- app/views/bookmarks/index.html.erb
#BL-467
Removes tool links from Bookmarks page display and adds them to send to drop-down button.
> Bookmark sendto

- app/views/primo_advanced/_advanced_search_fields.html.erb
#BL-479
Tweak layout for boolean operators in Advanced Search (Articles)
> Left-align Boolean row

- config/locales/en.yml
> Add translation for open_access key.

- app/views/search/index.html.erb
#BL-481 Hides the Bento More column if it's empty.
> Hide the more column if it is empty.

- lib/traject/macros/custom.rb
- lib/translation_maps/marc_date_type_pub_status.yaml
- spec/features/record_page_fields_spec.rb
- spec/fixtures/features.yml
Issue #BL-205
Note:
Issues refers to date type and pub status. Code in place to handle future uses for that field.
> Change pub date from field 260 to CF 008/007-010

- app/views/primo_advanced/_advanced_search_help.html.erb
- app/views/primo_advanced/index.html.erb
> Update articles advanced search help tips.

- app/controllers/users/omniauth_callbacks_controller.rb
This should work. I found a way to do it locally and it looked good. *but* if it doesn't work here I will revert this change.
> Change successful login message flash to success.

- app/assets/stylesheets/partials/_header.scss
- app/views/catalog/_home_text.html.erb
- app/views/primo_central/_home_text.html.erb
- app/views/search/_home_text.html.erb
- config/locales/blacklight.en.yml
- spec/features/indices_spec.rb
#BL-483 Updates to text on Catalog, Articles, and bento landing pages
> Text updates for landing pages: catalog, bento, and articles

- app/controllers/catalog_controller.rb
- lib/traject/indexer_config.rb
- spec/features/record_page_fields_spec.rb
- spec/fixtures/features.yml
- spec/fixtures/marc_fixture.xml
Issue #BL-429
Extracts collection name from local MARC field 973
- Created copy of fixtures records. Used field 773t for 973t and field 740a for 973a.
- Add collection field to index and catalog_controller.
> Add collection titles to Solr index

- app/assets/stylesheets/partials/_header.scss
- app/views/advanced/_search_form.html.erb
- app/views/advanced/index.html.erb
REF BL-486
Followup with some more form tweaks.
> Remove links and start over button.

- app/assets/stylesheets/partials/_header.scss
- app/helpers/application_helper.rb
- app/views/shared/_header_navbar.html.erb
> Add some header links.

- lib/tasks/server.rake
- spec/spec_helper.rb
Fixes tests failing on travis but passing build.
> Do not exit with 0 when tests fail.

- app/controllers/catalog_controller.rb
- spec/fixtures/features.yml
- spec/fixtures/marc_fixture.xml
REF BL-432
Transforms hhmmss to hh:mm:ss for duration_display field.
> Update display for duration_display field.

- app/assets/stylesheets/partials/_header.scss
- app/controllers/catalog_controller.rb
- app/views/catalog/_home_text.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/primo_central/_home_text.html.erb
- app/views/search/_home_text.html.erb
- config/locales/blacklight.en.yml
#BL-335 Update text for Shib. sign-in
> Login page

- app/views/almaws/item.html.erb
New branch to remove config file in last branch, to address cell widths.
> Updated table column widths.

- app/helpers/application_helper.rb
- app/helpers/catalog_helper.rb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_online_availability.html.erb
- app/views/catalog/_online_availability_button.html.erb
- app/views/catalog/_show_availability_section.html.erb
REF BL-480
Refactors online availability button and online availability document
section so not render section or button if no online resource is
available.
> Do not render online facet or buttons if none available.

- lib/traject/macros/marc_format_classifier.rb
- lib/translation_maps/marc_genre_008_26.yaml
- lib/translation_maps/marc_genre_leader_7.yaml
- lib/translation_maps/resource_type_codes.yaml
- spec/fixtures/marc_files/data_06m_006-9c.xml
- spec/fixtures/marc_files/data_06m_006-9d_7c.xml
- spec/fixtures/marc_files/data_06m_006-9d_7i.xml
- spec/fixtures/marc_files/data_06m_006-9d_7m.xml
- spec/fixtures/marc_files/data_06m_006-9d_7s.xml
- spec/fixtures/marc_files/data_06m_008-26c.xml
- spec/fixtures/marc_files/data_06m_008-26d_7c.xml
- spec/fixtures/marc_files/data_06m_008-26d_7i.xml
- spec/fixtures/marc_files/data_06m_008-26d_7m.xml
- spec/fixtures/marc_files/data_06m_008-26d_7s.xml
- spec/fixtures/marc_files/govdoc.xml
- spec/lib/traject/macros/marc_format_classifier_spec.rb
Issue #BL254
Updates resource type mappings
> Resource type mappings update

- app/views/users/_user_loans.html.erb
> Make loans access of attribute safer

- .travis.yml
Previously, @skng5 and I got email on every build. No more
> Don't send emails about travis builds

- app/assets/stylesheets/tucob.css.erb
- app/views/almaws/item.html.erb
Fixes the issue with multiple heading rows, and adds proper scoping, addresses scroll bar issues.
> Availability

- lib/oai/alma.rb
- lib/tasks/jenkins.rake
- lib/tasks/oaiharvest.rake
* Allow for reuse of downloaded files (#283) BL-76
* Make sure to close files after writes. (#303)
> Cherry pick harvest commits missing from prod.

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/views/_user_util_links.html.erb
- app/views/shared/_nav_bar_login_links.html.erb
- config/application.rb
- config/initializers/features.rb
- doc/architecture-decisions/0001-use-feature-flags-to-toggle-features.md
* Set up simple feature flag system
* Gall durn Rubocop
* Add architecture decsion record
> Use feature flags to turn off  features

- app/assets/stylesheets/tucob.scss.erb
- app/views/almaws/item.html.erb
Priority to location, callnum, desc, and availability. Type and Public note are tiny.
> Added fixed widths to availability table cells.

- app/mailers/application_mailer.rb
- config/environments/development.rb
- config/environments/production.rb
Fix ArgumentError: SMTP From address may not be blank: nil
> Add default email from.

- lib/tasks/oaiharvest.rake
Solr automatically commits every 15 minutes or when ingest exceeds
a specific number.
> Do not commit data.

- app/views/users/_user_loans.html.erb
BL-491 Text should now read:
- Items marked with  icon are not eligible for renewal at this time and are disabled. Please visit your library's Circulation Desk for more information or Ask a Librarian.
> Update text for unable to renew message.

- app/controllers/catalog_controller.rb
> Gracefully handle range limit error.

- app/controllers/catalog_controller.rb
- app/helpers/bookmark_helper.rb
- app/javascript/packs/controllers/index_controller.js
- app/models/blacklight/primo_central/document.rb
- app/models/blacklight/primo_central/search_builder_behavior.rb
- app/search_engines/primo_central_bookmark_search.rb
- app/views/catalog/_document.html.erb
- config/routes.rb
- spec/helpers/bookmark_helper_spec.rb
- spec/models/primo_central_document_spec.rb
- spec/models/primo_search_builder_spec.rb
> Add ajax lookup of failed Primo bookmark.

- app/helpers/catalog_helper.rb
- app/views/catalog/_search_results.html.erb
> Remove alternate links headers.

- lib/traject/indexer_config.rb
- lib/traject/macros/custom.rb
- spec/fixtures/features.yml
- spec/fixtures/marc_files/subject_display.xml
- spec/fixtures/marc_files/subject_topic_missing.xml
- spec/lib/traject/traject_indexer_spec.rb
REF BL-351
Require a re-index.
> Remove dashes from names in subject display.

- Gemfile.lock
- app/models/concerns/blacklight/document/article_email.rb
- app/models/primo_central_document.rb
- config/locales/blacklight.en.yml
> Allow emails of articles.

- app/views/record_mailer/email_record.text.erb
- config/locales/blacklight.en.yml
> Update email headers.

- app/helpers/catalog_helper.rb
- app/helpers/primo_advanced_helper.rb
- app/views/application/_advanced_search_link.html.erb
REF BL-510
Fixes advanced searches starting on non first page.
> Remove page params from advanced search.

- app/assets/stylesheets/partials/_header.scss
BL-513 Update font for headings/button to match the user_util links
> Update font for nav_header

- app/assets/stylesheets/tucob.scss.erb
- app/controllers/catalog_controller.rb
- app/controllers/primo_central_controller.rb
- app/controllers/search_controller.rb
- app/helpers/catalog_helper.rb
- app/search_engines/bento_search/blacklight_engine.rb
- app/views/bento_search/_std_item.html.erb
- app/views/catalog/_fields.html.erb
- app/views/catalog/_index_default.html.erb
> Add resource type to more results.

- app/views/application/_advanced_search_link.html.erb
- app/views/primo_advanced/_advanced_search_form.html.erb
REF BL-509 (followups).
Also fixes typo.
> Do not render basic params in primo advanced search.

- app/controllers/catalog_controller.rb
- spec/features/record_page_fields_spec.rb
BL-525 Remove pub_date field from catalog controller and record specs
> Remove pub_date field from full record display

- Gemfile
- Gemfile.lock
BL-526 Update gem file to get call numbers displaying
> Bl 526 call numbers

- app/controllers/almaws_controller.rb
- app/javascript/packs/controllers/show_controller.js
- app/lib/cob_alma/requests.rb
- app/views/almaws/_digitization_request_form.html.erb
- app/views/almaws/_hold_request_form.html.erb
- config/routes.rb
BL-382 Hold request functionality 
- Both bib level and item level requests are sending
- Updated show controller for modals on the full record page
> Bl 382 hold requests

- app/views/catalog/_search_results.html.erb
- config/locales/blacklight.en.yml
BL-521 Remove search term from page titles in search results
> Update page title text for search results

- app/assets/stylesheets/partials/_bento.scss
- app/assets/stylesheets/tucob.scss.erb
- app/controllers/search_controller.rb
- app/decorators/tul_decorator.rb
- app/helpers/application_helper.rb
- app/helpers/search_helper.rb
- app/search_engines/bento_search/blacklight_engine.rb
- app/search_engines/bento_search/books_engine.rb
- app/search_engines/bento_search/journals_engine.rb
- app/search_engines/bento_search/more_engine.rb
- app/search_engines/bento_search/primo_engine.rb
- app/views/bento_search/_more.html.erb
- app/views/bento_search/_std_item.html.erb
- app/views/search/_more_facets.html.erb
- app/views/search/_more_item.html.erb
- app/views/search/index.html.erb
- config/initializers/bento_search.rb
- spec/search_engines/more_search_spec.rb
REF Bl-534
* Links bento box title to results.
* Breaks up more results into two bento sets.
* Widens bento box columns.
* Refactors some bento code for better reuse.
> Update bento box.

- app/assets/stylesheets/tucob.scss.erb
- app/javascript/packs/controllers/explanation_controller.js
- app/views/catalog/_search_results.html.erb
- app/views/search/index.html.erb
- config/locales/blacklight.en.yml
BL-516 Adds text for users to see what is included in their search results
> Bl 516 explanatory text

- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/tucob.scss.erb
- app/helpers/application_helper.rb
- app/views/_user_util_links.html.erb
- app/views/shared/_header_navbar.html.erb
> Responsive work

- app/controllers/application_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
> Fix redirect not working.

- Gemfile.lock
- app/controllers/almaws_controller.rb
- app/lib/cob_alma/requests.rb
- app/views/almaws/_booking_request_form.html.erb
- app/views/almaws/request_options.html.erb
- config/routes.rb
- spec/fixtures/marc_fixture.xml
BL-506 Adds booking request functionality.
> Booking requests sending successfully

- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/tucob.scss.erb
- app/helpers/application_helper.rb
- app/views/_user_util_links.html.erb
> Removed hidden links from rendering empty html (list item nav links).

- app/assets/stylesheets/tucob.scss.erb
- app/views/catalog/_search_results.html.erb
- app/views/search/index.html.erb
BL-516 Aligns explanatory text with the search results for catalog and article results.
> Left align explanatory text

- app/controllers/catalog_controller.rb
Fixes title and creator fielded searches to use the right filed groupings
> Use the right field groups for field searches

- app/views/almaws/request_options.html.erb
BL-554 Hide request option headings if that option is not available.
- Items in the SCRC collection should currently show no options
> Move request logic to the top level

- app/views/record_mailer/email_record.text.erb
> Add breaks between emails.

- app/helpers/users_helper.rb
- app/views/users/_user_holds.html.erb
> Do not fail if expiry-date does not apply.

- app/controllers/catalog_controller.rb
- app/views/advanced/_advanced_search_facets.html.erb
> Remove count from facet in advanced select field.

- app/controllers/primo_central_controller.rb
- config/locales/en.yml
> Update Availability facet for article search.

- config/locales/en.yml
> Remove parenthetical from label.

- app/helpers/application_helper.rb
- app/models/concerns/blacklight/document/sms.rb
- config/locales/blacklight.en.yml
REF BL-548
Also refactors render_location helper (was not being used).
> Only text location and link.

- lib/traject/indexer_config.rb
- lib/traject/macros/custom.rb
- spec/features/record_page_fields_spec.rb
- spec/fixtures/features.yml
- spec/fixtures/marc_files/extract_lang.xml
- spec/fixtures/marc_files/normalize_lang.xml
- spec/lib/traject/traject_indexer_spec.rb
> Only use first 3 chars of lang codes.

- app/helpers/application_helper.rb
- app/views/record_mailer/sms_record.text.erb
REF BL-548
* URL should come first
* Add space between library and location.
> SMS tweaks.

- app/controllers/users_controller.rb
- spec/controllers/users_controller_spec.rb
> Do not cache account page.

- app/lib/cob_alma/requests.rb
BL-506 Fixes the bug where material types were repeating
> Return each material type only once

- app/assets/stylesheets/tucob.scss.erb
- app/javascript/packs/controllers/availability_controller.js
- app/javascript/packs/controllers/show_controller.js
- app/views/almaws/item.html.erb
- app/views/almaws/request_options.html.erb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_show_availability_section.html.erb
- app/views/primo_central/_show_availability_section.html.erb
Updates the placement of the request buttons on search result and record show pages
> Bl 544 styling updates

- lib/traject/indexer_config.rb
REF BL-517
Requires a re-index.
> Update field spec for langauge_facet,display to match.

- app/javascript/packs/controllers/show_controller.js
BL-544 Fixes the bug where availability panel disappears
> Refactor code to combine request and availability into one method

- app/assets/stylesheets/tucob.scss.erb
Fixes login page style off when not in modal context.
> Fix login page styling.

- app/views/almaws/_booking_request_form.html.erb
- app/views/almaws/_digitization_request_form.html.erb
- app/views/almaws/_hold_request_form.html.erb
BL-550 Makes the required field accessible
> Add aria-required for accessibility

- app/controllers/almaws_controller.rb
- spec/fixtures/marc_fixture.xml
Refactor controller to handle all digitization requests at the bib level
> Bl 453 boundwith digitization

- app/lib/cob_alma/requests.rb
- app/views/almaws/_hold_request_form.html.erb
- spec/fixtures/marc_fixture.xml
Equipment filters needed refactoring for multiple items
> Refactor equipment for multiple items

- app/views/catalog/_constraints.html.erb
- app/views/catalog/_previous_next_doc.html.erb
> Make start_over link go to bento search path.

- config/environments/development.rb
- config/environments/production.rb
REF BL-241
I'm updating the from: email to asktulibrary@temple.edu.  I'm not sure
this will work because I did not update the smtp user/password config.
But I'm guessing we can allow books@temple.edu to send emails as
asktulibrary in some GMAIL config panel.
> Update from email address.

- app/assets/stylesheets/tucob.scss.erb
- app/helpers/application_helper.rb
- app/views/almaws/request_options.html.erb
- app/views/catalog/_aeon_request.html.erb
- app/views/catalog/_show_availability_section.html.erb
- spec/features/record_page_fields_spec.rb
Moves the aeon request into the requests modal
> Bl 539 aeon request

- app/controllers/concerns/bookmarks_config.rb
> Remove cite button from bookmarks page.

- app/views/catalog/_citation.html.erb
> Add text to citation modal.

- app/views/catalog/_show_tools.html.erb
- config/locales/blacklight.en.yml
This reverts commit 7e8c9d9aa7559177ee87cdefb86f18de6c86d63b.
REF BL-571
> Revert "Make refworks link a button on catalog show page. (#581)"

- app/helpers/application_helper.rb
- app/helpers/catalog_helper.rb
- app/views/search/_home_text.html.erb
- app/views/shared/_banner.html.erb
- app/views/shared/_header_navbar.html.erb
- config/application.rb
- config/locales/blacklight.en.yml
- config/locales/en.yml
> Update bento verbiage.

- app/views/catalog/_citation.html.erb
> Move citation warning to bottom.

- app/assets/stylesheets/partials/_header.scss
- app/views/shared/_header_navbar.html.erb
iPhone 5 specific issue fixed with further font-size reduction on all devices at less than 485px.
> Logo text fix

- app/javascript/packs/controllers/form_controller.js
LibQA was forcing validation on empty date fields
-add conditional to method to allow for empty fields without validation
> Refine javascript method to avoid validation when empty

- app/javascript/packs/controllers/form_controller.js
- app/views/almaws/_digitization_request_form.html.erb
- app/views/almaws/_hold_request_form.html.erb
The custom validation method was not working before
- move format message into a div instead of using setCustomValidation()
> Move custom validation message into div

- app/helpers/application_helper.rb
- config/application.rb
> Use config help_link vs a translations.

- app/controllers/almaws_controller.rb
- spec/controllers/almaws_controller_spec.rb
Adds specs to test for exceptions
- also refactors dates to rescue empty strings
> Add specs for requests

- package-lock.json
- package.json
BL-585 Availability isn't displaying correctly on windows 11
> Add polyfills package to support windows 11

- Gemfile.lock
- app/controllers/users_controller.rb
- app/models/user.rb
- spec/controllers/users_controller_spec.rb
BL-591 Handle cases where a user does not have a uid
> Redirect users with an error message if no uid

- Gemfile.lock
- app/models/blacklight/primo_central/document.rb
- app/models/blacklight/primo_central/repository.rb
- app/models/blacklight/primo_central/search_builder_behavior.rb
REF BL-594
REF https://app.honeybadger.io/projects/56250/faults/39091736
> Fix semicolon breaks app path.

- app/assets/stylesheets/tucob.scss.erb
- app/views/users/_user_holds.html.erb
Removes multiple links to SCRC Research Account on Library Account page
> Take SCRC link out of each loop

- app/controllers/primo_central_controller.rb
- app/models/primo_central_document.rb
> Enable sms of articles.

- app/assets/stylesheets/tucob.scss.erb
- app/views/bookmarks/_sort_and_per_page.html.erb
BL-581 Links back to search from bookmarks page
> Add a back_to_search button on bookmarks page

- app/assets/stylesheets/tucob.scss.erb
- app/views/bookmarks/_sort_and_per_page.html.erb
Updates the styling to match "back to search" button on full record pages
> Update styling for bookmark-back-btn

- app/assets/stylesheets/tucob.scss.erb
- app/javascript/packs/controllers/primo_controller.js
- app/views/primo_advanced/_advanced_search_fields.html.erb
- app/views/primo_advanced/_advanced_search_submit_btns.html.erb
- app/views/primo_advanced/index.html.erb
Prevents the user from submitting an empty form in advanced article search
> Add validation to empty advanced form

- app/assets/javascripts/listeners.js
- app/javascript/packs/controllers/show_controller.js
- app/views/catalog/_show_availability_section.html.erb
Removes error appearing in online resource record pages
- also discovered a console error related to a mis-named id, so I fixed that too
> Move controller declaration to get rid of console error

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/tucob.scss.erb
- app/controllers/users_controller.rb
- app/javascript/packs/controllers/fines_controller.js
- app/javascript/packs/controllers/holds_controller.js
- app/javascript/packs/controllers/loans_controller.js
- app/models/user.rb
- app/views/users/_fines_details.html.erb
- app/views/users/_holds_details.html.erb
- app/views/users/_loans_details.html.erb
- app/views/users/_user_fines.html.erb
- app/views/users/_user_holds.html.erb
- app/views/users/_user_info.html.erb
- app/views/users/_user_loans.html.erb
- config/routes.rb
- spec/views/users/_user_loans.html.erb_spec.rb
This one needs some careful review, please, as it has a LOT of moving pieces.
Needs to be tested on IE11 and IE pre-11 to make sure it does not break account page for those browsers.
~~DO NOT MERGE UNTIL https://github.com/tulibraries/alma_rb/pull/29/files has been merged an 
the gemfile in this project updated accordning.~~ Merged and reference updated. (8/20/18)
> Refactor Account page to use AJAX loading.

- app/assets/javascripts/book_covers.js
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_show_default.html.erb
> Remove lccn book covers.

- app/javascript/packs/application.js
- package-lock.json
- package.json
The new stimulus version is supposed to fix issues with internet explorer, so we upgraded.
> Upgrade to newest version of stimulus

- app/controllers/almaws_controller.rb
- app/javascript/packs/controllers/form_controller.js
- app/views/almaws/_booking_request_form.html.erb
- app/views/almaws/_digitization_request_form.html.erb
- app/views/almaws/_hold_request_form.html.erb
BL-627 Alma has a strange user interface for full chapter digitization requests
- Remove the full chapter option and handle everything as partial
- Add validation patterns for text fields to disallow empty strings
- Change page fields to numbers and add min validations
> Bl 627 digitization requests

- app/helpers/application_helper.rb
Fixes bug where multiple aeon buttons were displaying on record pages with multiple items
> Show only 1 aeon button

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- spec/fixtures/marc_fixture.xml
There were still some cases where the availability button was not loading
- this calls the button method in the checkAndPopulateMissing function to hopefully cover all cases
> Handle additional availability loading problems

- config/libraries.yml
- config/locations.yml
> Add new location and library code.

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- spec/fixtures/marc_fixture.xml
BL-618 Fixes bug where availability information was not displaying for missing and lost items
> Show unavailable button for lost and missing items

- app/helpers/request_helper.rb
- app/javascript/packs/controllers/availability_controller.js
- app/views/catalog/_index_availability_section.html.erb
Change order that targets are called to try to get rid of javascript console errors
> Change order that data-targets are called

- app/assets/stylesheets/tucob.scss.erb
- app/views/advanced/_advanced_search_submit_btns.html.erb
- app/views/primo_advanced/_advanced_search_submit_btns.html.erb
- config/locales/blacklight_advanced_search.yml
BL-637 Changes requested for advances search buttons
- Reverse order
- Update text to "Clear Form" and add new styling
> Bl 637 advanced buttons

- lib/traject/indexer_config.rb
- lib/traject/macros/custom.rb
- spec/fixtures/marc_files/subject_topic_missing.xml
- spec/fixtures/marc_fixture.xml
- spec/lib/traject/traject_indexer_spec.rb
BL-629 Subject display fields were getting the data mixed up
- Index named fields and description fields together so that the description fields don't go to the wrong line
> BL-629 subject_display subfields indexed together

- app/views/almaws/_digitization_request_form.html.erb
- app/views/almaws/_hold_request_form.html.erb
> Set default last_interest_date to ""

- app/views/almaws/request_options.html.erb
BL-645 Header was accidentally removed in a previous commit
> Add request header back in to modal

- app/models/blacklight/primo_central/solr_adaptor.rb
> Fix bookmarked article title broken.

- package-lock.json
- package.json
BL-585 The latest internet explorer problem is ReferenceError: 'fetch' is undefined [object Object]
- adds another polyfill package to address this
> Add polyfill to handle fetch

- app/javascript/packs/application.js
Add import to application.js file
> Actually import the polyfill package

- app/javascript/packs/controllers/availability_controller.js
- app/javascript/packs/controllers/explanation_controller.js
- app/javascript/packs/controllers/fines_controller.js
- app/javascript/packs/controllers/show_controller.js
BL-585 Use the jQuery remove method to show availability in internet explorer
> Use jQuery remove method

- app/assets/stylesheets/tucob.scss.erb
BL-652 Auto-hide scrollbar when not needed
> BL-652 Hide scrollbar in internet explorer

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/tucob.scss.erb
- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
BL-571 Use blacklight-ris gem to enable the user to download ris files
- @dkinzer Can we talk about this approach?
> Bl 571 ris files

- app/controllers/catalog_controller.rb
- solr/conf/schema.xml
BL-610 Call number should be included in the advanced dropdown search fields after ISSN
> BL-610 Add call number to the advanced search field dropdowns

- .babelrc
- .travis.yml
- package.json
- spec/javascript/README.md
- spec/javascript/packs/controllers/availability_controller.spec.js
- spec/javascript/setup.test.js
- spec/javascript/setup/fetch-mock.js
- spec/javascript/setup/jquery.js
- spec/javascript/setup/mutation-observer.js
Adds the Jest JavaScript testing framework to our project with some initial tests and a documentation.
> Add javascript testing.

- app/controllers/application_controller.rb
> Update reload page verbiage.

- app/assets/stylesheets/tucob.scss.erb
- app/controllers/concerns/multi_source_bookmarks.rb
- app/helpers/application_helper.rb
- app/models/primo_central_document.rb
- app/models/solr_document.rb
- app/views/bookmarks/_show_tools.html.erb
- app/views/bookmarks/index.html.erb
- app/views/catalog/_show_tools.html.erb
- spec/controllers/bookmarks_controller_spec.rb
BL-571 Implement feature to download individual catalog/article records and bookmarks in ris format
> Bl 571 ris bookmarks

- app/models/search_builder.rb
- app/views/advanced/_advanced_search_fields.html.erb
- spec/features/advanced_search_spec.rb
- spec/models/search_builder_spec.rb
REF BL-638
Fixes inconsistent search results do to search operator getting
clobbered when operator is saved inside of an array.
> Fix search operator getting clobbered.

- app/assets/stylesheets/tucob.scss.erb
- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
- app/views/bookmarks/_show_tools.html.erb
BL-571 Update ris mappings
- label should be "RIS File"
> Bl 571 update mappings

- app/controllers/application_controller.rb
> Update message verbiage.

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/views/advanced/_advanced_search_facets.html.erb
BL-323 Add bootstrap-select through gem
-enable data-live-search so that we get the searchable text selects
> Bootstrap select

- lib/traject/macros/custom.rb
- spec/fixtures/marc_files/contributor_examples.xml
- spec/fixtures/marc_files/creator_examples.xml
- spec/fixtures/marc_files/creator_multiple_subfields.xml
- spec/fixtures/marc_files/creator_vern_examples.xml
- spec/fixtures/marc_fixture.xml
- spec/lib/traject/traject_indexer_spec.rb
BL-585 Refactors creator and contributor methods to allow for multiple instances of the same subfield
> BL-585 Allow for multiple subfields in creator/contributor

- app/assets/javascripts/blacklight_range_limit/range_limit_slider.js
- app/assets/stylesheets/partials/_facets.scss
- app/views/primo_advanced/_advanced_search_facets.html.erb
- app/views/primo_advanced/_advanced_search_form.html.erb
> Adds range limit facet to primo advanced form.

- app/controllers/catalog_controller.rb
- app/controllers/primo_central_controller.rb
This reverts commit 8158f98f1e8860022111f7aad8922d3ee17d7248.
> Revert "Temporarily disable refworks. (#685)"

- app/controllers/catalog_controller.rb
- solr/conf/schema.xml
BL-610 Add call_number_alt field to solr for advanced searches
> BL-610 Adds call_number_alt field to advanced search

- app/search_engines/bento_search/blacklight_engine.rb
Use the truncated_title_display for bento blacklight results
> BL-580 Truncated titles for bento

- app/controllers/catalog_controller.rb
- app/models/blacklight/primo_central/document.rb
- Use truncate method for PCI titles in search results
- Fix rubocop offense
> BL-580 Title truncation

- app/models/blacklight/primo_central/document.rb
- Handle nil cases in primo document titles
> Fix broken spec for primo central document

- app/views/almaws/_availability_status.html.erb
REF BL-242
Adds a missing template required to render status of materials that are
not available.
> Add missing template.

- app/models/solr_document.rb
- spec/models/solr_document_spec.rb
REF BL-242
When multiple items are found, only return a uniq set.
> Only return uniq materials.

- app/controllers/books_controller.rb
- app/controllers/concerns/multi_source_bookmarks.rb
- app/controllers/journals_controller.rb
- app/models/books_search_builder.rb
- app/models/journals_search_builder.rb
- app/models/solr_book_document.rb
- app/models/solr_journal_document.rb
- app/search_engines/catalog_bookmark_search.rb
- app/search_engines/primo_central_bookmark_search.rb
- app/views/books/_home_text.html.erb
- app/views/journals/_home_text.html.erb
- config/locales/blacklight.en.yml
- config/routes.rb
- spec/controllers/books_controller_spec.rb
- spec/controllers/journals_controller_spec.rb
- spec/features/indices_spec.rb
- spec/models/books_search_builder_spec.rb
- spec/models/journals_search_builder_spec.rb
REF BL-690
Adds some new controllers to handle searching just books or just pages
in a clean way.
> Add journal and books search pages.

- app/assets/stylesheets/partials/_header.scss
- app/helpers/application_helper.rb
- app/views/application/_navbar.html.erb
- app/views/shared/_header_navbar.html.erb
- config/routes.rb
- spec/helpers/application_helper_spec.rb
REF BL-685
The new navbar persits the search across all the possible searches for:
* Everything
* Books
* Articles
* More
> Adds a new dynamic navbar to site.

- solr/conf/synonyms.txt
REF BL-695
Add the following synonyms to Solr search:
Cantatas = kantate
Concerto = Konzerte
Mass = Messe
Sonatas = sonaten
Symphonies = sinfonien
Etc. = etcetera
Piano = Klavier
symphony = Sinfonie
arr. = arranged
maj. = major
> Add some more synonyms to solr config.

- app/helpers/application_helper.rb
- config/routes.rb
- spec/features/indices_spec.rb
- spec/fixtures/features.yml
- spec/helpers/application_helper_spec.rb
- spec/relevance/searches_spec.rb
> Makes the bento search the root of the site.

- Gemfile
- Gemfile.lock
Let's stop hitting /bento to do our health checks.
> Add a proper health check gem.

- app/assets/stylesheets/partials/_bento.scss
- app/assets/stylesheets/partials/_facets.scss
- app/assets/stylesheets/partials/_footer.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/tucob.scss.erb
- app/helpers/search_helper.rb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_show_availability_section.html.erb
- app/views/catalog/_show_default.html.erb
- app/views/catalog/_show_tools.html.erb
- app/views/catalog/show.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/search/index.html.erb
Changes to index pages, record pages, advanced search and bento.
> BL-692 Styling updates based on mockups

- app/assets/stylesheets/partials/_colors.scss
- app/views/advanced/_search_form.html.erb
- app/views/catalog/_facets.html.erb
- app/views/catalog/_search_form.html.erb
- app/views/catalog/_tweak_solr_query_form.html.erb
REF #660
This implementation uses the HTML5 `form` attribute for form elements,
does it will not work in i.e.; which should be OK for our use case.
> Move tweak fields to bottom of facets column.

- lib/traject/indexer_config.rb
- lib/traject/macros/custom.rb
- solr/conf/schema.xml
- spec/lib/traject/traject_indexer_spec.rb
REF BL-661
Adds new work_access_point index to help boost author/title searches.
> Add new work_access_point index.

- app/views/almaws/item.html.erb
REF BL-648
Pagination should only appear once at the top and once at the bottom and
no for each library.
> [BL-648] fix pagination appearing multiple times.

- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_show_availability_section.html.erb
Add spinning class to availability spinners so that the animation works.
> BL-622 Fix availability-spinners

- app/views/users/_holds_details.html.erb
- app/views/users/holds.html.erb
Add space between words and use titlecase
> BL-658 Make request status more human readable 

- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/tucob.scss.erb
- app/helpers/application_helper.rb
- app/views/catalog/_search_results.html.erb
- app/views/catalog/_zero_results.html.erb
- spec/helpers/application_helper_spec.rb
- Uses new font for Library Search and header links
- Adds margin to the explanation text to align with search results text
> BL-714 Updates styling to the new navbar

- Gemfile
- Gemfile.lock
- app/controllers/books_advanced_controller.rb
- app/controllers/books_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/journals_advanced_controller.rb
- app/controllers/journals_controller.rb
- app/controllers/primo_advanced_controller.rb
- app/controllers/primo_central_controller.rb
- app/helpers/application_helper.rb
- app/helpers/catalog_helper.rb
- app/views/catalog/show.html.erb
- app/views/layouts/blacklight.html.erb
- spec/helpers/application_helper_spec.rb
REF BL-689
Use breadcrumbs_on_rails gem to add breadcrumbs to the advanced pages
plus books and journals.
> [BL-689] Add breadcrumbs to advanced pages.

- app/views/bookmarks/_show_tools.html.erb
> Updates the path for bookmarked citations

- app/assets/stylesheets/tucob.scss.erb
- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/views/catalog/_holdings_summary.html.erb
- app/views/catalog/_index_availability_section.html.erb
- lib/traject/indexer_config.rb
- lib/traject/macros/custom.rb
- spec/fixtures/marc_files/holdings_summary.xml
- spec/helpers/application_helper_spec.rb
- spec/lib/traject/traject_indexer_spec.rb
- Adds holdings_summary_display field to traject for enriched data in HLD866
- Displays field as a table in the availability panel
> BL-693 Add summary holdings field

- app/helpers/almaws_helper.rb
- app/helpers/request_helper.rb
- app/views/almaws/_booking_allowed.html.erb
- app/views/almaws/_digitization_allowed.html.erb
- app/views/almaws/_hold_allowed.html.erb
- spec/helpers/almaws_helper_spec.rb
- when only hold requests are allowed
> BL-699 Request modal should default to being open 

- app/assets/stylesheets/tucob.scss.erb
- app/controllers/almaws_controller.rb
- app/helpers/almaws_helper.rb
- app/views/almaws/_no_request_options.html.erb
- app/views/almaws/_resource_sharing_broker_allowed.html.erb
- Make sure only books are included
- Display collapse partial with additional details
> Refactor ez-borrow request

- app/controllers/catalog_controller.rb
- lib/traject/indexer_config.rb
- lib/traject/macros/custom.rb
- spec/features/indices_spec.rb
- spec/features/record_page_fields_spec.rb
- Changes mappings for imprint_display
- Adds imprint_prod, imprint_dist, and imprint_man fields
- Changes date_copyright mappings
> BL-431 Updates to imprint_display

- app/views/catalog/_search_form.html.erb
REF BL-691
When viewing a record we still want to persist the search in the search
form.
> [BL-691] Persist the search params.

- config/locales/blacklight_advanced_search.yml
- config/locales/en.yml
- spec/helpers/advanced_search_helper_spec.rb
- The "More" advanced search title and link should just be Advanced Search
- Changes constraints label to "Applied Filters"
> BL-689 Copy changes for advanced Search

- app/assets/stylesheets/tucob.scss.erb
- app/controllers/books_controller.rb
- app/controllers/journals_controller.rb
- app/controllers/primo_central_controller.rb
- Remove background color from #sendto div
- Change breadcrumbs text
> BL-691 Updates to record page displays

- app/assets/stylesheets/tucob.scss.erb
- app/helpers/application_helper.rb
- app/views/almaws/item.html.erb
- Only display Description label when a holdings_summary_display field is present
- Fix the display of the aeon button
> BL-693 Update holdings_summary display

- app/controllers/catalog_controller.rb
> Update title field boosting.

- app/assets/javascripts/application.js
- app/assets/stylesheets/tucob.scss.erb
- app/views/catalog/index.html.erb
- spec/features/indices_spec.rb
- Refactor javascript so that the sortAndPerPage menu displays for bookmarks
- Use the show_sidebar? method to hide sidebar on the home pages
> Fix bugs with latest ux-ui styles not displaying

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_advanced.scss
- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_bento.scss
- app/assets/stylesheets/partials/_colors.scss
- app/assets/stylesheets/partials/_facets.scss
- app/assets/stylesheets/partials/_footer.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_iframe.scss
- app/assets/stylesheets/partials/_pagination.scss
- app/assets/stylesheets/partials/_requests.scss
- app/assets/stylesheets/partials/_sms_form.scss
- app/assets/stylesheets/partials/_typography.scss
- app/assets/stylesheets/partials/_users.scss
- app/assets/stylesheets/partials/_vars.scss
- app/assets/stylesheets/tucob.scss.erb
- app/helpers/catalog_helper.rb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_online_availability.html.erb
- Create/reorganize related styles into partials
- Removes unused css styles
- Ensure that color vars are being used
> BL-620 Clean up css files

- app/assets/stylesheets/partials/_header.scss
- app/helpers/application_helper.rb
- app/views/bookmarks/_show_tools.html.erb
- app/views/bookmarks/index.html.erb
- app/views/catalog/_grouped_citations.html.erb
- app/views/catalog/_single_citation.html.erb
- lib/traject/macros/custom.rb
- spec/fixtures/marc_files/oclc.xml
- spec/helpers/application_helper_spec.rb
- spec/lib/traject/traject_indexer_spec.rb
- Tighten regex so that items are not returning an incorrect oclc number
- Default to citations grouped by format
- Update labels to include versions
> BL-648 Updates to using worldcat citations

- app/views/almaws/item.html.erb
- app/views/catalog/_check_holdings.html.erb
- Removes Description label from header information
- Standardizes width for columns in the check_holdings tables with the availability tables
> BL-693 Update holdings_summary table information

- Gemfile
- Gemfile.lock
> [DevOps:BL-616] Update traject to version 3.0

- Gemfile.lock
- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/helpers/catalog_helper.rb
- app/views/catalog/_online_availability_button.html.erb
- lib/traject/indexer_config.rb
- lib/traject/macros/custom.rb
- solr/conf/schema.xml
- spec/fixtures/electronic_notes.xml
- spec/helpers/catalog_helper_spec.rb
- spec/lib/traject/traject_indexer_spec.rb
REF BL-347
* Refactors link index to use JSON.
* Refactors solr config to parse new JSON fields.
* Refactors link helper methods to use new link objects.
* Refactors link to render collection/service notes.
* Updates blacklight to version 6.18.0
> [BL-347] Refactor electronic collection/service info.

- lib/traject/macros/custom.rb
to creator, contributor and title_statement fields to avoid duplication
> BL-753 Add alternate_script false 

- lib/traject/macros/custom.rb
- spec/fixtures/marc_fixture.xml
- spec/lib/traject/traject_indexer_spec.rb
- Add whitespace around /
- Only add / when subfield c is present
> Refactor extract_title_statement

- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/tucob.scss.erb
- Removes bullet point for additional title information
- Align logo with LibrarySearch
> BL-754 Additional title display

- app/controllers/almaws_controller.rb
- app/javascript/packs/controllers/form_controller.js
- app/views/almaws/_booking_request_form.html.erb
- app/views/almaws/_digitization_request_form.html.erb
- app/views/almaws/_hold_request_form.html.erb
- Fixes issue with item level pickup locations
- Adds unique values to each form field
> Update forms to have unique fields for accessibility

- app/views/catalog/_electronic_notes.html.erb
REF BL-768
..so that tags get rendered.
> [BL-347:768] Render electronic note in raw form.

- app/helpers/catalog_helper.rb
- spec/helpers/catalog_helper_spec.rb
- Label should only display for libraries that have a holdings summary field
> BL-693 Update label for holdings_summary

- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/application/_navbar.html.erb
- app/views/shared/_header_navbar.html.erb
Updates the styling for the navigational headers to make them more responsive to various screen sizes.
> Bl 763 responsive menus

- app/views/catalog/_show_default.html.erb
- Change label color for more contrast
- Add alt tag to default images
> BL-749 Updates to record page accessibility

- app/views/catalog/_purchase_order_anonymous_button.html.erb
REF BL-766, # 874
Forgot to commit new template to PO button refactor.
> [BL-340:766] Add missing template

- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_bento.scss
- app/assets/stylesheets/partials/_facets.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_vars.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/catalog/_online_availability_button.html.erb
- app/views/catalog/_search_results.html.erb
- app/views/catalog/index.html.erb
- app/views/primo_central/_online_button.html.erb
- app/views/search/index.html.erb
- Use larger font for explanatory text
- Widen expanatory text to be across whole screen
- Change color of online buttons for bento and catalog
- Remove underline from Library Search
> BL-764 navigational updates

- app/assets/stylesheets/partials/_requests.scss
- Float left instead of right
- Keep text white in all states
> BL-770 Update ezborrow button

- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_facets.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/catalog/_search_results.html.erb
- app/views/catalog/index.html.erb
- Move explanation text back to search results in catalog
- Fix bug with online collapsed button text color
> BL-764 Updates to navigation

- app/assets/stylesheets/partials/_header.scss
- app/views/bookmarks/_show_tools.html.erb
- app/views/catalog/_refworks_form.html.erb
- app/views/primo_central/_tagged_refworks.erb
- multiple records export to refworks
- add target _blank to primo refworks links
> BL-694 Enable export to refworks for bookmarks

- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_colors.scss
* Add border to table in show availability view.
* Do not change button color for focus.
> [BL-766] Update PO styling.

- app/models/purchase_order_mailer.rb
- app/views/purchase_order_mailer/purchase_order.text.erb
REF BL-767
* bbc orders@temple.edu
* update email verbage
> [BL-340:767] Additional updates to PO email.

- app/views/layouts/blacklight.html.erb
- preload fonts
- add description meta tag
> More updates related to performance

- app/helpers/alma_data_helper.rb
- lib/traject/macros/custom.rb
- spec/fixtures/marc_files/lost_missing_technical.xml
- spec/helpers/alma_data_helper_spec.rb
- spec/lib/traject/traject_indexer_spec.rb
- testing is currently being done on work with the bookbot, but the records in this location should not be visible to users
> BL-791 Suppress items with asrs location

- app/controllers/databases_controller.rb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_show_availability_section.html.erb
> [BL-726] Fix database availability field not working.

- app/controllers/databases_controller.rb
- app/helpers/catalog_helper.rb
REF BL-726
Fixes issue caused by recent BL-7 upgrade update.
> [BL-726] Fix database show availability not displaying.

- app/assets/javascripts/application.js
- Use siblings to get removeClass to work
> BL-790 Refactor function

- app/models/solr_document.rb
- app/views/catalog/_sms_form.html.erb
- app/views/catalog/purchase_order.html.erb
* Change name of flash partial (moved to /shared in blacklight-7)
* defined []=, [], dig for SolrDocument.
> Fix sms not working.

- app/views/primo_central/_direct_link_button.html.erb
- Update classes to reflect new styling colors
- Update helper method for direct links from the index page
> BL-796 Primo online buttons with direct link

- app/assets/stylesheets/partials/_availability.scss
- The right column is sometimes being cut off so the user can't see the content
- Add a horizontal scroll at smaller screen sizes so that users can see all information
> BL-785 Availability display mobile view

- app/helpers/blacklight_marc_helper.rb
- Adds back a helper method accidentally removed last week
> Bl 694 refworks bookmarks

- app/assets/images/temple-logo-t-box.svg
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_vars.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/_user_util_links.html.erb
- app/views/shared/_banner.html.erb
- app/views/shared/_header_navbar.html.erb
- Updates styles for banner, logo navbar and red navbar
> First attempt at styling

- app/controllers/search_controller.rb
- app/search_engines/bento_search/blacklight_engine.rb
- app/search_engines/bento_search/books_engine.rb
- app/search_engines/bento_search/databases_engine.rb
- app/search_engines/bento_search/journals_engine.rb
- app/search_engines/bento_search/more_engine.rb
- app/search_engines/bento_search/primo_engine.rb
> Use bl-7 search_service for bento search engines.

- app/controllers/almaws_controller.rb
- Pass additional parameters into the comments field to make filling requests easier.
> BL-705 Digitization request params

- app/views/catalog/_refworks_form.html.erb
- Remove the red background color from refworks link
> BL-694 Refworks link on bookmarks page

- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_vars.scss
- app/helpers/application_helper.rb
- app/views/application/_navbar.html.erb
Styling for navigational header links
> Search toggle navbar

- app/controllers/search_controller.rb
- spec/models/search/solr/response_spec.rb
REF BL-348
* Remove some debugging code that is now causing failure.
* Clean up the Search::Solr::Response specs.
> [BL-348] Fix cdm controller, remove debugging.

- app/models/search_builder.rb
Remove patch required to fix issue in BL-6 using code from BL-7
> [BL-800] Remove temporary fix for BL-6

- app/assets/javascripts/application.js
- app/assets/stylesheets/partials/_bookmarks.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_requests.scss
- app/views/bookmarks/_show_tools.html.erb
- app/views/bookmarks/_sort_and_per_page.html.erb
- app/views/bookmarks/index.html.erb
- app/views/catalog/_citation.html.erb
- app/views/catalog/_grouped_citations.html.erb
- app/views/catalog/_previous_next_doc.html.erb
- app/views/catalog/_refworks_form.html.erb
- app/views/catalog/_show_tools.html.erb
- app/views/catalog/_single_citation.html.erb
- app/views/catalog/index.html.erb
Styles for bookmarks mobile views
> Bookmarks citations styles

- Rakefile
> Remove require causing error in libqa.

- lib/traject/macros/custom.rb
- spec/fixtures/no_245_field_present.xml
Fixes #1018
If document does not have a title truncate fails.
> Fix trying to get length on nil when no title present.

- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_pagination.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/almaws/_booking_allowed.html.erb
- app/views/almaws/_digitization_allowed.html.erb
- app/views/almaws/_hold_allowed.html.erb
- app/views/catalog/_check_holdings.html.erb
- app/views/catalog/index.html.erb
- add border to check_holdings table
- default request forms to be open if only one request option is available
- align LibrarySearch text with logo
- fix pagination margin on mobile screens
- make main container width wider on large screen sizes
> More style updates

- lib/traject/macros/custom.rb
- spec/lib/traject/traject_indexer_spec.rb
If record is supposed to be suppressed skip it instead of ingesting
it into solr.
> [BL-641] Skip suppressed record instead of ingesting.

- app/controllers/catalog_controller.rb
- app/lib/log_utils.rb
REF BL-820
See also tulibraries/tul_cob_playbook#48
> [BL-820] Add referer user-agent to api request logs.

- app/assets/stylesheets/partials/_facets.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_index_results.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/bento_search/_no_article_results.html.erb
- app/views/bento_search/_no_book_results.html.erb
- app/views/bento_search/_no_database_results.html.erb
- app/views/bento_search/_no_journal_results.html.erb
- app/views/catalog/_fields.html.erb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_search_results.html.erb
- app/views/catalog/_sort_and_per_page.html.erb
- app/views/catalog/facet.html.erb
- app/views/search/_suggestions.html.erb
- app/views/search/index.html.erb
- bento no results formatting
- format explanation divs in bento and index results
- sort and per page header
- availability label alignment
> Style updates

- app/assets/stylesheets/partials/_bookmarks.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/almaws/_resource_sharing_broker_allowed.html.erb
- app/views/catalog/_grouped_citations.html.erb
- app/views/catalog/_previous_next_doc.html.erb
- app/views/catalog/_show_default.html.erb
- app/views/catalog/_single_citation.html.erb
- app/views/catalog/_sort_and_per_page.html.erb
- app/views/primo_central/_show_availability_section.html.erb
- record page pagination search widget alignment
- adjust bookmark/cite/send to buttons padding
- ez borrow request form expands if it is the only option present
- Fix styles for availability panels in primo documents
- adjust citation modal styles
> BL-399 Style updates

- app/helpers/alma_data_helper.rb
- app/views/almaws/item.html.erb
- spec/helpers/alma_data_helper_spec.rb
- items with a physical_material_type of "Bound Issue" should display as "Libary Use Only"
- Items with a circulation_policy of "Music Restricted" should also be Library Use Only
> BL-844 Updates to availability_status method

- app/controllers/almaws_controller.rb
- app/controllers/catalog_controller.rb
- app/helpers/availability_helper.rb
- app/javascript/packs/controllers/availability_controller.js
- app/javascript/packs/controllers/show_controller.js
- app/models/solr_document.rb
- app/views/almaws/item.html.erb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_physical_availability_card.html.erb
- app/views/catalog/_show_availability_section.html.erb
- spec/helpers/availability_helper_spec.rb
- spec/javascript/README.md
- spec/javascript/packs/controllers/availability_controller.spec.js
This refactor allows most of the availability information to appear immediately and just adds the real-time availability with stimulus.
> Bl 815 filter locations suppressed items

- app/helpers/availability_helper.rb
- spec/helpers/availability_helper_spec.rb
- Refactor bound issue to be based on policy rather than material type
> BL-844 Library Use Only

- app/assets/stylesheets/partials/_header.scss
- app/helpers/application_helper.rb
- app/views/application/_navbar.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/search/index.html.erb
- app/views/shared/_banner.html.erb
- app/views/shared/_header_navbar.html.erb
- remove banner
- move FAQ link to red navbar
- add "Website" link to navigation menu
- remove explanation text from bento view
> BL-861 Updates to headers

- app/views/catalog/_search_form.html.erb
- app/views/shared/_header_navbar.html.erb
- Updates basic search form input to use blacklight 7 autofocus method
> Bl 859 update autofocus

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_index_results.scss
- app/assets/stylesheets/partials/_pagination.scss
- app/assets/stylesheets/tucob.scss.erb
- app/helpers/application_helper.rb
- app/views/almaws/item.html.erb
- app/views/catalog/_fields.html.erb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_physical_availability_card.html.erb
- app/views/catalog/_previous_next_doc.html.erb
- Adds back aeon request button and refactors it to use document data rather that the api
- Resize start over/back buttons
- Move pagination down on record pages
- Aligns available library wit the other index fields in search results
> BL-399 Additional style changes

- app/helpers/availability_helper.rb
- lib/traject/macros/custom.rb
- spec/fixtures/marc_files/lost_missing_technical.xml
- spec/helpers/availability_helper_spec.rb
- spec/lib/traject/traject_indexer_spec.rb
> [BL-852] Supress holdings/doc if holding in empty library.

- app/views/catalog/show.html.erb
-- Ensure nav tools appear on record pages when coming from a bento search
> BL-846 Bento links

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/helpers/availability_helper.rb
- app/lib/cob_alma/requests.rb
- config/libraries.yml
- config/locations.yml
- config/translation_maps/libraries_map.properties
- lib/traject/macros/custom.rb
- spec/fixtures/marc_files/lost_missing_technical.xml
- spec/lib/traject/traject_indexer_spec.rb
- Change library and location mappings for asrs items
- Update suppression methods
- Refactor campus logic to include ASRS library
> Bl 872 asrs mappings

- app/helpers/availability_helper.rb
> [BL-872] Hide the ASRS_TEST location.

- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_bookmarks.scss
- app/assets/stylesheets/partials/_header.scss
- app/views/bookmarks/_show_tools.html.erb
- app/views/bookmarks/_sort_and_per_page.html.erb
- app/views/catalog/_show_availability_section.html.erb
- app/views/catalog/_show_tools.html.erb
- spec/features/login_page_spec.rb
- spec/features/record_page_fields_spec.rb
- spec/fixtures/features.yml
- Add padding and make font-size consistent for nav tool buttons
- Adjust width of aeon request button to fit on one line
- Only render the 'request rapid access' button once on record show pages
> Bl 399 style updates 2

- app/controllers/databases_controller.rb
* Allow search with alternate titles.
* Fix title search not working.
> [BL-809] Fix az databases title search.

- app/assets/stylesheets/tucob.scss.erb
- app/controllers/users_controller.rb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- Give user a flash message explaining why they are unable to log in
- Continue to send general user errors to Honeybadger
> BL-873 Honeybadger user error

- app/models/blacklight/primo_central/search_builder_behavior.rb
Do not update known fields to be searched as "any" field.
> [BL-855] pass field through when known.

- app/assets/stylesheets/partials/_requests.scss
- Fix text color for hover, active, and visited states
> BL-399 ez borrow button

- app/helpers/catalog_helper.rb
- app/views/catalog/_availability_panel.html.erb
- app/views/catalog/_purchase_order_anonymous_button.html.erb
- app/views/catalog/_show_availability_section.html.erb
- app/views/catalog/purchase_order.html.erb
- spec/helpers/catalog_helper_spec.rb
- display text on show pages
- fix modal template
- remove table structure
- add classes to keep styles consistent with other availability panels
> BL-399 Purchase order styling

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/assets/stylesheets/partials/_colors.scss
- app/assets/stylesheets/partials/_requests.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/almaws/_resource_sharing_broker_allowed.html.erb
- app/views/catalog/_fields.html.erb
- app/views/catalog/_index_default.html.erb
- app/views/errors/not_found.html.erb
- app/views/layouts/blacklight.html.erb
- white color for ez borrow text
- display flash messages on main layout
- less space between images and availability display in search results
> BL-399 More style updates

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
BL-852 Don't display library for "EMPTY" in Javascript code
> Bl 852 other library

- app/helpers/catalog_helper.rb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_show_availability_section.html.erb
- spec/features/purcahse_order_spec.rb
- spec/helpers/catalog_helper_spec.rb
* Fixes databases az breaks when viewing database in show view.
* Fixes po availability not rendering login link.
* Adds some feature level tests for PO functionality.
> Fix render availability breaks databases.

- app/assets/stylesheets/partials/_header.scss
- app/helpers/application_helper.rb
- app/views/_user_util_links.html.erb
- app/views/almaws/item.html.erb
- app/views/catalog/_physical_availability_card.html.erb
- app/views/shared/_header_navbar.html.erb
- spec/helpers/application_helper_spec.rb
The red navbar is changing heights when logged in/out.  Adding a fixed height stops that behavior.
> Add height to red_navbar

- app/models/solr_document.rb
- spec/fixtures/vcr_cassettes/bento_search_blacklight.yml
Now that we truncate at ingest time we do not need to truncate at model.
This commit removes the duplicate truncation temporarily added while
transitioning to doing this at ingest time.
> [BL-619] do not duplicate truncation.

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/assets/stylesheets/partials/_availability.scss
- app/helpers/availability_helper.rb
- app/views/almaws/item.html.erb
- config/libraries.yml
- config/translation_maps/libraries_map.properties
- spec/helpers/availability_helper_spec.rb
- Adds a new method to display unavailable message for items located in MAIN, MEDIA, SCRC, DSC, and ASRS
- Change MAIN library name to Charles
- Remove the Paley mapping for ASRS items
> BL-883 Move-related changes

- app/assets/javascripts/availability.js
- app/views/catalog/_physical_availability_card.html.erb
- Use append to show more button once
> BL-881 multiple button bug

- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_bento.scss
- app/assets/stylesheets/partials/_record_pages.scss
- app/views/almaws/item.html.erb
- app/views/bookmarks/index.html.erb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_show_availability_section.html.erb
- app/views/layouts/_bento_box_wrapper.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/search/_bento_results.html.erb
- app/views/search/index.html.erb
- remove closing div tag from almaws/item
- add closing div to show_availability
- use html_safe characters for greater than symbols
-remove extra row class breaking IE
> Fix syntax errors

- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_facets.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_record_pages.scss
- app/views/almaws/item.html.erb
- app/views/catalog/_constraints_element.html.erb
- app/views/catalog/_facets.html.erb
- app/views/catalog/_physical_availability_card.html.erb
- app/views/catalog/_show_availability_section.html.erb
- app/views/catalog/_sort_and_per_page.html.erb
- app/views/catalog/index.html.erb
- app/views/shared/_header_navbar.html.erb
- Removes padding from record pages on small screen sizes
- Remove height for red navbar
- Adjusts padding and margins
> Fixes some style issues for mobile views

- config/locations.yml
- spec/helpers/availability_helper_spec.rb
- Updates location mappings for all libraries 
- Requires reindex
> BL-892 Update location mappings

- app/controllers/catalog_controller.rb
- app/views/errors/not_found.html.erb
- config/locales/en.yml
- Add back in the use of the invalid_document_id error 
- Update the text on the 404 error page
> BL-895 Record not found error

- app/controllers/databases_controller.rb
- app/helpers/catalog_helper.rb
- spec/helpers/catalog_helper_spec.rb
- Adds searchable link for database types to the individual database record page
> BL-810 Database display fields

- app/helpers/availability_helper.rb
- items located in m_reserve should display as available during move
> BL-902 Additional location change

- config/locations.yml
- Kardon locations prepend with remote storage
> BL-892 Update locations

- .travis.yml
The following changes worked for me when I tried them via a travis debug
session.
> Enable travis ci for tul_cob.

- .travis.yml
hold off until PR on playbook changing `.python-version` is merged (awaiting test suite run)
> Travis ci deploy

- app/controllers/databases_controller.rb
- app/views/catalog/_bookmark_control.html.erb
REF BL-809
REF BL-810
* Remove databases show document actions.
* Hide show_database_display
* Allow search by id
> [BL-809:810] More databases az updates.

- app/controllers/databases_advanced_controller.rb
- app/views/advanced/_advanced_search_facets.html.erb
* Do not show the subject facet.
* Label the format facet to match regular search.
> [Bl-809] Update database advanced search facets.

- Gemfile
- Gemfile.lock
This reverts commit e6db3378c7fceceee7fd831cdef03ac9434124f1.
> Revert "Bump puma from 3.12.1 to 4.0.0 (#1273)"

- app/controllers/almaws_controller.rb
- app/lib/cob_alma/requests.rb
- app/views/almaws/_asrs_request_form.html.erb
- app/views/almaws/_hold_request_form.html.erb
- config/locales/en.yml
- spec/fixtures/requests/blank_material_type.json
- spec/lib/cob_alma/requests_spec.rb
- spec/spec_helper.rb
- Make field optional, not required
- Only display field if there is more than one material type
- Filter out empty material types
> BL-890 Update material types form

- app/views/almaws/_booking_request_form.html.erb
- Add conditional logic to booking form so that we don't get a network error when material types is nil
> BL-890 Material types bug

- app/assets/stylesheets/partials/_bento.scss
- app/views/search/_bento_results.html.erb
- app/views/search/index.html.erb
- Update bento layout to use cards and card-column classes for better displays
> BL-923 Bento columns

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/helpers/availability_helper.rb
- Update library name for search results
- Remove call to temporary method already removed in a previous commit.
> BL-920 Remove temporary changes related to move

- Gemfile.lock
Reverts tulibraries/tul_cob#1325
> Revert "Bump honeybadger from 4.4.0 to 4.4.1"

- app/helpers/availability_helper.rb
- spec/helpers/availability_helper_spec.rb
- Updates the availaiblity display for requested items.
> BL-904 Requested status update

- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_bookmarks.scss
- app/assets/stylesheets/tucob.scss.erb
- app/lib/cob_alma/requests.rb
- app/views/almaws/_asrs_allowed.html.erb
- app/views/almaws/_asrs_request_form.html.erb
- app/views/almaws/_booking_allowed.html.erb
- app/views/almaws/_digitization_allowed.html.erb
- app/views/almaws/_hold_allowed.html.erb
- app/views/almaws/_resource_sharing_broker_allowed.html.erb
- config/locales/en.yml
- spec/lib/cob_alma/requests_spec.rb
- Updates background color for headers
- Text changes for Request headers
- Adds wait times for ASRS pickup locations
- Use Charles as default option for ASRS pickup locations
- Remove notes field from ASRS form
> BL-935 Request form updates

- app/controllers/almaws_controller.rb
- app/helpers/request_helper.rb
- app/views/shared/_flash_msg.html.erb
- config/locales/en.yml
- spec/helpers/request_helper_spec.rb
- Updates the text of the flash message a user received when they have made a successful request
- The text includes a link.  In order to display the link properly, we need to override the blacklight flash message template to use the sanitize method
- Also updates the styles for flash messages to be 75% width and centered.  
- Moves the close icon above the message instead of below.
> BL-941 Successful request message

- app/views/application/_mobile_nav.html.erb
- app/views/databases/_zero_results.html.erb
- app/views/shared/_header_navbar.html.erb
- config/application.rb
- config/locales/en.yml
- Update header links to point to production, not QA site
- Update links/text for no search results links
> BL-927 Update website links

- app/views/catalog/_search_results.html.erb
- config/locales/en.yml
- Edits text of the grey explanation box to include musical scores
- Adds margins to give a little space between the sidebar and the explanation div
> BL-952 Books and Media description

- app/assets/javascripts/availability.js
- app/assets/stylesheets/partials/_availability.scss
- app/views/almaws/item.html.erb
- app/views/catalog/_physical_availability_card.html.erb
- Fixes the alignment of the columns within the availaiblity tables
- Styles show more buttons to match the rest of the site
> BL-932 availability updates

- config/locales/en.yml
- Updates text displayed on the home page for /catalog
> BL-952 Books and more text

- app/assets/stylesheets/partials/_requests.scss
- app/views/shared/_header_navbar.html.erb
- Decrease font size for EZBorrow button
> BL-935 Request form changes

- app/helpers/request_helper.rb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_show_availability_section.html.erb
- Add back float for right side nav items in website navbar
- Remove margin-bottom from request button on index pages
> BL-930 Styles updates

- app/helpers/application_helper.rb
- app/views/search/_home_text.html.erb
- app/views/web_content/_home_text.html.erb
- config/locales/en.yml
- Updates the text for the everything home page and the website home page
> BL-958 Landing page updates

- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_record_pages.scss
- app/views/catalog/_previous_next_doc.html.erb
- app/views/catalog/show.html.erb
- Add padding back to red navbar at larger screen sizes
- Formats the start over/back to search tools on record pages
- Removes float from bookmarks on record pages
> BL-936 Mobile updates

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_mobilemenu.scss
- app/assets/stylesheets/partials/_users.scss
- app/views/shared/_header_navbar.html.erb
- app/views/users/_holds_details.html.erb
- app/views/users/_loans_details.html.erb
- app/views/users/_user_fines.html.erb
- app/views/users/account.html.erb
- app/views/users/renew_selected.js.erb
- config/locales/en.yml
- Update font family and sizes for my account page
- Update text/links from my account pages
- Adjust font-weight for Library Search header
- Add breakpoints and max widths to application css so that website navbar collapses at the right width
> BL-930 Style updates

- app/assets/stylesheets/partials/_header.scss
- app/views/shared/_header_navbar.html.erb
- Adjusted the float/padding for the red navbar to better match the library website
> BL-930 Fix website header

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_header.scss
- app/views/application/_mobile_nav.html.erb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_search_form.html.erb
- app/views/search/_bento_results.html.erb
- app/views/shared/_header_navbar.html.erb
- Fixes bug with filter icon not displaying between searches
- Remove breakpoints from website since they were breaking bento
- Adjust spacing/padding for start over/back to search links
> BL-936 More mobile updates

- app/assets/stylesheets/tucob.scss.erb
- app/views/shared/_footer.html.erb
- Updates address
- Fixes icons
> Footer fix

- config/locations.yml
- spec/helpers/availability_helper_spec.rb
- Update reference location external name
> BL-960 MAIN locations

- app/views/catalog/_show_primary_fields.html.erb
- app/views/catalog/_show_secondary_fields.html.erb
* Renders the field value using raw if the field is configured with :raw
attribute set to true.
> [BL-969] Use field raw value if :raw config set.

- app/assets/stylesheets/partials/_availability.scss
- app/helpers/catalog_helper.rb
- app/views/catalog/_online_availability.html.erb
- app/views/catalog/_online_availability_button.html.erb
- Updates borders and padding for various online availability displays, including search results and databases
> BL-968 Online availability displays

- app/assets/stylesheets/partials/_users.scss
- app/views/devise/sessions/new.html.erb
- app/views/shared/_header_navbar.html.erb
- Add current_user method to My Account link so that the need to log in message does not appear to users on the sign in page
- Updates styles for the login page
> BL-939 Login Updates

- app/assets/stylesheets/partials/_availability.scss
- Remove border-botom from online-list-items when they are in a dd
> BL-968 Online availability borders

- app/views/catalog/_show_secondary_fields.html.erb
- Change text of the secondary fields header to Details
> BL-932 Description header

- app/assets/stylesheets/partials/_availability.scss
- Add border-bottom to the online-list-item class
> BL-968 Online borders

- config/locations.yml
- spec/helpers/availability_helper_spec.rb
- Updates locations for MAIN juvenile, stacks, and storage to all display as Storage
> BL-964 BL-965 Update locations

- app/views/users/_user_info.html.erb
- app/views/users/account.html.erb
- Move items requested above items checked out in the user info section
- Move Request table above items table
> BL-970 Account page updates

- app/views/almaws/_digitization_request_form.html.erb
- Remove padding from end page field
> BL-935 Digitization form

- .env.prod
- .env.qa
- .env.stage
Avoid tul_cob_playbook PRs for deployments by managing the solr config
at the app level via .env variables.
> Manage solr url configs in .env files.

- .env.vagrant
(for testing and development purposes.)
> Add a vagrant specific .env file.

- Gemfile.lock
- app/views/users/_user_info.html.erb
- config/locales/en.yml
- Retrieves preferred user names from Alma
- Changes text for directions to update name
- Moves longer text blocks on account_info page into locales file
> BL-937 Use preferred names

- app/controllers/catalog_controller.rb
- Updates the text for the date range validation error and redirects them back to the page they were on, with root_path as a fallback_location
- Cleans up some extra spaces in the catalog controller
> BL-856 Date range validation

- app/views/primo_central/_home_text.html.erb
- app/views/primo_central/_zero_results.html.erb
- config/locales/en.yml
- Add citation link and descriptive text to the articles home page
- Add new unordered list to articles zero results page
> BL-982 Citations link

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/helpers/availability_helper.rb
This reverts commit 8f5df15556e3e4b3116f501b674fadddcd0f8877.
> Revert "BL-966 SCRC availability (#1380)"

- app/javascript/packs/controllers/explanation_controller.js
- Adds the web_content target and action to the stimulus controller so that clicking the hide link actually works
> BL-894 Web content hide link bug

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/helpers/availability_helper.rb
- app/views/primo_central/_home_text.html.erb
- app/views/primo_central/_zero_results.html.erb
- config/locales/en.yml
* Revert temporary SRC updates (BL-978)
* Add citation link and descriptive text to the articles home page (BL-982)
* Add new unordered list to articles zero results page (BL-982))
> Setup release v0.10.2

- app/controllers/almaws_controller.rb
- solr/conf/schema.xml
* [BL-991] Fixes solr schema to make web content data ingestible. (#1438)
* [BL-990] Fixes a request option bug. (#1432)
[BL-991]: https://tulibdev.atlassian.net/browse/BL-991
[BL-990]: https://tulibdev.atlassian.net/browse/BL-990
> Setup Release v0.10.3

- Gemfile
- Gemfile.lock
* .env.x files will get sourced automatically.
> Adds dotenv to tul_cob.

- app/views/users/_user_info.html.erb
- config/locales/en.yml
- Update text for link to update preferred name
- Move link underneath name
> BL-937 Account page changes

- app/assets/stylesheets/partials/_record_pages.scss
- app/assets/stylesheets/partials/_requests.scss
- app/views/almaws/_asrs_allowed.html.erb
- app/views/almaws/_booking_allowed.html.erb
- app/views/almaws/_digitization_allowed.html.erb
- app/views/almaws/_hold_allowed.html.erb
- app/views/almaws/_resource_sharing_broker_allowed.html.erb
- app/views/almaws/request_options.html.erb
- app/views/catalog/_show_secondary_fields.html.erb
- app/views/shared/_header_navbar.html.erb
- Fix aria value
- BL-934 Header structure
- Updates header tags to follow correct structure on individual record pages and request modals
- Updates styles so that element display the same as they did previously
> Bl 972 accessibiity review

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/assets/javascripts/listeners.js
- app/helpers/primo_central_helper.rb
- app/views/application/_mobile_nav.html.erb
- app/views/catalog/_online_availability_button.html.erb
- app/views/catalog/_show_availability_section.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/primo_central/_direct_link_button.html.erb
- app/views/search/_blacklight_availability.html.erb
- app/views/shared/_header_navbar.html.erb
- Updates the code to use both ids and classes
- Removes duplicate ids from code
- Adds new listeners for features that didn't exist before
- Removes listeners for elements that have been removed
- Sets timeout to allow availability to be loaded first
> Bl 973 refactor google analytics events

- app/lib/cob_alma/requests.rb
> BL-1002 Sort the selection description.

- app/lib/cob_alma/requests.rb
- spec/fixtures/requests/booking_locations.json
- spec/lib/cob_alma/requests_spec.rb
- spec/spec_helper.rb
- ASRS is currently displaying as a pickup location for booking requests.
- Refactors booking_location method to label ASRS as Charles Library
- Adds specs for this method
> BL-997 Booking request pickup locations

- app/assets/javascripts/application.js
- app/javascript/packs/controllers/availability_controller.js
- app/views/almaws/_asrs_request_form.html.erb
- app/views/almaws/_booking_request_form.html.erb
- app/views/almaws/_digitization_request_form.html.erb
- app/views/almaws/_hold_request_form.html.erb
- app/views/catalog/_index_availability_section.html.erb
- Adds the data disble_with feature to all of the request forms
- Adds a loading spinner to the request button that is removed once the modal is open
> BL-677 Interactive feedback on clicks

- app/helpers/catalog_helper.rb
- app/views/catalog/index.html.erb
- Use html_safe for icons displayed on individual record pages
- Remove grey borders that were introduced when the search-results class was created
> BL-905 fix display bugs

- app/assets/javascripts/listeners.js
- app/helpers/request_helper.rb
- Adds separate classes for request buttons in search results or record pages for request buttons so that clicks can be tracked separately in Google Analytics
> Bl 973 update request btns

- app/assets/javascripts/application.js
- app/views/catalog/_facets.html.erb
- app/views/catalog/_show_availability_section.html.erb
- Ensure that only 1 h2 "limit search" element is present at a time
- Add sr-only h2 to the availability section on full record pages
> BL-934 Header accessibility

- app/helpers/request_helper.rb
- app/javascript/packs/controllers/show_controller.js
- app/views/catalog/_show_availability_section.html.erb
- Adds the spinner functionality for the request button to record pages
> BL-677 Show spinner on record pages

- .circleci/deploy-prod.sh
Specify tag in the deployment to tul_cob.
Closes #1494
> Set -e rails_app_git_branch=$CIRCLE_TAG.

- app/controllers/almaws_controller.rb
- Fixes request bug related to nil request options
> set up release v.0.11.1 - attempt two

- app/assets/javascripts/application.js
> Location hash is usually empty, not undefined.

- app/views/journals/_zero_results.html.erb
- app/views/primo_central/_zero_results.html.erb
- config/locales/en.yml
- Adds additional text to journal and article no results templates
> BL-1007 Add text to no results templates

- app/helpers/availability_helper.rb
- app/views/almaws/item.html.erb
- app/views/catalog/_main_open_shelving_instructions.html.erb
- app/views/catalog/_physical_availability_card.html.erb
- config/locales/en.yml
- spec/features/availability_spec.rb
- spec/fixtures/availability_features.yml
- spec/fixtures/marc_fixture.xml
- Adds a blue banner with instructions for retreiving items found in MAIN open shelving
> BL-1001 Instructions for main open shelving

- app/helpers/availability_helper.rb
- app/views/almaws/item.html.erb
- spec/helpers/availability_helper_spec.rb
If location for item is "storage" then present user
“X In temporary storage — Recall item now”
Where link is to https://library.temple.edu//forms/storage-request
> [BL-1024] Request items held in overflow storage.

- config/locations.yml
- spec/helpers/availability_helper_spec.rb
- Updates the external names for Charles Library locations
> BL-1024 Labels for Charles

- app/assets/stylesheets/partials/_users.scss
- app/views/users/_loans_details.html.erb
- app/views/users/_user_loans.html.erb
- app/views/users/renew.html.erb
- Fixes the select all feature
- Removes unused partial
- Moves call number before due date
> BL-1014 Account page accessibility

- app/assets/stylesheets/partials/_availability.scss
- app/views/almaws/item.html.erb
- app/views/catalog/_physical_availability_card.html.erb
- Adds a fixed width to the first and last columns for better alignment
> BL-1031 Availability columns

- Gemfile
- Gemfile.lock
Fixes articles search breaking after BLv7.3.0 upgrade.
REF: https://github.com/projectblacklight/blacklight/issues/2192
> [BL-1038] Fix articles search breaking.

- app/assets/stylesheets/partials/_header.scss
- app/views/catalog/_show_tools.html.erb
- Updates nav show tools to render correctly at smaller screen sizes
> BL-1013 Full record page accessibility

- app/views/catalog/_asrs_instructions.html.erb
- app/views/catalog/_main_open_shelving_instructions.html.erb
- app/views/catalog/_scrc_instructions.html.erb
- Remove bottom margin from availability banners
> BL-1031 Avalability panels

- app/controllers/almaws_controller.rb
We haven't been logging these.  This PR corrects issue.
> Log the ASRS requests.

- .env.prod
- .env.stage
- app/controllers/almaws_controller.rb
* Swap solrs
* Log asrs requests
> Set up hotfix 0.12.2

- .env.prod
- .env.stage
> Set up release v0.12.4

- config/locations.yml
- Add new location for juvenile items
> BL-1055 Hirsch Collection

- app/views/catalog/_availability_panel.html.erb
- app/views/primo_central/_show_availability_section.html.erb
- Change online heading on individual record pages to be an h3 element for both catalog and articles
> BL-1053 Online header

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- BL-1060 Fixes issue where prev/next was not displaying on record pages
- BL-1041 Resolves the Back to Search button so that it goes to the previous results page
> Fixes for Blacklight bugs

- .env.prod
- .env.qa
- .env.stage
* Update prod and stage az urls to solrcloud.
* Set up solr-swap.
> Update solr urls.

- app/views/primo_central/_show_availability_section.html.erb
- Add sr-only header for individual articles
> BL-1053 Availability header on articles

- app/controllers/web_content_controller.rb
- Remove default_solr_params from web content controller
> BL-985 Web content solrconfig

- .env.prod
- .env.qa
- .env.stage
- app/controllers/web_content_controller.rb
> BL-1065 Use solrcloud for web-content.

- app/controllers/web_content_controller.rb
> BL-1065 Do not inherit catalog solr params into web content.

- app/views/almaws/_aeon_allowed.html.erb
- Need to add an additional argument to the aeon request form
> BL-1068 aeon request form bug

- app/views/almaws/_aeon_allowed.html.erb
- Need to add an additional argument to the aeon request form
> BL-1068 aeon request form bug (#1641)

- solr/conf/solrconfig.xml
Fixes catalog search broken on QA.
tulibraries/tul_cob-catalog-solr#10 is pending on some discussions.  In the meantime we need to update our local solrconfigs because these are still being used in QA.
> BL-673 Update local solr configs.

- .circleci/config.yml
- Makefile
- README.md
- bin/app-start.rb
- Updates ReadME
- Adds Makefile and commands
> Adds Makefile

- bin/app-start.rb
Run bundle install before starting app.
> Fix make up fail when gem not found.

- app/helpers/search_helper.rb
- spec/helpers/search_helper_spec.rb
- Update link to website when search query is empty
- Add specs for digital collections links
> BL-1061 Digital Collections bug

- .env.qa
- app/controllers/catalog_controller.rb
- app/controllers/databases_controller.rb
Also fixes controller not all fields queries.
And, updates local to point latest tul_cob-catalog-solr.
> Update qa solr to use new SC config.

- config/locations.yml
> BL-1105 DSS new location

- config/locales/en.yml
- Removes period from database link in the sidebar
> BL-1080 Update databases link

- spec/fixtures/marc_fixture.xml
Fix broken spec do to missing HLD field.
> Add HLD field to spec fixture.

- app/views/almaws/request_options.html.erb
- app/views/catalog/_zero_results.html.erb
- app/views/journals/_zero_results.html.erb
- app/views/primo_central/_zero_results.html.erb
- Removes Temple doesn't have it section from the no results partials for books and media, articles, and journals
- Removes the footer from the request options modal
> BL-1151 Temporarily remove links/sections

- app/assets/stylesheets/partials/_header.scss
- app/views/shared/_banner.html.erb
- app/views/shared/_header_navbar.html.erb
- config/locales/en.yml
- This adds a banner to the application due to the temporary closure
> BL-1150 adding banner

- app/views/devise/sessions/new.html.erb
- Add padding to the header element in the login modal
> BL-1128 Login modal styling

- Gemfile.lock
- spec/fixtures/service_notes.json
* Update e-services-notes (hopefully last time we do it this way)
* Bump cob_index (dev dependency only)
> Release v0.14.7

- app/assets/stylesheets/partials/_bookmarks.scss
- app/views/catalog/_index_default.html.erb
- Right align bookmark checkbox, cover images, and request buttons
> BL-1129 Search results alignment

- app/assets/stylesheets/tucob.scss.erb
- app/views/layouts/blacklight.html.erb
BL-1159 Add chat widget to librarysearch
> Bl 1159 chat widget

- config/locales/en.yml
- Updates text and links for the librarysearch banner
> BL-1160 update banner

- app/assets/stylesheets/icons.css.erb
- Adds icon for temporary resource database type
- Fixes issue with database reference type icon not displaying
> BL-1161 Temporary Resources icon

- app/assets/stylesheets/icons.css.erb
- Add icon to search results for temporary resources
> BL-1161 database icon

- config/application.rb
- lib/alma/config_utils.rb
- lib/tasks/server.rake
- spec/lib/alma_config_utils_spec.rb
* Abort if notes file is not found.
* look in /tmp folder by default.
> Update alma electronic task.

- app/assets/stylesheets/partials/_availability.scss
- app/helpers/availability_helper.rb
- app/helpers/catalog_helper.rb
- app/views/catalog/_index_availability_section.html.erb
- config/locales/en.yml
- spec/features/availability_spec.rb
- spec/helpers/catalog_helper_spec.rb
Includes URL params to pre-populate the form
Removes request button
> Add button to request help finding items online

- config/locales/en.yml
- spec/fixtures/service_notes.json
* Update banner (BL-1160)
* Update e-service-notes
> Set up hotfix release v0.14.8

- app/assets/stylesheets/partials/_availability.scss
- app/javascript/packs/controllers/availability_controller.js
- app/javascript/packs/controllers/show_controller.js
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_show_availability_section.html.erb
- spec/javascript/packs/controllers/availability_controller.spec.js
Update js tests to reflect no request button
Clean up some JS and CSS issues
> Remove request and add online help on show page

- Gemfile
- Gemfile.lock
- config/environments/production.rb
* configures cache_store to be memcached.
> BL-1131 Use local memcache.

- config/routes.rb
Adds missing concerns to the article search route.
> Fix articles search broken.

- Makefile
- bin/attach.sh
* Update restart to run bundle install and restart rails app.
* Add ps command
* Add attach command (for debugging purposes)
> Update Makefile commands.

- .env.prod
- .env.qa
- .env.stage
This reverts commit ec4fa4ef780ef962dd46e80eb09e8c671050328c.
Wait until full reindex is complete before switching URLs.
> Revert "Update sorl url links for next full-reindex."

- app/assets/stylesheets/partials/_availability.scss
- app/helpers/catalog_helper.rb
- config/application.rb
- config/locales/en.yml
Adds use of browser alias to application so it is picked up at start up.
Adds some media query fanciness for button padding on mobile.
> Switch button content for mobile using browser gem

- app/helpers/availability_helper.rb
- app/helpers/catalog_helper.rb
- config/application.rb
- config/locales/en.yml
- spec/features/availability_spec.rb
Reverts previously made changes.
Also, Remove blue banner for stacks
> Change temple help button text at all sizes

- .env.prod
- .env.qa
- .env.stage
Reverts tulibraries/tul_cob#1793
Re apply #1786
> Update sorl url links for next full-reindex.

- app/assets/stylesheets/partials/_availability.scss
- app/helpers/catalog_helper.rb
Fix a slight button drrop on small screens.
> Don't show button for archival materials

- app/helpers/catalog_helper.rb
- app/views/catalog/_hathitrust_button.html.erb
- app/views/catalog/_hathitrust_link.html.erb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_show_availability_section.html.erb
- config/locales/en.yml
- spec/helpers/catalog_helper_spec.rb
- Add hathitrust link to record pages and search results
- Build url for hathitrust link
- Update link text and add notes
> Bl 1168 hathitrust integration

- app/helpers/catalog_helper.rb
- spec/helpers/catalog_helper_spec.rb
- Hide digital request form button for items that have online or hathitrust links
> BL-1170 digital rquest form

- app/views/catalog/_hathitrust_link.html.erb
- config/locales/en.yml
- Add padding-top to hathitrust text
- Add Notes header to text
> BL-1169 Hathitrust display updates

- lib/tasks/server.rake
* Fix service notes not reloaded.
* Flush the cache to avoid old e-notes.
> Fix electronic notes reload task.

- app/views/search/_blacklight_availability.html.erb
- Adds online button to bento results for items with Hathitrust links
> BL-1168 Hathitrust on bento

- lib/tasks/server.rake
Fix undefined method 'clear' for nil.
> Do not clear nil cache.

- spec/fixtures/service_notes.json
Needed in case notes db fix does not work as expected.
> Merge "Update e-service-notes fixture." into master

- app/assets/stylesheets/tucob.scss.erb
- app/views/layouts/blacklight.html.erb
> BL-1177 Use new chat widget

- app/assets/stylesheets/tucob.scss.erb
- app/views/layouts/blacklight.html.erb
> BL-1177 Use new chat widget (#1843)

- .circleci/config.yml
- app/views/application/_mobile_nav.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/shared/_header_navbar.html.erb
Use https://librarysearch.temple.edu as the referer.
> BL-1186. Update referer in chat link.

- .circleci/config.yml
- app/helpers/catalog_helper.rb
- app/views/application/_mobile_nav.html.erb
- app/views/catalog/_electronic_notes.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/shared/_header_navbar.html.erb
- spec/helpers/catalog_helper_spec.rb
* Use db for e-notes
* Update referer links to chat widget
> Set up v1.0.0 release

- README.md
Documentation update to include better introduction
> tul_cob readme update

- .circleci/deploy-qa.sh
* Use --limit=app instead of --skip=solr so that it's more like production.
* Use the master branch instead of default set by playbook.
> Update qa build to use master branch.

- app/models/blacklight/primo_central/document.rb
* Update primo record id to mapping to use pnx/control/recordid
> BL-1215 Use correct primo doc id mapping.

- app/assets/stylesheets/partials/_bento.scss
- app/views/search/_digital_collections.html.erb
- app/views/search/_research_guides_faq.html.erb
- app/views/search/_resource_types.html.erb
- config/locales/en.yml
- Updates text for digital collections header
- Updates facet label for digital collections to be digitized collections
> BL-1184 Bento display changes

- app/assets/javascripts/listeners.js
- app/views/catalog/_hathitrust_link.html.erb
* Add tracking for digital help button.
* Add tracking for hathytrust link
* Add tracking for google preview button.
> BL-1191: Add Google Tracking

- config/locations.yml
-Update display for location text for new code
> BL-1193 new location code

- app/assets/stylesheets/partials/_vars.scss
- app/views/search/_digital_collections.html.erb
- app/views/search/_research_guides_faq.html.erb
- app/views/search/_resource_types.html.erb
- Use same color grey for headers
- Add more padding between resource type headers
> BL-1184 Bento updates

- .docker/app/Dockerfile
- README.md
REF: https://github.com/pry/pry/issues/1248#issuecomment-366056015
> Fixes issue with pry not working.

- .circleci/deploy-prod.sh
- .circleci/deploy-qa.sh
- .circleci/deploy-stage.sh
Removes executable bit from .vault file to stop CI from throwing error
on deployment.
> BL-1201: Fix airflow variable deploy

- doc/Alma-to-[Indexing-Process]-to-Solr(s)-Notes.md
- doc/README.md
- doc/Setting-up-a-release-candidate.md
- doc/Solr-Document-Suppression.md
- doc/Swapping-Solr-Instance-On-Production-Server.md
- doc/User-interaction-with-Alma.md
- doc/dataflow-docs.md
- doc/deployment-process.md
- doc/new-release-process.md
* Moves and updates files in tul_cob.wiki into doc/ folder.
> DEVO-106: Move our wiki into doc/

- app/assets/stylesheets/partials/_bookmarks.scss
- app/views/bookmarks/index.html.erb
Per @ebtoner , Adjusted margins to allow alignment of headings to match My Account page.
> #BL-1192 Add notification about articles bookmarks sunsetting

- app/helpers/search_helper.rb
- app/search_engines/bento_search/cdm_engine.rb
- spec/helpers/search_helper_spec.rb
- spec/search_engines/cdm_seach_spec.rb
* Substitute forward slash with " "
* Better CDM specific error handling.
> BL-1256: Fix CDM slash error.

- app/helpers/catalog_helper.rb
Update icon mappings in catalog helper for missing mappings.
> #BL-1231 CDI thumbnail tweak

- app/assets/stylesheets/icons.css.erb
Update styles to use reference icon only on Type not Subject.
> #BL-1067 databases A-Z: reference icon issue for type and subject facet

- app/controllers/almaws_controller.rb
- app/helpers/availability_helper.rb
- spec/helpers/availability_helper_spec.rb
Addresses Issue BL-358
- Expand Alma query to get due_date from holding
- Parse date string to display in common mm/dd/yyyy format (Jira Issues specifies m/d/yyyy)
> #BL-358 Display due date in availability

- app/assets/stylesheets/partials/_requests.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/almaws/request_options.html.erb
Adjusted alignment of text items on request options pop-up.
> #BL-1262 Styling - Body Paragraph sections need to be vertically aligned

- app/assets/stylesheets/icons.css.erb
- app/views/almaws/_aeon_allowed.html.erb
- app/views/almaws/_asrs_allowed.html.erb
- app/views/almaws/_booking_allowed.html.erb
- app/views/almaws/_digital_copy_help.html.erb
- app/views/almaws/_digitization_allowed.html.erb
- app/views/almaws/_hold_allowed.html.erb
- app/views/almaws/_open_shelves.html.erb
- app/views/almaws/_resource_sharing_broker_allowed.html.erb
Needed to set initial state of aria-expanded.
> #BL-1259 Styling - Carrot does not reflect auto expanded section

- app/helpers/availability_helper.rb
- spec/helpers/availability_helper_spec.rb
* Adds new availability status.
> BL-1074: Add Awaiting Reshelving Status.

- app/search_engines/bento_search/primo_engine.rb
> BL-1247 fix numFound setting in empty primo response

- app/helpers/availability_helper.rb
- app/helpers/catalog_helper.rb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_show_availability_section.html.erb
- spec/helpers/availability_helper_spec.rb
* When we're back on campus, enable recall link for unavailable items.
> [BL-1245] Feature flag enable recall link.

- app/controllers/primo_central_controller.rb
- app/helpers/catalog_helper.rb
* Sets up sun-setting article bookmarks.
> BL-1237: Remove option to add new article bookmarks.

- config/locales/en.yml
- Updates text on the request modal button from Cancel to Close
> BL-1261 Request cancel button update

- app/assets/stylesheets/partials/_requests.scss
- app/views/almaws/_booking_request_form.html.erb
- app/views/almaws/_digitization_request_form.html.erb
- app/views/almaws/_hold_request_form.html.erb
- Adds a new line between label and additional information on various request forms
> BL-1275 Add new line to form text

- app/views/almaws/_aeon_allowed.html.erb
- Removes the pb-0 class from the aeon form since it is no longer the last option
> BL-1268 Add padding to aeon panel

- app/components/facet_item_component.rb
Add class name of resource type to selected facet span.
> #BL-1276 Facet icons disappear when selected

- app/views/almaws/_asrs_request_form.html.erb
- Adds new line for additional text in asrs form
> BL-1275 Update asrs form

- app/views/shared/_header_navbar.html.erb
- Remove banner display for the reopening
> BL-1281 Remove banner

- app/models/search_builder.rb
Temporary patch. We will remove this once we are on a new fixed solr
config.
> Add suppression query.

- app/helpers/catalog_helper.rb
- spec/helpers/catalog_helper_spec.rb
- Adds more relevant locations for the open shelves request modal tab
> Bl 1279 ADD MORE open shelves

- config/locales/en.yml
- Updates text for sunsetting article bookmarks
> BL-1285 Update bookmarks message

- config/locations.yml
This is a minor tweak that I realized needs to be included in addition to changes for BL-1288.
> Updated MAIN reserve location name for temporary changes

- app/helpers/catalog_helper.rb
- spec/helpers/catalog_helper_spec.rb
- Tighten the logic so that we don't get unintended matches between libraries and locations
> BL-1291 Find it on the shelves message refactor

- app/controllers/lib_guides_controller.rb
- app/models/lib_guides_api.rb
- config/application.rb
- config/lib_guides.yml
- config/routes.rb
- spec/controllers/lib_guides_controller_spec.rb
- spec/models/lib_guides_api_spec.rb
- Sets up basic route, controller, and model for Lib Guides API
> BL-1307 Lib Guides endpoint

- app/controllers/bookmarks_controller.rb
- app/helpers/bookmark_helper.rb
- app/views/bookmarks/_show_tools.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/bookmarks_controller_spec.rb
- spec/helpers/bookmark_helper_spec.rb
Add temporary feature add allow users to export their bookmarks.
> BL-1297: Add export article bookmarks button.

- app/lib/cob_alma/requests.rb
- Removes Law Library from being part of main campus so that utems can be requested for pickup at Charles.
> BL-1312 Law Library

- app/helpers/bookmark_helper.rb
- app/views/bookmarks/_show_tools.html.erb
- config/locales/en.yml
- spec/helpers/bookmark_helper_spec.rb
* Remove export bookmark button
* Add export bookmark link to bookmarks page.
> [BL-1297] Add export bookmarks link.

- app/assets/stylesheets/partials/_bento.scss
- app/assets/stylesheets/partials/_lib_guides.scss
- app/controllers/search_controller.rb
- app/views/catalog/_lib_guide_recommender_catalog.html.erb
- app/views/search/_bento_results.html.erb
- app/views/search/_lib_guide_recommender_bento.html.erb
- app/views/search/index.html.erb
- Basic view partials for the lib guides recommender.
> BL-1315 View templates

- app/models/search_builder.rb
- app/search_engines/bento_search/books_and_media_engine.rb
We were not adding suppress filter in search engine context.
> BL-1317: Fix suppressed record showing up in bento context.

- app/assets/stylesheets/partials/_bento.scss
- app/javascript/packs/controllers/lib-guides_controller.js
- app/models/lib_guides_api.rb
- app/views/catalog/_lib_guide_recommender_catalog.html.erb
- app/views/catalog/index.html.erb
- app/views/search/_bento_results.html.erb
- app/views/search/_lib_guide_recommender_bento.html.erb
- app/views/search/index.html.erb
client side controller for loading lib guide data. the librarian section is missing some fields that exist in the mockups but not in the api. 
Still needs error handling, tests, etc.
> BL-1306 javascript for libguides recommender

- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/partials/_lib_guides.scss
- app/controllers/search_controller.rb
- app/views/search/_lib_guide_recommender_bento.html.erb
- Styles the lib-guides section for the bento page
> BL-1313 Bento lib-guides styles

- app/assets/stylesheets/partials/_index_results.scss
- app/assets/stylesheets/partials/_lib_guides.scss
- app/views/catalog/_lib_guide_recommender_catalog.html.erb
- Combines styles used in both bento and catalog PRs
- Fixes some issues overlooked previously
> Lib guides styling

- .env
Bump to catalog solr collection to 5.1.0.v0.6.3-2020-09-11_19-05-07
> Update catalog solr collection

- app/controllers/catalog_controller.rb
- app/helpers/facets_helper.rb
- app/views/advanced/_advanced_search_facets.html.erb
- spec/helpers/facets_helper_spec.rb
* Requires collection tul_cob-catalog-5.1.0.v0.6.3-2020-09-11_19-05-07 or
above.
> BL-1052: Add nested location facet.

- app/helpers/facets_helper.rb
- app/views/catalog/_constraints.html.erb
- spec/helpers/facets_helper_spec.rb
Use library location label maps in constraints section.
> BL-1052: Map location facet constraints

- app/presenters/facet_item_presenter.rb
- spec/presenters/facet_item_presenter_spec.rb
this should take care of the recent slow down in facet rendering.
> refactor so as not to create expensive search state objects

- app/views/catalog/_lib_guide_recommender_catalog.html.erb
- app/views/lib_guides/index.html.erb
- app/views/search/_lib_guide_recommender_bento.html.erb
- Adds back email to librarian section
- Fixes styling issue before content is loaded
> BL-1320 Lib Guide changes

- app/helpers/catalog_helper.rb
- app/lib/feature_flags.rb
- config/initializers/features.rb
- spec/helpers/catalog_helper_spec.rb
- spec/lib/feature_flags_spec.rb
> Add new with_libguides?/with_call_number_facet? feature flags.

- app/controllers/catalog_controller.rb
- app/views/catalog/_lib_guide_section.html.erb
- app/views/search/_bento_results.html.erb
- spec/features/indices_spec.rb
> Put libguides and lc facet behind feature flags

- app/views/lib_guides/index.html.erb
- Fixes the link for librians when there are no search results int he bento view
> BL-1320 Fix link

- app/assets/stylesheets/partials/_facets.scss
- app/controllers/catalog_controller.rb
- app/presenters/facet_item_presenter.rb
- app/views/advanced/_advanced_search_facets.html.erb
- spec/presenters/facet_item_presenter_spec.rb
Only brings to parity with current broken solution.
> Fix advanced search library faceting.

- app/controllers/almaws_controller.rb
- There have been several notifications of asrs requests not going through.  This will hopefully give us more information about why the bug is happening.
> BL-1336 Request bug

- app/views/almaws/_asrs_request_form.html.erb
- app/views/almaws/_booking_request_form.html.erb
- app/views/almaws/_digitization_request_form.html.erb
- app/views/almaws/_hold_request_form.html.erb
- Updates the way we check for description count in all request forms
- Updates the params[:description] in all non-asrs request forms
> BL-1337 Descriptions request form bug

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_facets.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_index_results.scss
- app/views/catalog/_facets.html.erb
- We haven't been using the default blacklight styles.  This adds them to the application.scss file
> BL-1340 Import Blacklight stylesheet

- Gemfile.lock
- lib/tasks/tulsearch.rake
AZ specs are failing because az solr db is failing to get ingested.
* Update cob_az_index to fix ingest failure.
* Use system() vs . `` to make sure we fail if ingest step fails.
> Update cob_az_index and use system instead of

- .circleci/config.yml
- Makefile
Update make commands to behave according to the environment vs different
commands per environment.
> DEVO-107 Use same commands on CI as we do locally.

- app/views/catalog/_search_suggestions.html.erb
- config/locales/en.yml
- Adds a link to the books and media no results page
> BL-1327 Add no results link

- app/controllers/lib_guides_controller.rb
* Will make easier to test lib_guides.
> BL-1353: Allow format=json for lib_guides enpoint

- app/assets/stylesheets/partials/_facets.scss
- Adjusts spacing and font-size for facet headings
> BL-1340 Update styles

- app/controllers/catalog_controller.rb
- app/views/catalog/_explanation_div.html.erb
- app/views/catalog/_lc_sort_div.html.erb
- app/views/catalog/_search_results.html.erb
- Adds lc_call_number field to search results when sorting by lc classification.
- Adds a box to the top of the search results that displays to the user that they are using lc sorting.
- Box includes a link to remove lc sort
> BL-1350 LC Display Field

- app/models/blacklight/alma/response.rb
- app/models/blacklight/primo_central/response.rb
Hard to tell where this error message is coming from.
> Fix ambiguous error message.

- Makefile
- README.md
- app/controllers/lib_guides_controller.rb
- app/controllers/search_controller.rb
- app/helpers/catalog_helper.rb
- app/models/lib_guides_api.rb
- app/views/search/_bento_results.html.erb
- spec/helpers/catalog_helper_spec.rb
- spec/relavance/lib_guides_spec.rb
- spec/spec_helper.rb
* Skip running on CI
* Idea is to trigger this on QA or locally but referencing prod Solr.
> [BL-1341] Create relevance tests for libguides.

- app/assets/javascripts/application.js
- app/assets/stylesheets/partials/_record_pages.scss
- app/helpers/catalog_helper.rb
* Add "Search: " to subject link titles.
* Remove decorations for subject links (avoids weird sub visited link
selected)
* Remove some un-uses javascript selector.
> BL-1166 Update subject link title.

- app/assets/stylesheets/partials/_index_results.scss
- app/helpers/catalog_helper.rb
- app/views/catalog/_online_availability_button.html.erb
- Fixes alignment for availability index fields
- Adjusts the grey background to be smaller
- Adds padding between metadata fields and online button in search results
> BL-1350 LC display field in search results

- app/assets/stylesheets/partials/_index_results.scss
- app/helpers/catalog_helper.rb
- Adds border-radius
- Changes background color
- Adds padding
> BL-1350 Style updates lc_display field

- app/lib/cob_alma/requests.rb
- spec/lib/cob_alma/requests_spec.rb
Revised https://github.com/tulibraries/tul_cob/pull/2290
> BL-1372 don't exclude MAIN campus from valid pickup locations

- config/locales/devise.en.yml
- spec/features/login_page_spec.rb
> BL-1374 Update login links

- app/assets/javascripts/listeners.js
- app/components/facet_item_pivot_component.rb
- Adds trackers for pivot facet elements(outer, inner, and expand button)
> BL-1354 Google Analytics tracking

- app/assets/stylesheets/partials/_bookmarks.scss
- app/controllers/bookmarks_controller.rb
- app/helpers/bookmark_helper.rb
- app/models/user.rb
- app/views/catalog/_document.html.erb
- spec/controllers/bookmarks_controller_spec.rb
- spec/models/user_spec.rb
* Also removes more unnecessary article bookmark code.
* Fixes one styling issue that was causing font to be white in select button.
> BL-1298: Do not count article bookmarks.

- config/locales/en.yml
- Updates text at the top of the bookmarks page
> BL-1378 Update bookmarks text

- app/assets/stylesheets/partials/_bookmarks.scss
- app/helpers/bookmark_helper.rb
- app/views/bookmarks/_show_tools.html.erb
- config/locales/en.yml
- spec/helpers/bookmark_helper_spec.rb
* And, fix cite button font size.
> BL-1298: Add cite range.

- app/assets/stylesheets/partials/_sms_form.scss
- app/helpers/availability_helper.rb
- app/models/solr_document.rb
- app/views/almaws/_location_field.html.erb
- app/views/almaws/_location_selector.html.erb
- app/views/catalog/_sms_form.html.erb
- spec/helpers/availability_helper_spec.rb
- spec/models/solr_document_spec.rb
- Fixes broken location
- Removes title
- Updates display to use dashes instead of parentheses
> BL-1352 Clean up text this modal

- app/views/almaws/_location_field.html.erb
- Use curent_library to get library name
> BL-1352 Text this modal

- app/helpers/availability_helper.rb
- app/models/solr_document.rb
- app/views/almaws/_location_selector.html.erb
- spec/models/solr_document_spec.rb
- Adds a raw_library field so that we can access the code in the location helper method
> BL-1352 Text modal changes

- app/assets/stylesheets/partials/_bookmarks.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_vars.scss
- app/views/bookmarks/_show_tools.html.erb
- app/views/catalog/_citation.html.erb
- app/views/catalog/_grouped_citations.html.erb
- app/views/catalog/_show_tools.html.erb
- config/locales/en.yml
* Update cite and sendto styling to match other buttons on bookmarks and show page.
> BL-1298 styling changes.

- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_bento.scss
- app/views/primo_central/_libkey_btn.html.erb
- app/views/primo_central/_online_button.html.erb
- app/views/primo_central/_show_availability_section.html.erb
- app/views/search/_primo_availability.html.erb
- config/locales/en.yml
- Initial style work for libkey button
- BL-1384 Libkey button for article show pages
- BL-1383 Add libkey button to article search results page
- BL-1382 Add libkey button to bento
- Use feature flag to hide display
> Bl 1371 libkey front end integration

- app/models/user.rb
- spec/models/user_spec.rb
Fixes bug introduced with we overrode User#bookmarks method.
> BL-1298: Fix user login bug.

- app/controllers/primo_central_controller.rb
- config/routes.rb
- spec/controllers/primo_central_controller_spec.rb
> BL-1381: Add libkey integration action to primo controller.

- app/assets/stylesheets/partials/_sms_form.scss
- app/helpers/availability_helper.rb
- app/models/solr_document.rb
- app/views/almaws/_location_field.html.erb
- app/views/almaws/_location_selector.html.erb
- Add raw_location to properly render locations both in the display and the text message
- Align radio button to the top line for multiple items
- Updates styling
> BL-1352 Text this modal changes

- app/views/primo_central/_libkey_btn.html.erb
- app/views/search/_primo_availability.html.erb
- config/locales/en.yml
- limit button display to articles with doi
- adds correct link to button
> BL-1370 Libkey integration

- app/models/blacklight/primo_central/document.rb
- spec/helpers/bookmark_helper_spec.rb
- spec/models/primo_central_document_spec.rb
Found some more code to remove now that we are getting rid of article
bookmarks.
> BL-1298: More unused article bookmarks code.

- Gemfile
- Gemfile.lock
- Devise has not yet merged the PR to work with omniauth 2.  The maintainer recommends using this branch in the meantime.
> Pin devise to branch

- Makefile
* Also, remove unused env variables.
* And, mount secrets.config.
> Sort env variables.

- Gemfile
- Gemfile.lock
- spec/features/login_page_spec.rb
This reverts commit 8a58368b7aa170e67572761118e2866c8ed6f745.
* Adds a regression spec
> [BL-1415] Revert "Pin devise to branch"

- Gemfile
- Gemfile.lock
- app/views/devise/sessions/new.html.erb
- spec/features/login_page_spec.rb
* Updates devise
* Fixes "Not found. Authentication passthru."
> [BL-1416] Update devise and fix shib path broken.

- Gemfile
- Gemfile.lock
- app/views/devise/sessions/new.html.erb
This reverts commit 7cbd9fdb272b5404461a8517d6ce8394cf29d75b.
> Revert "[BL-1416] Update devise and fix shib path broken."

- app/lib/cob_alma/requests.rb
- spec/lib/cob_alma/requests_spec.rb
- Refactors item_level_locations method to allow for curbside pickup at Charles
> BL-1390 Item level pickup locations

- app/assets/javascripts/book_covers.js
- Updates the code to not display link for items with noview
> BL-1397 Google books preview

- app/helpers/application_helper.rb
- app/search_engines/bento_search/books_and_media_engine.rb
- spec/search_engines/books_and_media_search_spec.rb
* Fixes regression that removed online totals link from the books and
media bento box.
> BL-1394: Add online totals link to books and media bento.

- app/models/user.rb
- Adds Japan faculty to the list of users that can use the purchase order feature
> BL-1414 Purchase order bug

- app/models/purchase_order_mailer.rb
- app/views/catalog/purchase_order.html.erb
- app/views/purchase_order_mailer/purchase_order.text.erb
- config/locales/en.yml
- Updates text for various messages related to the purchase order feature
> BL-1393 Purchase order wording

- app/assets/stylesheets/partials/_bookmarks.scss
- Align bookmarks checkbox to the left in mobile views
> BL-1403 Mobile styling change

- app/controllers/sessions_controller.rb
- app/helpers/catalog_helper.rb
- app/views/devise/sessions/new.html.erb
- config/locales/devise.en.yml
- spec/helpers/catalog_helper_spec.rb
- Adds a Continue as guest link
- Includes prepopulated fields for title, date, and edition if applicable
> BL-1419 Add guest link to login page

- app/controllers/catalog_controller.rb
- app/controllers/web_content_controller.rb
- app/models/books_search_builder.rb
- app/models/journals_search_builder.rb
- app/models/search_builder.rb
- app/search_engines/bento_search/books_and_media_engine.rb
- spec/models/books_search_builder_spec.rb
- spec/search_engines/books_and_media_search_spec.rb
* Fixes books media bento totals not matching books media search totals.
> BL-1421: Always supress journals in book media context.

- app/assets/stylesheets/partials/_bookmarks.scss
- Makes bookmark div clickable
- Hides actual checkbox
- Adjusts padding and font-size for bookmarks
> BL-1403 Bookmark button on mobile

- app/assets/stylesheets/partials/_bookmarks.scss
- app/assets/stylesheets/partials/_header.scss
- Limit hiding the checkbox to record pages only
- Remove highlight from click for sendto menu items
> BL-1403 Mobile styles

- app/views/layouts/blacklight.html.erb
- Updates code to use Blacklight implementation of this feature
> BL-1430 Keyboard navigation update

- Gemfile
- Gemfile.lock
- app/views/devise/sessions/new.html.erb
- config/initializers/devise.rb
* Updates devise without breaking the shib login.
> BL-1416: Update devise.

- Gemfile
- Gemfile.lock
Update blacklight_range_limit with fix for the update sort bug issue.
REF: projectblacklight/blacklight_range_limit#168
> BL-1431: Fix pub date sort bug.

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- package.json
- yarn.lock
The bootstrap-select library is interfering with the accessibility use
case of drop-down select menus.  Removing it from our app fixes the
issue.
> BL-1133: Fix drop-down selection accessibility issue.

- yarn.lock
When I run the yarn command locally it's updating yarn.lock
This change commits that update.
> Add yarn update changes.

- app/controllers/application_controller.rb
- Adds librarian_view to the manifold_alerts before_action
> BL-1467 Broken staff view

- config/devise.yml
- config/initializers/devise.rb
* Also makes some more saml config configurable via rails config file.
> Update ipd_sso_service_url to correct value.

- app/helpers/users_helper.rb
- app/views/devise/sessions/new.html.erb
- spec/helpers/users_helper_spec.rb
This makes it a little more stream lined.
> Switch dynamically between Shib and Saml logins.

- Gemfile.lock
- app/controllers/catalog_controller.rb
- app/helpers/catalog_helper.rb
- spec/features/record_page_fields_spec.rb
- spec/helpers/catalog_helper_spec.rb
- We have been indexing the same mapping for genre_display to three different fields. We updated cob_index to use one multivalued field that both stores and indexes data.  This updates the app to use the new field and removes the extra one
> BL-1319 Update genre fields

- .docker/app/Dockerfile.prod
> Update mariadb-dev (10.5.11-r0)

- .docker/app/Dockerfile.prod
- .gitlab-ci.yml
* Revert "Revert to old harbor image to fix pipeline fails"
* Update gitlab config to use docker-20
This reverts commit 78d6cbed1457b3363ab2562460197ea329feabc6.
> Unpin production ruby container.

- app/helpers/application_helper.rb
- app/views/catalog/_record_page_query_lists.html.erb
- app/views/catalog/_show_default.html.erb
- app/views/query_list/show.html.erb
- app/views/search/_query_list.html.erb
- spec/features/query_list_spec.rb
- spec/helpers/application_helper_spec.rb
- Adds creator and call number query_lists to the record pages for catalog and journal documents
> BL-1519 Record page query lists

- app/controllers/sessions_controller.rb
- spec/controllers/sessions_controller_spec.rb
Fixes treating an array as if it were a SolrDocument instance.
> BL-1480 Fix redirect database error.

- app/controllers/catalog_controller.rb
- Adds newly added faceet and sort fields to the controller
> BL-1473 Add new fields for date_added

- app/views/catalog/_home_text.html.erb
- app/views/search/_home_text.html.erb
- app/views/search/_query_list.html.erb
- app/views/search/index.html.erb
- spec/features/query_list_spec.rb
- Removes query lists from bento results
- Adds new materials query lists to bento and catalog home pages
> BL-1520 Query list refactoring

- app/controllers/catalog_controller.rb
I noticed some things that I forgot / didn't think to include in the original ticket requirements. Adding them here.
> BL-1473 Update labels/ordering for Newly Added filter and sort

- app/helpers/application_helper.rb
- app/models/search_builder.rb
- spec/helpers/application_helper_spec.rb
- spec/models/search_builder_spec.rb
* Add filter query to remove any results that mach id of current doc.
> BL-1531: Filter out current item in query_list results.

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_query_lists.scss
- app/helpers/application_helper.rb
- app/views/query_list/_results.html.erb
- app/views/query_list/show.html.erb
- spec/helpers/application_helper_spec.rb
- Adds basic styles for the query  list sets
> BL-1521 Query list styling

- app/views/catalog/_home_text.html.erb
- app/views/search/_home_text.html.erb
- app/views/search/_query_list.html.erb
- Moves query lists on home pages
- Adds the one_month facet parameter to the new item queries
> BL-1520 Query list refactor

- Gemfile.lock
- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
- Use pub_date_sort for author queries
- Strip whitespace from call_number field
> BL-1519 Record page query list updates

- app/assets/stylesheets/partials/_advanced.scss
- app/views/advanced/_advanced_search_facets.html.erb
- app/views/catalog/_search_form.html.erb
- app/views/primo_advanced/_advanced_search_fields.html.erb
- Adds contrast to facet colors
- Fixes broken placeholder text
- Updates label to be readable by screen readers
> BL-1411 Advanced search accessibility

- app/assets/stylesheets/partials/_query_lists.scss
- app/views/query_list/show.html.erb
- config/locales/en.yml
- Adds text when query lists have no results
> BL-1535 Query list no results

- app/helpers/web_content_helper.rb
- spec/helpers/web_content_helper_spec.rb
Fixes BL-1406
Wraps li tags with ul to resolve accessibility issue.
> BL-1406: Wrap <li> in <ul>

- app/controllers/catalog_controller.rb
- app/presenters/classification_field_presenter.rb
- spec/presenters/classification_field_presenter_spec.rb
I removed a the :collapsing config from the lc_facet config by mistake.
This adds it back plus refactors tests.
> BL-1541: Reset collapsing config to true.

- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/partials/_query_lists.scss
- app/helpers/application_helper.rb
- app/views/query_list/_results.html.erb
- app/views/query_list/show.html.erb
- spec/helpers/application_helper_spec.rb
- Also adds back some changes from the link PR that were lost in a merge conflict resolution
> BL-1538 Style updates

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
* Remove donor_info_display field
* Remove feature flag from query links
> BL-1543: Aug 2021 Release Final updates.

- app/assets/stylesheets/partials/_query_lists.scss
- app/views/catalog/_show_default.html.erb
- config/locales/en.yml
Add text "Help us improve this new feature in development! [Tell us what you think of the related items shown below](https://temple.libwizard.com/f/Library_search_feedback)"
> Bl 1542 add feedback text

- app/views/query_list/show.html.erb
- spec/features/query_list_spec.rb
- Removes view more when less than 5 results
- Removes extra no results text
- Remove unused path from specs
> BL-1539 More updates

- app/search_engines/bento_search/web_content_engine.rb
> BL-1547 Web content view all bug

- app/assets/stylesheets/partials/_header.scss
- config/locales/en.yml
Update label to include expiration date, plus some minor styling adjustments to accommodate the new text length.
> BL-1552 Update Refworks label, with styling adjustments

- app/controllers/catalog_controller.rb
- app/helpers/catalog_helper.rb
- Adds existing do_with_json_logger method to the purchase order requests 
- Fixes bug with the button where the text was not displaying when a user was logged in
> BL-1562 Log purchase order requests

- app/views/catalog/_show_default.html.erb
- Flip image to right side
- Float text to left
- Make details section full width
> BL-1568 Record page updates

- app/models/concerns/blacklight/document/email.rb
- app/models/solr_document.rb
- config/locales/en.yml
- spec/models/blacklight/document/email_spec.rb
- spec/models/solr_document_spec.rb
- Display contributor names instead of json 
- Adds new imprint fields
- Adds tests for email concern
> BL-150 Email body data update

- app/controllers/catalog_controller.rb
Use genre_t for advanced search
> BL-1586 Genre bug

- app/assets/javascripts/application.js
- app/views/catalog/_show_default.html.erb
- app/views/catalog/_show_primary_fields.html.erb
- config/locales/en.yml
- Adds an anchor link to browse related items
- Adds <hr> element below link
> BL-1570 Anchor tag to related items

- app/assets/javascripts/application.js
- app/javascript/packs/controllers/show_controller.js
- Adjust margins for the article and database secondary fields
> BL-1568 Record page layout

- app/javascript/packs/application.js
- app/javascript/packs/controllers/advanced_controller.js
- app/javascript/packs/controllers/availability_controller.js
- app/javascript/packs/controllers/explanation_controller.js
- app/javascript/packs/controllers/fines_controller.js
- app/javascript/packs/controllers/form_controller.js
- app/javascript/packs/controllers/holds_controller.js
- app/javascript/packs/controllers/index_controller.js
- app/javascript/packs/controllers/lib-guides_controller.js
- app/javascript/packs/controllers/loans_controller.js
- app/javascript/packs/controllers/primo_controller.js
- app/javascript/packs/controllers/query_list_controller.js
- app/javascript/packs/controllers/show_controller.js
- bin/webpack
- bin/yarn
- config/initializers/assets.rb
- config/initializers/content_security_policy.rb
- package.json
- spec/javascript/packs/controllers/availability_controller.spec.js
- spec/javascript/setup/mutation-observer.js
- yarn.lock
* Complete overall of JS Deps in order to get rid of our dep to
a critical vulnerability in the json-schema library.
* Updates stimulus and dependencies to latest version
* Updates webpacker and deps to latest version.
* Update development JS
> Update JS Deps.

- .circleci/config.yml
- also updates ruby orb to latest version
> Use cimg images

- app/controllers/concerns/quik_pay.rb
- config/quik_pay.yml
* Updates the service URL.
* Updates default configuration.
> Update quick_pay service URL.

- .docker/app/Dockerfile.prod
- .docker/ci-app/Dockerfile.ci
- Gemfile
- Gemfile.lock
- bundler version updated in Dockerfile
- i18n package referenced in Gemfile.lock was removed, so needed to update that to new version
- Pinned faraday gem for now so that we don't have to deal with failing tests
> Fix gitlab pipeline

- app/controllers/concerns/quik_pay.rb
- config/quik_pay.yml
- spec/controllers/quik_pay_spec.rb
* Needed to deploy to production.
> Make quik_pay_url configurable.

- config/locales/en.yml
> BL-1608 Payment feature styling

- .docker/app/Dockerfile.prod
I tried to fix all of them but I think I ran into a hadolint bug and so
am ignoring one that just was not fixable.
> Fix dockerfile lint issues.

- app/javascript/packs/controllers/form_controller.js
- Reset the description select menu to display all options if material type is deselected
> BL-1321 Request form bug

- app/assets/stylesheets/partials/_bento.scss
- app/helpers/application_helper.rb
- app/views/layouts/_bento_box_wrapper.html.erb
- Fix styling issue with bento links to full/online results
> BL-1621 GA Trackers

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_requests.scss
- app/assets/stylesheets/partials/_vars.scss
- app/helpers/catalog_helper.rb
- app/helpers/request_helper.rb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_online_availability_button.html.erb
- app/views/catalog/_purchase_order_anonymous_button.html.erb
- app/views/catalog/_show_availability_section.html.erb
- Updates the styling of all availability buttons except Not Available
- Updates the layout of the request button
> BL-1639 Availability buttons

- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_vars.scss
- app/helpers/availability_helper.rb
- app/views/almaws/item.html.erb
- app/views/catalog/_online_availability.html.erb
- app/views/catalog/_physical_availability_card.html.erb
- app/views/primo_central/_direct_link.html.erb
- Update colors for availability heading section and rows
- Update fonts for availability heading
- Add styled summary label
> BL-1617 Styling updates for physical item / online availability displays

- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_bento.scss
- app/assets/stylesheets/partials/_requests.scss
- app/helpers/catalog_helper.rb
- app/helpers/request_helper.rb
- app/views/catalog/_hathitrust_button.html.erb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_online_availability_button.html.erb
- app/views/catalog/_purchase_order_anonymous_button.html.erb
- app/views/catalog/_show_availability_section.html.erb
- app/views/primo_central/_libkey_btn.html.erb
- app/views/primo_central/_online_button.html.erb
- app/views/search/_blacklight_availability.html.erb
Minor revisions to new availability button designs, including: 
- Fix "Not Available" icon color
- Adjust request button styling to apply only to search results and record page request buttons
- Apply new button colors to bento/query list "Online" buttons
- Adjust padding for all availability buttons, which included removing "btn-sm" from html classes
- Standardize padding/borders for all availability button types (except smaller bento/query list buttons)
> BL-1639 Revisions to new availability button designs

- app/views/catalog/_online_availability.html.erb
- app/views/catalog/_online_availability_button.html.erb
- Adds header to search results
- Removes border from record page online items
> BL-1638 Online availability

- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/partials/_availability.scss
- app/views/almaws/item.html.erb
- app/views/catalog/_index_availability_section.html.erb
- app/views/catalog/_physical_availability_card.html.erb
- app/views/catalog/_show_availability_section.html.erb
- Adds border-top to table heading
- Use 1px border for table
- Decreases padding for table heading
- Fixes styling for special instructions
> BL-1617 Physical item availability

- app/assets/stylesheets/partials/_availability.scss
- Adjust font size styling for available button, as it was affecting the overall size of the button
- Adjust available button margins so that it appears in mobile view
> BL-1639 Update available button sizing and margins

- app/views/catalog/_hathitrust_button.html.erb
- app/views/catalog/_online_availability_button.html.erb
- app/views/primo_central/_online_button.html.erb
- Add Online header for hathitrust links in search results
- Remove padding for article iframe container in search results
- Add margin-top for online dropdown container
> BL-1639 Adjust online dropdown margins and padding, plus hathitrust header

- app/assets/javascripts/application.js
- Load tooltip on turbolinks:load so that they always appear
> BL-1637 Bootstrap tooltips

- .gitlab-ci.yml
For now I will keep the other non helm deployment.
> DEVO-572: Add helm chart deployment.

- .gitlab-ci.yml
Updating to use "librarysearch" helm chart instead of "cob" helm chart.
> Use librarysearch helm chart.

- .gitlab-ci.yml
Update image name used to deploy librarysearch-qa.
> Fix librarysearch-qa deployment.

- Gemfile.lock
Reverts tulibraries/tul_cob#3194
> Revert "Bump omniauth from 2.0.4 to 2.1.0"

- app/models/user.rb
Search for email when creating a new user.
> BL-1589: Fix Mysql2::Error: Duplicate entry

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
This reverts commit cdd4a1659892a39dfc6788fb685f9852aa32b5ce.
> Revert "Modify Available at display to suppress ambler holdings"

- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/partials/_advanced.scss
- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_bento.scss
- app/assets/stylesheets/partials/_bookmarks.scss
- app/assets/stylesheets/partials/_citation_form.scss
- app/assets/stylesheets/partials/_facets.scss
- app/assets/stylesheets/partials/_query_lists.scss
- app/assets/stylesheets/partials/_record_pages.scss
- app/assets/stylesheets/partials/_requests.scss
- app/assets/stylesheets/partials/_sms_form.scss
- app/assets/stylesheets/partials/_users.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/advanced/index.html.erb
- app/views/layouts/blacklight.html.erb
Updated and cleaned up stylesheets for headers. I haven't done the University Libraries header section or the search index displays yet to avoid merge conflicts. Buttons will also be in a separate PR.
> BL-1667 Update Library Search fonts for headers

- app/views/catalog/_sms_form.html.erb
Issue is not redirect but the fact that the modal is not working as expected.
This changes updates the modal so that it works as expected.
> BL-1647: Fix redirect issue after SMS

- app/assets/javascripts/blacklight_alma/blacklight_alma_lib.js
- app/assets/stylesheets/partials/_colors.scss
- app/assets/stylesheets/partials/_index_results.scss
- app/assets/stylesheets/partials/_record_pages.scss
- app/helpers/catalog_helper.rb
- app/views/catalog/_fields.html.erb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_index_header.html.erb
- app/views/catalog/index.html.erb
- app/views/layouts/blacklight.html.erb
Started off as BL-1667 work. 
I needed to restructure the styles for index results to isolate document elements to just those page types. I also was playing around the responsive design to align the text for mobile views, switching over a flex approach. 
@cdoyle-temple Handing this off to you, since you starting this work. Let me know if you want to talk about anything here.
> BL-1671 Updating index page fonts and spacing

- app/controllers/users_controller.rb
- app/views/users/_user_loans.html.erb
REF: https://stackoverflow.com/a/36591178/256854
REF: https://apidock.com/rails/ActionView/Helpers/FormHelper/form_for
We need to apply the format: :js to the path, but we also need to use
form_for with remote: true in order for js to be loaded in the current
page vs. going to that js page.
> BL-1690: Fixes unrecognized format error when renewing books.

- app/views/catalog/_index_default.html.erb
- app/views/catalog/_show_default.html.erb
* Removes alt text for book covers and default images
* Removes book cover links to full record pages
> BL-1696 Book cover updates

- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_bento.scss
- app/assets/stylesheets/partials/_bookmarks.scss
- app/assets/stylesheets/partials/_colors.scss
- app/assets/stylesheets/partials/_footer.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_index_results.scss
- app/assets/stylesheets/partials/_record_tools.scss
- app/assets/stylesheets/partials/_requests.scss
- app/assets/stylesheets/partials/_users.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/almaws/_resource_sharing_broker_allowed.html.erb
- app/views/bookmarks/_clear_bookmarks_widget.html.erb
- app/views/bookmarks/_show_tools.html.erb
- app/views/bookmarks/_sort_and_per_page.html.erb
- app/views/catalog/_previous_next_doc.html.erb
- app/views/catalog/_show_tools.html.erb
- app/views/users/_loans_details.html.erb
- app/views/users/_quik_pay_button.html.erb
- Update default stylings for btn, including Faustina font family, default line height, and border-radius
- Clean up button code and type standardize button stylings as much as possible
> BL-1709 Button updates

- app/views/catalog/_index_header.html.erb
> Remove an unsued name paramter value in _index_header.html.erb

- package.json
- yarn.lock
k8s scan is failing due to fixable security issue. Updating yarn packages will resolve this issue.
> BL-1722: Update yarn packages.

- app/controllers/almaws_controller.rb
Fixes bug with requesting bookbot media item for faculty and library
staff user groups.
> BL-1729: Collapse multiple request options.

- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/partials/_colors.scss
- app/assets/stylesheets/partials/_index_results.scss
- app/assets/stylesheets/partials/_record_pages.scss
- app/controllers/catalog_controller.rb
- app/controllers/databases_controller.rb
- app/controllers/primo_central_controller.rb
- app/controllers/web_content_controller.rb
- app/presenters/index_presenter.rb
- app/views/catalog/_fields.html.erb
- app/views/catalog/_index_default.html.erb
- app/views/catalog/_index_format_field.html.erb
- app/views/catalog/_index_header.html.erb
- app/views/catalog/_index_summary_field.html.erb
- app/views/web_content/_index_default.html.erb
- spec/controllers/catalog_controller_spec.rb
- spec/features/articles_spec.rb
- spec/features/indices_spec.rb
This does not include resource type icon updates or controller updates yet.
> BL-1702 Update title display design in search results

- yarn.lock
Fixes kubernetes deploy fails.
> Upgrade yarn packages for security fix.

- Gemfile
- Gemfile.lock
- spec/features/axe_spec.rb
- spec/spec_helper.rb
* Also adds some tests but skips them because they fail.
> BL-1699: Add axe rspec gem.

- config/environments/production.rb
> DEVO-657: Enable memcache_store for k8 instance.

- app/assets/stylesheets/partials/_availability.scss
- app/assets/stylesheets/partials/_requests.scss
- Revert "Available" button to green color
- Adjust boldness of buttons with crystal blue background
> BL-1757 Update availability buttons

- app/assets/stylesheets/partials/_availability.scss
- app/models/blacklight/primo_central/document.rb
- app/models/solr_document.rb
- app/views/catalog/_libkey_btn.html.erb
- app/views/catalog/_online_availability_button.html.erb
- app/views/catalog/_show_availability_section.html.erb
- app/views/primo_central/_libkey_btn.html.erb
- app/views/search/_primo_availability.html.erb
- config/bento.yml.example
- config/locales/en.yml
- spec/models/primo_central_document_spec.rb
- spec/models/solr_document_spec.rb
- Add libkey api integration for issn lookup in solr document model
- Update labels for doi lookup in primo document model to distinguish from new feature and update blanklight configs for deduplication
- Add libkey view for "View Journal Content" button and update existing libkey views
> BL-1746 Add LibKey Journal integration

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/views/catalog/_fields.html.erb
- app/views/catalog/_show_fields.html.erb
- spec/helpers/application_helper_spec.rb
- Adds back responsibility field values
- Adds comma separators to primo author index displays with multiple authors
> BL-1758 Update author/creator displays

- app/assets/javascripts/application.js
- app/assets/stylesheets/partials/_bookmarks.scss
- app/assets/stylesheets/partials/_record_tools.scss
- app/views/catalog/_show_default.html.erb
- app/views/catalog/_show_tools_navbar.html.erb
This reverts changes in https://github.com/tulibraries/tul_cob/pull/3145, due to a bug with bookmarks form. There is an error when multiple forms with the same label/input ids are present in the html, even when one is always visually hidden. 
This also includes a couple of minor styling changes for nav tools section that I noticed when doing this work.
> BL-1700 Fix error with bookmarks on record page

- app/models/search_builder.rb
- spec/models/search_builder_spec.rb
* Wraps call_number query value with * when using "contains" query
operator.
* Adds a * to end of value when using "begins_with" query  operator
> BL-1760: Update how we build call_number queries.

- .docker/app/Dockerfile.debugger
- Makefile
Adds a build job for creating debugging images.
> Add a way to run our debugger stuff on k8.

- app/controllers/application_controller.rb
- spec/controllers/bookmarks_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
- spec/controllers/users_controller_spec.rb
Fixes issue brought up during ITS secuirty scan.
> DEVO-790: Add privacy headers

- app/controllers/application_controller.rb
Check to see if this fixes issue we are having in k8.
> DEVO-791: Update header.

- .circleci/config.yml
- app/assets/javascripts/application.js
- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/partials/_facets.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_pagination.scss
- app/assets/stylesheets/tucob.scss.erb
- app/views/catalog/_explanation_div.html.erb
- app/views/catalog/_facets.html.erb
- app/views/catalog/_search_header.html.erb
- app/views/catalog/index.html.erb
> BL-1672 Simplify mobile display for Limit Your Search

- config/environments/production.rb
Since we removed google analytics gem we cannot reference GA anymore.
> Remove GA.tracker config.

- .gitlab-ci.yml
- Makefile
* Use new security scan method
* Update local security to skip non vulnerability checks.
> DEVO-825: Use new security scan.

- app/models/blacklight/primo_central/document.rb
- spec/models/primo_central_document_spec.rb
Reverts tulibraries/tul_cob#4002
> Revert "BL-1813: Temporarily add libproxy to get_it link."

- yarn.lock
there is a security issue that is failing the pipeline.  hoping this fixes it.
> upgrade yarn deps.

- app/assets/stylesheets/partials/_query_lists.scss
- app/views/query_list/show.html.erb
Accidentially removed responsive styling in previous PR
> BL-1654 Fix responsive styling for query lists

- app/assets/javascripts/application.js
- app/javascript/packs/controllers/loans_controller.js
- app/views/users/_loans_details.html.erb
- app/views/users/_user_loans.html.erb
Pulled from work that @cdoyle-temple did on separate branch and moved into loans controller
> BL-1818 Move loan renewals js to loans_controller

- .docker/app/Dockerfile.prod
> updated dependency tzdata

- .circleci/config.yml
Match the version of python ansible-airflow-playbook requires.
> BL-1841: Fix broken prod deployment

- Documentation/essential_packages.txt
- yarn.lock
> Add actionpack to essential packages documentation.

- app/search_engines/bento_search/cdm_engine.rb
- spec/fixtures/vcr_cassettes/bento_search_cdm_awards.yml
- spec/fixtures/vcr_cassettes/bento_search_cdm_theses.yml
- spec/search_engines/cdm_search_spec.rb
Holly requested two restricted collections
> BL-1829-update-digital-collections-results-on-bento-page

- app/views/record_mailer/email_record.html.erb
Honor new-line embedded in text created by `to_email_text` method.
> BL-1834 Break document lines

- app/search_engines/bento_search/cdm_engine.rb
Puts iiif call in its own rescue method because when it errors it breaks the calls coming after it
> refactor image calls to use iiif as default

- app/search_engines/bento_search/cdm_engine.rb
Reintroduce bug fix in https://github.com/tulibraries/tul_cob/pull/4290 into new code for collections.
> BL-1852 Handle empty collections in cdm integration

- app/components/query_list_component.html.erb
- app/components/query_list_component.rb
- app/controllers/query_list_controller.rb
- app/helpers/query_list_helper.rb
- app/models/concerns/query_listable.rb
- app/models/query_list.rb
- app/models/solr_document.rb
- app/views/query_list/show.html.erb
- spec/components/query_list_component_spec.rb
- spec/helpers/query_list_helper_spec.rb
- spec/models/concerns/query_listable_spec.rb
* Moved document related function to a document concern module.
* Made query_list a component.
> BL-1869: Refactor Query List.

- app/controllers/catalog_controller.rb
- app/controllers/query_list_controller.rb
* Enables action caching.
*  Disables search tracking which breaks action caching.
> Bl-1848: Add action caching.

- app/controllers/almaws_controller.rb
I accidentially removed @item_level_locations from the almaws controller.
> BL-1866 Fix error in request refactoring

- app/assets/stylesheets/icons.css.erb
- app/assets/stylesheets/tucob.scss.erb
- app/views/almaws/request_options.html.erb
- app/views/catalog/purchase_order.html.erb
- config/locales/en.yml
Replaced headers of the forms with the standard Blacklight modal header view component.
> BL-1867 Use default close button

- Documentation/Node.js-CVE-2024-4067
- Documentation/essential_packages.txt
Needs to also be in essential-packages.txt
> Micromatch documentation

- app/views/bookmarks/_show_tools.html.erb
- app/views/catalog/_show_tools.html.erb
I've just commented out the logic in the relevant views so that we can revert easily if needed.
> BL-1899 Suppress citation button temporarily

- Documentation/body-parse-CVE-2024-45590
- Documentation/path-to-regexp-CVE-2024-45296
- These are new CVEs.  NVD indicates still under analysis
> Waiver for new vulnerabilities

- Documentation/Node.js-CVE-2024-43799
- Documentation/body-parse-CVE-2024-45590
- Documentation/essential_packages.txt
- Documentation/path-to-regexp-CVE-2024-45296
- yarn.lock
- Remove waivers
- Update yarn package versions
> Update packages that address recent CVEs

- app/assets/stylesheets/tucob.scss
This class is still on the BS website's guide, but does not appear anywhere in the code
> BL-1914-borders-less-visible-in-everything-page

- app/components/facet_item_pivot_component.rb
> Bootstrap Data Attributes

- .docker/app/Dockerfile.prod
- Documentation/Ruby-CVE-2024-49761
- Documentation/essential_packages.txt
- Gemfile
- Gemfile.lock
- Update package dependencies
- waive vulnerability until selenium-web-driver updates rexml version
- Remove MySQL package and gems
> CVE-2024-49761 Waiver

- app/assets/stylesheets/partials/_record_pages.scss
- app/assets/stylesheets/tucob.scss
- app/helpers/catalog_helper.rb
> BL-1919-fix-multi-subject-links-when-hovered-over

- config/alma.yml.example
- config/alma.yml.local
> Alma Config File

- app/controllers/primo_central_controller.rb
* Also disable recaptcha completly if user is logged in.
> Only verify recaptcha once per user session.

- .circleci/config.yml
- app/middleware/block_suspicious_requests.rb
- config/application.rb
Return a 400 error when someone tries to inject invalid parameters into the url
> BL-1937 Block suspicious requests

- Gemfile.lock
Includes primo and lc_solr_sortable updates
> bundle update cob indexes

- .circleci/config.yml
- Makefile
Fixes dependabot PRs break due to caching issues.
> Do not use cache for dependabot PRs.

- .docker/app/Dockerfile.prod
Reverts tulibraries/tul_cob#5172
> Revert "creates secure-tmp folders as root"
